// Code generated by xgo (XGo); DO NOT EDIT.

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"github.com/fanfeilong/xgoup/internal/buildinfo"
	"github.com/fanfeilong/xgoup/internal/home"
	"github.com/fanfeilong/xgoup/internal/resolve"
	"github.com/fanfeilong/xgoup/internal/selfupdate"
	"github.com/fanfeilong/xgoup/internal/toolchain"
	"os"
	"os/exec"
)

const _ = true
//line cmd/xgoup/main.xgo:16
func main() {
//line cmd/xgoup/main.xgo:16:1
	printUsage := func() {
//line cmd/xgoup/main.xgo:17:1
		fmt.Println(`xgoup - XGo toolchain manager

Usage:
  xgoup init
  xgoup toolchain install <name> [--method <standard|source|linked>] [--ref <git-ref>] [--repo <url>] [--path <dir>] [--force]
  xgoup toolchain update [name]
  xgoup toolchain list [--json]
  xgoup toolchain remove <name> [--purge]
  xgoup default <name>
  xgoup run [--toolchain <name>] <xgo-args...>
  xgoup which [--toolchain <name>]
  xgoup env [--toolchain <name>] [--shell <sh|zsh|fish|powershell>]
  xgoup doctor
  xgoup self update
  xgoup self uninstall [--force]

Compatibility aliases (deprecated):
  xgoup install ...   -> xgoup toolchain install ... --method source
  xgoup update ...    -> xgoup toolchain update ...
  xgoup list          -> xgoup toolchain list

Global options:
  -h, --help
  -V, --version`)
	}
//line cmd/xgoup/main.xgo:43:1
	printVersion := func() {
//line cmd/xgoup/main.xgo:44:1
		v := buildinfo.Version
//line cmd/xgoup/main.xgo:45:1
		if v == "" {
//line cmd/xgoup/main.xgo:46:1
			v = "dev"
		}
//line cmd/xgoup/main.xgo:48:1
		fmt.Println("xgoup", v)
	}
//line cmd/xgoup/main.xgo:51:1
	dieUsage := func(msg string) {
//line cmd/xgoup/main.xgo:52:1
		fmt.Fprintln(os.Stderr, "[xgoup] ERROR:", msg)
//line cmd/xgoup/main.xgo:53:1
		fmt.Fprintln(os.Stderr)
//line cmd/xgoup/main.xgo:54:1
		printUsage()
//line cmd/xgoup/main.xgo:55:1
		os.Exit(2)
	}
//line cmd/xgoup/main.xgo:58:1
	args := os.Args[1:]
//line cmd/xgoup/main.xgo:59:1
	if len(args) == 0 {
//line cmd/xgoup/main.xgo:60:1
		printUsage()
//line cmd/xgoup/main.xgo:61:1
		os.Exit(0)
	}
//line cmd/xgoup/main.xgo:64:1
	switch args[0] {
//line cmd/xgoup/main.xgo:65:1
	case "-h", "--help", "help":
//line cmd/xgoup/main.xgo:66:1
		printUsage()
//line cmd/xgoup/main.xgo:67:1
		os.Exit(0)
//line cmd/xgoup/main.xgo:68:1
	case "-V", "--version", "version":
//line cmd/xgoup/main.xgo:69:1
		printVersion()
//line cmd/xgoup/main.xgo:70:1
		os.Exit(0)
	}
//line cmd/xgoup/main.xgo:74:1
	if args[0] == "install" {
//line cmd/xgoup/main.xgo:76:1
		args = append([]string{"toolchain", "install"}, args[1:]...) 
//line cmd/xgoup/main.xgo:77:1
		args = append(args, "--method", "source")
	} else
//line cmd/xgoup/main.xgo:78:1
	if args[0] == "update" {
//line cmd/xgoup/main.xgo:79:1
		args = append([]string{"toolchain", "update"}, args[1:]...)
	} else
//line cmd/xgoup/main.xgo:80:1
	if args[0] == "list" {
//line cmd/xgoup/main.xgo:81:1
		args = append([]string{"toolchain", "list"}, args[1:]...)
	}
//line cmd/xgoup/main.xgo:84:1
	cmd := args[0]
//line cmd/xgoup/main.xgo:85:1
	rest := args[1:]
//line cmd/xgoup/main.xgo:87:1
	die := func(err error) {
//line cmd/xgoup/main.xgo:88:1
		fmt.Fprintln(os.Stderr, "[xgoup] ERROR:", err.Error())
//line cmd/xgoup/main.xgo:89:1
		os.Exit(1)
	}
//line cmd/xgoup/main.xgo:92:1
	orDefault := func(v string, def string) string {
//line cmd/xgoup/main.xgo:93:1
		if v != "" {
//line cmd/xgoup/main.xgo:94:1
			return v
		}
//line cmd/xgoup/main.xgo:96:1
		return def
	}
//line cmd/xgoup/main.xgo:99:1
	execCommand := func(name string, args ...string) *exec.Cmd {
//line cmd/xgoup/main.xgo:100:1
		return exec.Command(name, args...)
	}
//line cmd/xgoup/main.xgo:104:1
	globalHome := ""
//line cmd/xgoup/main.xgo:105:1
	for
//line cmd/xgoup/main.xgo:105:1
	i := 0; i < len(rest);
//line cmd/xgoup/main.xgo:105:1
	i++ {
//line cmd/xgoup/main.xgo:106:1
		if rest[i] == "--home" && i+1 < len(rest) {
//line cmd/xgoup/main.xgo:107:1
			globalHome = rest[i+1]
//line cmd/xgoup/main.xgo:108:1
			rest = append(rest[:i], rest[i+2:]...) 
//line cmd/xgoup/main.xgo:109:1
			break
		}
	}
//line cmd/xgoup/main.xgo:112:1
	if globalHome != "" {
//line cmd/xgoup/main.xgo:113:1
		_ = os.Setenv("XGOUP_HOME", globalHome)
	}
//line cmd/xgoup/main.xgo:116:1
	switch cmd {
//line cmd/xgoup/main.xgo:117:1
	case "init":
//line cmd/xgoup/main.xgo:118:1
		p, c, err := toolchain.Init()
//line cmd/xgoup/main.xgo:119:1
		if err != nil {
//line cmd/xgoup/main.xgo:120:1
			die(err)
		}
//line cmd/xgoup/main.xgo:122:1
		_ = p
//line cmd/xgoup/main.xgo:123:1
		_ = c
//line cmd/xgoup/main.xgo:124:1
		fmt.Println("[xgoup] initialized home")
//line cmd/xgoup/main.xgo:125:1
		os.Exit(0)
//line cmd/xgoup/main.xgo:126:1
	case "toolchain":
//line cmd/xgoup/main.xgo:127:1
		if len(rest) == 0 {
//line cmd/xgoup/main.xgo:128:1
			dieUsage("missing toolchain subcommand")
		}
//line cmd/xgoup/main.xgo:130:1
		switch rest[0] {
//line cmd/xgoup/main.xgo:131:1
		case "install":
//line cmd/xgoup/main.xgo:132:1
			fs := flag.NewFlagSet("toolchain install", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:133:1
			method := fs.String("method", "standard", "")
//line cmd/xgoup/main.xgo:134:1
			repo := fs.String("repo", "", "")
//line cmd/xgoup/main.xgo:135:1
			ref := fs.String("ref", "", "")
//line cmd/xgoup/main.xgo:136:1
			path := fs.String("path", "", "")
//line cmd/xgoup/main.xgo:137:1
			force := fs.Bool("force", false, "")
//line cmd/xgoup/main.xgo:138:1
			_ = fs.Parse(rest[1:])
//line cmd/xgoup/main.xgo:139:1
			pos := fs.Args()
//line cmd/xgoup/main.xgo:140:1
			if len(pos) < 1 {
//line cmd/xgoup/main.xgo:141:1
				dieUsage("toolchain install requires <name>")
			}
//line cmd/xgoup/main.xgo:143:1
			name := pos[0]
//line cmd/xgoup/main.xgo:144:1
			p, c, err := toolchain.Init()
//line cmd/xgoup/main.xgo:145:1
			if err != nil {
//line cmd/xgoup/main.xgo:146:1
				die(err)
			}
//line cmd/xgoup/main.xgo:148:1
			_, err = toolchain.Install(p, c, name, toolchain.InstallOptions{Method: *method, Repo: *repo, Ref: *ref, Path: *path, Force: *force})
//line cmd/xgoup/main.xgo:155:1
			if err != nil {
//line cmd/xgoup/main.xgo:156:1
				die(err)
			}
//line cmd/xgoup/main.xgo:158:1
			fmt.Println("[xgoup] installed toolchain", name)
//line cmd/xgoup/main.xgo:159:1
			os.Exit(0)
//line cmd/xgoup/main.xgo:160:1
		case "update":
//line cmd/xgoup/main.xgo:161:1
			fs := flag.NewFlagSet("toolchain update", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:162:1
			_ = fs.Parse(rest[1:])
//line cmd/xgoup/main.xgo:163:1
			pos := fs.Args()
//line cmd/xgoup/main.xgo:164:1
			name := ""
//line cmd/xgoup/main.xgo:165:1
			if len(pos) > 0 {
//line cmd/xgoup/main.xgo:166:1
				name = pos[0]
			}
//line cmd/xgoup/main.xgo:168:1
			p, c, err := toolchain.Init()
//line cmd/xgoup/main.xgo:169:1
			if err != nil {
//line cmd/xgoup/main.xgo:170:1
				die(err)
			}
//line cmd/xgoup/main.xgo:172:1
			_, err = toolchain.Update(p, c, name)
//line cmd/xgoup/main.xgo:173:1
			if err != nil {
//line cmd/xgoup/main.xgo:174:1
				die(err)
			}
//line cmd/xgoup/main.xgo:176:1
			fmt.Println("[xgoup] updated toolchain", orDefault(name, c.DefaultToolchain))
//line cmd/xgoup/main.xgo:177:1
			os.Exit(0)
//line cmd/xgoup/main.xgo:178:1
		case "list":
//line cmd/xgoup/main.xgo:179:1
			fs := flag.NewFlagSet("toolchain list", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:180:1
			jsonOut := fs.Bool("json", false, "")
//line cmd/xgoup/main.xgo:181:1
			_ = fs.Parse(rest[1:])
//line cmd/xgoup/main.xgo:182:1
			p, c, err := toolchain.Init()
//line cmd/xgoup/main.xgo:183:1
			if err != nil {
//line cmd/xgoup/main.xgo:184:1
				die(err)
			}
//line cmd/xgoup/main.xgo:186:1
			items, err := toolchain.List(p, c)
//line cmd/xgoup/main.xgo:187:1
			if err != nil {
//line cmd/xgoup/main.xgo:188:1
				die(err)
			}
//line cmd/xgoup/main.xgo:190:1
			if *jsonOut {
//line cmd/xgoup/main.xgo:191:1
				b, _ := json.Marshal(items)
//line cmd/xgoup/main.xgo:192:1
				fmt.Println(string(b))
			} else {
				for
//line cmd/xgoup/main.xgo:194:1
				_, m := range items {
//line cmd/xgoup/main.xgo:195:1
					fmt.Printf("%s\t%s\t%s\n", m.Name, m.Kind, m.RootPath)
				}
			}
//line cmd/xgoup/main.xgo:198:1
			os.Exit(0)
//line cmd/xgoup/main.xgo:199:1
		case "remove":
//line cmd/xgoup/main.xgo:200:1
			fs := flag.NewFlagSet("toolchain remove", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:201:1
			purge := fs.Bool("purge", false, "")
//line cmd/xgoup/main.xgo:202:1
			_ = fs.Parse(rest[1:])
//line cmd/xgoup/main.xgo:203:1
			pos := fs.Args()
//line cmd/xgoup/main.xgo:204:1
			if len(pos) < 1 {
//line cmd/xgoup/main.xgo:205:1
				dieUsage("toolchain remove requires <name>")
			}
//line cmd/xgoup/main.xgo:207:1
			name := pos[0]
//line cmd/xgoup/main.xgo:208:1
			p, c, err := toolchain.Init()
//line cmd/xgoup/main.xgo:209:1
			if err != nil {
//line cmd/xgoup/main.xgo:210:1
				die(err)
			}
//line cmd/xgoup/main.xgo:212:1
			_, err = toolchain.Remove(p, c, name, *purge)
//line cmd/xgoup/main.xgo:213:1
			if err != nil {
//line cmd/xgoup/main.xgo:214:1
				die(err)
			}
//line cmd/xgoup/main.xgo:216:1
			fmt.Println("[xgoup] removed toolchain", name)
//line cmd/xgoup/main.xgo:217:1
			os.Exit(0)
//line cmd/xgoup/main.xgo:218:1
		default:
//line cmd/xgoup/main.xgo:219:1
			dieUsage("unknown toolchain subcommand: " + rest[0])
		}
//line cmd/xgoup/main.xgo:221:1
	case "default":
//line cmd/xgoup/main.xgo:222:1
		if len(rest) < 1 {
//line cmd/xgoup/main.xgo:223:1
			dieUsage("default requires <name>")
		}
//line cmd/xgoup/main.xgo:225:1
		name := rest[0]
//line cmd/xgoup/main.xgo:226:1
		p, c, err := toolchain.Init()
//line cmd/xgoup/main.xgo:227:1
		if err != nil {
//line cmd/xgoup/main.xgo:228:1
			die(err)
		}
//line cmd/xgoup/main.xgo:230:1
		_, err = toolchain.SetDefault(p, c, name)
//line cmd/xgoup/main.xgo:231:1
		if err != nil {
//line cmd/xgoup/main.xgo:232:1
			die(err)
		}
//line cmd/xgoup/main.xgo:234:1
		fmt.Println("[xgoup] default toolchain set to", name)
//line cmd/xgoup/main.xgo:235:1
		os.Exit(0)
//line cmd/xgoup/main.xgo:236:1
	case "run":
//line cmd/xgoup/main.xgo:237:1
		fs := flag.NewFlagSet("run", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:238:1
		tcn := fs.String("toolchain", "", "")
//line cmd/xgoup/main.xgo:239:1
		_ = fs.Parse(rest)
//line cmd/xgoup/main.xgo:240:1
		xgoArgs := fs.Args()
//line cmd/xgoup/main.xgo:241:1
		if len(xgoArgs) == 0 {
//line cmd/xgoup/main.xgo:242:1
			dieUsage("run requires <xgo args...>")
		}
//line cmd/xgoup/main.xgo:244:1
		p, c, err := toolchain.Init()
//line cmd/xgoup/main.xgo:245:1
		if err != nil {
//line cmd/xgoup/main.xgo:246:1
			die(err)
		}
//line cmd/xgoup/main.xgo:248:1
		cwd, _ := os.Getwd()
//line cmd/xgoup/main.xgo:249:1
		r, err := resolve.ResolveToolchain(p, c, *tcn, cwd)
//line cmd/xgoup/main.xgo:250:1
		if err != nil {
//line cmd/xgoup/main.xgo:251:1
			die(err)
		}
//line cmd/xgoup/main.xgo:254:1
		cmd := execCommand(r.XgoExe, xgoArgs...) 
//line cmd/xgoup/main.xgo:255:1
		cmd.Env = append(os.Environ(), "XGOROOT="+r.XgoRoot, "PATH="+r.BinDir+string(os.PathListSeparator)+os.Getenv("PATH"))
//line cmd/xgoup/main.xgo:259:1
		cmd.Stdout = os.Stdout
//line cmd/xgoup/main.xgo:260:1
		cmd.Stderr = os.Stderr
//line cmd/xgoup/main.xgo:261:1
		cmd.Stdin = os.Stdin
//line cmd/xgoup/main.xgo:262:1
		if
//line cmd/xgoup/main.xgo:262:1
		err := cmd.Run(); err != nil {
//line cmd/xgoup/main.xgo:263:1
			die(err)
		}
//line cmd/xgoup/main.xgo:265:1
		os.Exit(0)
//line cmd/xgoup/main.xgo:266:1
	case "which":
//line cmd/xgoup/main.xgo:267:1
		fs := flag.NewFlagSet("which", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:268:1
		tcn := fs.String("toolchain", "", "")
//line cmd/xgoup/main.xgo:269:1
		_ = fs.Parse(rest)
//line cmd/xgoup/main.xgo:270:1
		p, c, err := toolchain.Init()
//line cmd/xgoup/main.xgo:271:1
		if err != nil {
//line cmd/xgoup/main.xgo:272:1
			die(err)
		}
//line cmd/xgoup/main.xgo:274:1
		cwd, _ := os.Getwd()
//line cmd/xgoup/main.xgo:275:1
		r, err := resolve.ResolveToolchain(p, c, *tcn, cwd)
//line cmd/xgoup/main.xgo:276:1
		if err != nil {
//line cmd/xgoup/main.xgo:277:1
			die(err)
		}
//line cmd/xgoup/main.xgo:279:1
		fmt.Println(r.XgoExe)
//line cmd/xgoup/main.xgo:280:1
		os.Exit(0)
//line cmd/xgoup/main.xgo:281:1
	case "env":
//line cmd/xgoup/main.xgo:282:1
		fs := flag.NewFlagSet("env", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:283:1
		tcn := fs.String("toolchain", "", "")
//line cmd/xgoup/main.xgo:284:1
		shell := fs.String("shell", "powershell", "")
//line cmd/xgoup/main.xgo:285:1
		_ = fs.Parse(rest)
//line cmd/xgoup/main.xgo:286:1
		p, c, err := toolchain.Init()
//line cmd/xgoup/main.xgo:287:1
		if err != nil {
//line cmd/xgoup/main.xgo:288:1
			die(err)
		}
//line cmd/xgoup/main.xgo:290:1
		cwd, _ := os.Getwd()
//line cmd/xgoup/main.xgo:291:1
		r, err := resolve.ResolveToolchain(p, c, *tcn, cwd)
//line cmd/xgoup/main.xgo:292:1
		if err != nil {
//line cmd/xgoup/main.xgo:293:1
			die(err)
		}
//line cmd/xgoup/main.xgo:295:1
		switch *shell {
//line cmd/xgoup/main.xgo:296:1
		case "powershell":
//line cmd/xgoup/main.xgo:297:1
			fmt.Printf("$env:XGOROOT = \"%s\"\n", r.XgoRoot)
//line cmd/xgoup/main.xgo:298:1
			fmt.Printf("$env:PATH = \"%s%c\" + $env:PATH\n", r.BinDir, os.PathListSeparator)
//line cmd/xgoup/main.xgo:299:1
		case "sh", "zsh":
//line cmd/xgoup/main.xgo:300:1
			fmt.Printf("export XGOROOT=\"%s\"\n", r.XgoRoot)
//line cmd/xgoup/main.xgo:301:1
			fmt.Printf("export PATH=\"%s:%s\"\n", r.BinDir, "$PATH")
//line cmd/xgoup/main.xgo:302:1
		default:
//line cmd/xgoup/main.xgo:303:1
			dieUsage("unsupported shell: " + *shell)
		}
//line cmd/xgoup/main.xgo:305:1
		os.Exit(0)
//line cmd/xgoup/main.xgo:306:1
	case "doctor":
//line cmd/xgoup/main.xgo:307:1
		p, c, err := toolchain.Init()
//line cmd/xgoup/main.xgo:308:1
		if err != nil {
//line cmd/xgoup/main.xgo:309:1
			die(err)
		}
//line cmd/xgoup/main.xgo:311:1
		if
//line cmd/xgoup/main.xgo:311:1
		err := toolchain.Doctor(p, c); err != nil {
//line cmd/xgoup/main.xgo:312:1
			die(err)
		}
//line cmd/xgoup/main.xgo:314:1
		fmt.Println("[xgoup] doctor: ok")
//line cmd/xgoup/main.xgo:315:1
		os.Exit(0)
//line cmd/xgoup/main.xgo:316:1
	case "self":
//line cmd/xgoup/main.xgo:317:1
		if len(rest) == 0 {
//line cmd/xgoup/main.xgo:318:1
			dieUsage("missing self subcommand")
		}
//line cmd/xgoup/main.xgo:320:1
		switch rest[0] {
//line cmd/xgoup/main.xgo:321:1
		case "update":
//line cmd/xgoup/main.xgo:322:1
			fs := flag.NewFlagSet("self update", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:323:1
			repo := fs.String("repo", os.Getenv("XGOUP_GITHUB_REPO"), "")
//line cmd/xgoup/main.xgo:324:1
			_ = fs.Parse(rest[1:])
//line cmd/xgoup/main.xgo:325:1
			path, err := selfupdate.Update(selfupdate.Options{Repo: *repo})
//line cmd/xgoup/main.xgo:326:1
			if err != nil {
//line cmd/xgoup/main.xgo:327:1
				die(err)
			}
//line cmd/xgoup/main.xgo:329:1
			fmt.Println("[xgoup] updated:", path)
//line cmd/xgoup/main.xgo:330:1
			os.Exit(0)
//line cmd/xgoup/main.xgo:331:1
		case "uninstall":
//line cmd/xgoup/main.xgo:332:1
			fs := flag.NewFlagSet("self uninstall", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:333:1
			force := fs.Bool("force", false, "")
//line cmd/xgoup/main.xgo:334:1
			_ = fs.Parse(rest[1:])
//line cmd/xgoup/main.xgo:335:1
			p, err := home.Resolve()
//line cmd/xgoup/main.xgo:336:1
			if err != nil {
//line cmd/xgoup/main.xgo:337:1
				die(err)
			}
//line cmd/xgoup/main.xgo:339:1
			if
//line cmd/xgoup/main.xgo:339:1
			err := selfupdate.Uninstall(p.Home, *force); err != nil {
//line cmd/xgoup/main.xgo:340:1
				die(err)
			}
//line cmd/xgoup/main.xgo:342:1
			fmt.Println("[xgoup] uninstalled home:", p.Home)
//line cmd/xgoup/main.xgo:343:1
			os.Exit(0)
//line cmd/xgoup/main.xgo:344:1
		default:
//line cmd/xgoup/main.xgo:345:1
			dieUsage("unknown self subcommand: " + rest[0])
		}
//line cmd/xgoup/main.xgo:347:1
	default:
//line cmd/xgoup/main.xgo:348:1
		dieUsage("unknown command: " + cmd)
	}
}
