// Code generated by xgo (XGo); DO NOT EDIT.

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"github.com/fanfeilong/xgoup/internal/bootstrap"
	"github.com/fanfeilong/xgoup/internal/buildinfo"
	"github.com/fanfeilong/xgoup/internal/home"
	"github.com/fanfeilong/xgoup/internal/meta"
	"github.com/fanfeilong/xgoup/internal/resolve"
	"github.com/fanfeilong/xgoup/internal/selfupdate"
	"github.com/fanfeilong/xgoup/internal/toolchain"
	"github.com/fanfeilong/xgoup/internal/userenv"
	"github.com/fanfeilong/xgoup/internal/xgodoc"
	"os"
	"os/exec"
)

const _ = true
//line cmd/xgoup/main.xgo:20
func main() {
//line cmd/xgoup/main.xgo:20:1
	printUsage := func() {
//line cmd/xgoup/main.xgo:21:1
		fmt.Println(`xgoup - XGo toolchain manager

Usage:
  xgoup init
  xgoup toolchain install <name> [--method <standard|source|linked>] [--ref <git-ref>] [--repo <url>] [--path <dir>] [--force]
  xgoup toolchain update [name]
  xgoup toolchain list [--json]
  xgoup toolchain remove <name> [--purge]
  xgoup default <name>
  xgoup run [--toolchain <name>] <xgo-args...>
  xgoup which [--toolchain <name>]
  xgoup env [--toolchain <name>] [--shell <sh|zsh|fish|powershell>]
  xgoup doctor
  xgoup doc [--no-browser] [--repo <owner/name>]
  xgoup self install [--repo <owner/name>] [--version latest|vX.Y.Z] [--modify-path] [--zip <path>]
  xgoup self update
  xgoup self uninstall [--force]

Compatibility aliases (deprecated):
  xgoup install ...   -> xgoup toolchain install ... --method source
  xgoup update ...    -> xgoup toolchain update ...
  xgoup list          -> xgoup toolchain list

Global options:
  -h, --help
  -V, --version`)
	}
//line cmd/xgoup/main.xgo:49:1
	printVersion := func() {
//line cmd/xgoup/main.xgo:50:1
		v := buildinfo.Version
//line cmd/xgoup/main.xgo:51:1
		if v == "" {
//line cmd/xgoup/main.xgo:52:1
			v = "dev"
		}
//line cmd/xgoup/main.xgo:54:1
		fmt.Println("xgoup", v)
	}
//line cmd/xgoup/main.xgo:57:1
	dieUsage := func(msg string) {
//line cmd/xgoup/main.xgo:58:1
		fmt.Fprintln(os.Stderr, "[xgoup] ERROR:", msg)
//line cmd/xgoup/main.xgo:59:1
		fmt.Fprintln(os.Stderr)
//line cmd/xgoup/main.xgo:60:1
		printUsage()
//line cmd/xgoup/main.xgo:61:1
		os.Exit(2)
	}
//line cmd/xgoup/main.xgo:64:1
	args := os.Args[1:]
//line cmd/xgoup/main.xgo:65:1
	if len(args) == 0 {
//line cmd/xgoup/main.xgo:66:1
		printUsage()
//line cmd/xgoup/main.xgo:67:1
		os.Exit(0)
	}
//line cmd/xgoup/main.xgo:70:1
	switch args[0] {
//line cmd/xgoup/main.xgo:71:1
	case "-h", "--help", "help":
//line cmd/xgoup/main.xgo:72:1
		printUsage()
//line cmd/xgoup/main.xgo:73:1
		os.Exit(0)
//line cmd/xgoup/main.xgo:74:1
	case "-V", "--version", "version":
//line cmd/xgoup/main.xgo:75:1
		printVersion()
//line cmd/xgoup/main.xgo:76:1
		os.Exit(0)
	}
//line cmd/xgoup/main.xgo:80:1
	if args[0] == "install" {
//line cmd/xgoup/main.xgo:82:1
		args = append([]string{"toolchain", "install"}, args[1:]...) 
//line cmd/xgoup/main.xgo:83:1
		args = append(args, "--method", "source")
	} else
//line cmd/xgoup/main.xgo:84:1
	if args[0] == "update" {
//line cmd/xgoup/main.xgo:85:1
		args = append([]string{"toolchain", "update"}, args[1:]...)
	} else
//line cmd/xgoup/main.xgo:86:1
	if args[0] == "list" {
//line cmd/xgoup/main.xgo:87:1
		args = append([]string{"toolchain", "list"}, args[1:]...)
	}
//line cmd/xgoup/main.xgo:90:1
	cmd := args[0]
//line cmd/xgoup/main.xgo:91:1
	rest := args[1:]
//line cmd/xgoup/main.xgo:93:1
	die := func(err error) {
//line cmd/xgoup/main.xgo:94:1
		fmt.Fprintln(os.Stderr, "[xgoup] ERROR:", err.Error())
//line cmd/xgoup/main.xgo:95:1
		os.Exit(1)
	}
//line cmd/xgoup/main.xgo:98:1
	orDefault := func(v string, def string) string {
//line cmd/xgoup/main.xgo:99:1
		if v != "" {
//line cmd/xgoup/main.xgo:100:1
			return v
		}
//line cmd/xgoup/main.xgo:102:1
		return def
	}
//line cmd/xgoup/main.xgo:105:1
	getenv := func(k string, def string) string {
//line cmd/xgoup/main.xgo:106:1
		if
//line cmd/xgoup/main.xgo:106:1
		v := os.Getenv(k); v != "" {
//line cmd/xgoup/main.xgo:107:1
			return v
		}
//line cmd/xgoup/main.xgo:109:1
		return def
	}
//line cmd/xgoup/main.xgo:112:1
	execCommand := func(name string, args ...string) *exec.Cmd {
//line cmd/xgoup/main.xgo:113:1
		return exec.Command(name, args...)
	}
//line cmd/xgoup/main.xgo:117:1
	globalHome := ""
//line cmd/xgoup/main.xgo:118:1
	for
//line cmd/xgoup/main.xgo:118:1
	i := 0; i < len(rest);
//line cmd/xgoup/main.xgo:118:1
	i++ {
//line cmd/xgoup/main.xgo:119:1
		if rest[i] == "--home" && i+1 < len(rest) {
//line cmd/xgoup/main.xgo:120:1
			globalHome = rest[i+1]
//line cmd/xgoup/main.xgo:121:1
			rest = append(rest[:i], rest[i+2:]...) 
//line cmd/xgoup/main.xgo:122:1
			break
		}
	}
//line cmd/xgoup/main.xgo:125:1
	if globalHome != "" {
//line cmd/xgoup/main.xgo:126:1
		_ = os.Setenv("XGOUP_HOME", globalHome)
	}
//line cmd/xgoup/main.xgo:129:1
	switch cmd {
//line cmd/xgoup/main.xgo:130:1
	case "init":
//line cmd/xgoup/main.xgo:131:1
		p, c, err := toolchain.Init()
//line cmd/xgoup/main.xgo:132:1
		if err != nil {
//line cmd/xgoup/main.xgo:133:1
			die(err)
		}
//line cmd/xgoup/main.xgo:135:1
		_ = p
//line cmd/xgoup/main.xgo:136:1
		_ = c
//line cmd/xgoup/main.xgo:137:1
		fmt.Println("[xgoup] initialized home")
//line cmd/xgoup/main.xgo:138:1
		os.Exit(0)
//line cmd/xgoup/main.xgo:139:1
	case "toolchain":
//line cmd/xgoup/main.xgo:140:1
		if len(rest) == 0 {
//line cmd/xgoup/main.xgo:141:1
			dieUsage("missing toolchain subcommand")
		}
//line cmd/xgoup/main.xgo:143:1
		switch rest[0] {
//line cmd/xgoup/main.xgo:144:1
		case "install":
//line cmd/xgoup/main.xgo:145:1
			fs := flag.NewFlagSet("toolchain install", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:146:1
			method := fs.String("method", "standard", "")
//line cmd/xgoup/main.xgo:147:1
			repo := fs.String("repo", "", "")
//line cmd/xgoup/main.xgo:148:1
			ref := fs.String("ref", "", "")
//line cmd/xgoup/main.xgo:149:1
			path := fs.String("path", "", "")
//line cmd/xgoup/main.xgo:150:1
			force := fs.Bool("force", false, "")
//line cmd/xgoup/main.xgo:151:1
			_ = fs.Parse(rest[1:])
//line cmd/xgoup/main.xgo:152:1
			pos := fs.Args()
//line cmd/xgoup/main.xgo:153:1
			if len(pos) < 1 {
//line cmd/xgoup/main.xgo:154:1
				dieUsage("toolchain install requires <name>")
			}
//line cmd/xgoup/main.xgo:156:1
			name := pos[0]
//line cmd/xgoup/main.xgo:157:1
			p, c, err := toolchain.Init()
//line cmd/xgoup/main.xgo:158:1
			if err != nil {
//line cmd/xgoup/main.xgo:159:1
				die(err)
			}
//line cmd/xgoup/main.xgo:161:1
			_, err = toolchain.Install(p, c, name, toolchain.InstallOptions{Method: *method, Repo: *repo, Ref: *ref, Path: *path, Force: *force})
//line cmd/xgoup/main.xgo:168:1
			if err != nil {
//line cmd/xgoup/main.xgo:169:1
				die(err)
			}
//line cmd/xgoup/main.xgo:171:1
			fmt.Println("[xgoup] installed toolchain", name)
//line cmd/xgoup/main.xgo:172:1
			os.Exit(0)
//line cmd/xgoup/main.xgo:173:1
		case "update":
//line cmd/xgoup/main.xgo:174:1
			fs := flag.NewFlagSet("toolchain update", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:175:1
			_ = fs.Parse(rest[1:])
//line cmd/xgoup/main.xgo:176:1
			pos := fs.Args()
//line cmd/xgoup/main.xgo:177:1
			name := ""
//line cmd/xgoup/main.xgo:178:1
			if len(pos) > 0 {
//line cmd/xgoup/main.xgo:179:1
				name = pos[0]
			}
//line cmd/xgoup/main.xgo:181:1
			p, c, err := toolchain.Init()
//line cmd/xgoup/main.xgo:182:1
			if err != nil {
//line cmd/xgoup/main.xgo:183:1
				die(err)
			}
//line cmd/xgoup/main.xgo:185:1
			_, err = toolchain.Update(p, c, name)
//line cmd/xgoup/main.xgo:186:1
			if err != nil {
//line cmd/xgoup/main.xgo:187:1
				die(err)
			}
//line cmd/xgoup/main.xgo:189:1
			fmt.Println("[xgoup] updated toolchain", orDefault(name, c.DefaultToolchain))
//line cmd/xgoup/main.xgo:190:1
			os.Exit(0)
//line cmd/xgoup/main.xgo:191:1
		case "list":
//line cmd/xgoup/main.xgo:192:1
			fs := flag.NewFlagSet("toolchain list", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:193:1
			jsonOut := fs.Bool("json", false, "")
//line cmd/xgoup/main.xgo:194:1
			_ = fs.Parse(rest[1:])
//line cmd/xgoup/main.xgo:195:1
			p, c, err := toolchain.Init()
//line cmd/xgoup/main.xgo:196:1
			if err != nil {
//line cmd/xgoup/main.xgo:197:1
				die(err)
			}
//line cmd/xgoup/main.xgo:199:1
			items, err := toolchain.List(p, c)
//line cmd/xgoup/main.xgo:200:1
			if err != nil {
//line cmd/xgoup/main.xgo:201:1
				die(err)
			}
//line cmd/xgoup/main.xgo:203:1
			if *jsonOut {
//line cmd/xgoup/main.xgo:204:1
				b, _ := json.Marshal(items)
//line cmd/xgoup/main.xgo:205:1
				fmt.Println(string(b))
			} else {
				for
//line cmd/xgoup/main.xgo:207:1
				_, m := range items {
//line cmd/xgoup/main.xgo:208:1
					fmt.Printf("%s\t%s\t%s\n", m.Name, m.Kind, m.RootPath)
				}
			}
//line cmd/xgoup/main.xgo:211:1
			os.Exit(0)
//line cmd/xgoup/main.xgo:212:1
		case "remove":
//line cmd/xgoup/main.xgo:213:1
			fs := flag.NewFlagSet("toolchain remove", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:214:1
			purge := fs.Bool("purge", false, "")
//line cmd/xgoup/main.xgo:215:1
			_ = fs.Parse(rest[1:])
//line cmd/xgoup/main.xgo:216:1
			pos := fs.Args()
//line cmd/xgoup/main.xgo:217:1
			if len(pos) < 1 {
//line cmd/xgoup/main.xgo:218:1
				dieUsage("toolchain remove requires <name>")
			}
//line cmd/xgoup/main.xgo:220:1
			name := pos[0]
//line cmd/xgoup/main.xgo:221:1
			p, c, err := toolchain.Init()
//line cmd/xgoup/main.xgo:222:1
			if err != nil {
//line cmd/xgoup/main.xgo:223:1
				die(err)
			}
//line cmd/xgoup/main.xgo:225:1
			_, err = toolchain.Remove(p, c, name, *purge)
//line cmd/xgoup/main.xgo:226:1
			if err != nil {
//line cmd/xgoup/main.xgo:227:1
				die(err)
			}
//line cmd/xgoup/main.xgo:229:1
			fmt.Println("[xgoup] removed toolchain", name)
//line cmd/xgoup/main.xgo:230:1
			os.Exit(0)
//line cmd/xgoup/main.xgo:231:1
		default:
//line cmd/xgoup/main.xgo:232:1
			dieUsage("unknown toolchain subcommand: " + rest[0])
		}
//line cmd/xgoup/main.xgo:234:1
	case "default":
//line cmd/xgoup/main.xgo:235:1
		fs := flag.NewFlagSet("default", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:236:1
		_ = fs.Parse(rest)
//line cmd/xgoup/main.xgo:237:1
		pos := fs.Args()
//line cmd/xgoup/main.xgo:238:1
		if len(pos) < 1 {
//line cmd/xgoup/main.xgo:239:1
			dieUsage("default requires <name>")
		}
//line cmd/xgoup/main.xgo:241:1
		name := pos[0]
//line cmd/xgoup/main.xgo:242:1
		p, c, err := toolchain.Init()
//line cmd/xgoup/main.xgo:243:1
		if err != nil {
//line cmd/xgoup/main.xgo:244:1
			die(err)
		}
//line cmd/xgoup/main.xgo:246:1
		_, err = toolchain.SetDefault(p, c, name)
//line cmd/xgoup/main.xgo:247:1
		if err != nil {
//line cmd/xgoup/main.xgo:248:1
			die(err)
		}
//line cmd/xgoup/main.xgo:250:1
		m, err := meta.Load(p.Metadata, name)
//line cmd/xgoup/main.xgo:251:1
		if err != nil {
//line cmd/xgoup/main.xgo:252:1
			die(err)
		}
//line cmd/xgoup/main.xgo:254:1
		root := m.XgoRootValue
//line cmd/xgoup/main.xgo:255:1
		if root == "" {
//line cmd/xgoup/main.xgo:256:1
			root = m.RootPath
		}
//line cmd/xgoup/main.xgo:258:1
		fmt.Println("[xgoup] default toolchain set to", name)
//line cmd/xgoup/main.xgo:259:1
		fmt.Println("[xgoup] XGOROOT for this toolchain:", root)
//line cmd/xgoup/main.xgo:260:1
		if
//line cmd/xgoup/main.xgo:260:1
		err := userenv.PersistDefaultToolchainEnv(root); err != nil {
//line cmd/xgoup/main.xgo:261:1
			die(err)
		}
//line cmd/xgoup/main.xgo:263:1
		fmt.Println("[xgoup] persisted user env (open a new terminal; on Unix you can source ~/.xgoup/env.sh in this shell)")
//line cmd/xgoup/main.xgo:264:1
		os.Exit(0)
//line cmd/xgoup/main.xgo:265:1
	case "run":
//line cmd/xgoup/main.xgo:266:1
		fs := flag.NewFlagSet("run", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:267:1
		tcn := fs.String("toolchain", "", "")
//line cmd/xgoup/main.xgo:268:1
		_ = fs.Parse(rest)
//line cmd/xgoup/main.xgo:269:1
		xgoArgs := fs.Args()
//line cmd/xgoup/main.xgo:270:1
		if len(xgoArgs) == 0 {
//line cmd/xgoup/main.xgo:271:1
			dieUsage("run requires <xgo args...>")
		}
//line cmd/xgoup/main.xgo:273:1
		p, c, err := toolchain.Init()
//line cmd/xgoup/main.xgo:274:1
		if err != nil {
//line cmd/xgoup/main.xgo:275:1
			die(err)
		}
//line cmd/xgoup/main.xgo:277:1
		cwd, _ := os.Getwd()
//line cmd/xgoup/main.xgo:278:1
		r, err := resolve.ResolveToolchain(p, c, *tcn, cwd)
//line cmd/xgoup/main.xgo:279:1
		if err != nil {
//line cmd/xgoup/main.xgo:280:1
			die(err)
		}
//line cmd/xgoup/main.xgo:283:1
		cmd := execCommand(r.XgoExe, xgoArgs...) 
//line cmd/xgoup/main.xgo:284:1
		cmd.Env = append(os.Environ(), "XGOROOT="+r.XgoRoot, "PATH="+r.BinDir+string(os.PathListSeparator)+os.Getenv("PATH"))
//line cmd/xgoup/main.xgo:288:1
		cmd.Stdout = os.Stdout
//line cmd/xgoup/main.xgo:289:1
		cmd.Stderr = os.Stderr
//line cmd/xgoup/main.xgo:290:1
		cmd.Stdin = os.Stdin
//line cmd/xgoup/main.xgo:291:1
		if
//line cmd/xgoup/main.xgo:291:1
		err := cmd.Run(); err != nil {
//line cmd/xgoup/main.xgo:292:1
			die(err)
		}
//line cmd/xgoup/main.xgo:294:1
		os.Exit(0)
//line cmd/xgoup/main.xgo:295:1
	case "which":
//line cmd/xgoup/main.xgo:296:1
		fs := flag.NewFlagSet("which", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:297:1
		tcn := fs.String("toolchain", "", "")
//line cmd/xgoup/main.xgo:298:1
		_ = fs.Parse(rest)
//line cmd/xgoup/main.xgo:299:1
		p, c, err := toolchain.Init()
//line cmd/xgoup/main.xgo:300:1
		if err != nil {
//line cmd/xgoup/main.xgo:301:1
			die(err)
		}
//line cmd/xgoup/main.xgo:303:1
		cwd, _ := os.Getwd()
//line cmd/xgoup/main.xgo:304:1
		r, err := resolve.ResolveToolchain(p, c, *tcn, cwd)
//line cmd/xgoup/main.xgo:305:1
		if err != nil {
//line cmd/xgoup/main.xgo:306:1
			die(err)
		}
//line cmd/xgoup/main.xgo:308:1
		fmt.Println(r.XgoExe)
//line cmd/xgoup/main.xgo:309:1
		os.Exit(0)
//line cmd/xgoup/main.xgo:310:1
	case "env":
//line cmd/xgoup/main.xgo:311:1
		fs := flag.NewFlagSet("env", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:312:1
		tcn := fs.String("toolchain", "", "")
//line cmd/xgoup/main.xgo:313:1
		shell := fs.String("shell", "powershell", "")
//line cmd/xgoup/main.xgo:314:1
		_ = fs.Parse(rest)
//line cmd/xgoup/main.xgo:315:1
		p, c, err := toolchain.Init()
//line cmd/xgoup/main.xgo:316:1
		if err != nil {
//line cmd/xgoup/main.xgo:317:1
			die(err)
		}
//line cmd/xgoup/main.xgo:319:1
		cwd, _ := os.Getwd()
//line cmd/xgoup/main.xgo:320:1
		r, err := resolve.ResolveToolchain(p, c, *tcn, cwd)
//line cmd/xgoup/main.xgo:321:1
		if err != nil {
//line cmd/xgoup/main.xgo:322:1
			die(err)
		}
//line cmd/xgoup/main.xgo:324:1
		switch *shell {
//line cmd/xgoup/main.xgo:325:1
		case "powershell":
//line cmd/xgoup/main.xgo:326:1
			fmt.Printf("$env:XGOROOT = \"%s\"\n", r.XgoRoot)
//line cmd/xgoup/main.xgo:327:1
			fmt.Printf("$env:PATH = \"%s%c\" + $env:PATH\n", r.BinDir, os.PathListSeparator)
//line cmd/xgoup/main.xgo:328:1
		case "sh", "zsh":
//line cmd/xgoup/main.xgo:329:1
			fmt.Printf("export XGOROOT=\"%s\"\n", r.XgoRoot)
//line cmd/xgoup/main.xgo:330:1
			fmt.Printf("export PATH=\"%s:%s\"\n", r.BinDir, "$PATH")
//line cmd/xgoup/main.xgo:331:1
		default:
//line cmd/xgoup/main.xgo:332:1
			dieUsage("unsupported shell: " + *shell)
		}
//line cmd/xgoup/main.xgo:334:1
		os.Exit(0)
//line cmd/xgoup/main.xgo:335:1
	case "doctor":
//line cmd/xgoup/main.xgo:336:1
		p, c, err := toolchain.Init()
//line cmd/xgoup/main.xgo:337:1
		if err != nil {
//line cmd/xgoup/main.xgo:338:1
			die(err)
		}
//line cmd/xgoup/main.xgo:340:1
		if
//line cmd/xgoup/main.xgo:340:1
		err := toolchain.Doctor(p, c); err != nil {
//line cmd/xgoup/main.xgo:341:1
			die(err)
		}
//line cmd/xgoup/main.xgo:343:1
		fmt.Println("[xgoup] doctor: ok")
//line cmd/xgoup/main.xgo:344:1
		os.Exit(0)
//line cmd/xgoup/main.xgo:345:1
	case "doc":
//line cmd/xgoup/main.xgo:346:1
		fs := flag.NewFlagSet("doc", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:347:1
		noBrowser := fs.Bool("no-browser", false, "")
//line cmd/xgoup/main.xgo:348:1
		repo := fs.String("repo", getenv("XGO_DOC_REPO", xgodoc.DefaultRepo), "")
//line cmd/xgoup/main.xgo:349:1
		_ = fs.Parse(rest)
//line cmd/xgoup/main.xgo:350:1
		urls := xgodoc.URLs(*repo)
//line cmd/xgoup/main.xgo:351:1
		if *noBrowser {
			for
//line cmd/xgoup/main.xgo:352:1
			_, u := range urls {
//line cmd/xgoup/main.xgo:353:1
				fmt.Println(u)
			}
//line cmd/xgoup/main.xgo:355:1
			os.Exit(0)
		}
//line cmd/xgoup/main.xgo:357:1
		if
//line cmd/xgoup/main.xgo:357:1
		err := xgodoc.OpenBrowser(urls); err != nil {
//line cmd/xgoup/main.xgo:358:1
			die(err)
		}
//line cmd/xgoup/main.xgo:360:1
		fmt.Println("[xgoup] opened XGo spec, classfile docs, reference, demo, and tutorial")
//line cmd/xgoup/main.xgo:361:1
		os.Exit(0)
//line cmd/xgoup/main.xgo:362:1
	case "self":
//line cmd/xgoup/main.xgo:363:1
		if len(rest) == 0 {
//line cmd/xgoup/main.xgo:364:1
			dieUsage("missing self subcommand")
		}
//line cmd/xgoup/main.xgo:366:1
		switch rest[0] {
//line cmd/xgoup/main.xgo:367:1
		case "install":
//line cmd/xgoup/main.xgo:368:1
			fs := flag.NewFlagSet("self install", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:369:1
			repo := fs.String("repo", getenv("XGOUP_GITHUB_REPO", "fanfeilong/xgoup"), "")
//line cmd/xgoup/main.xgo:370:1
			version := fs.String("version", "latest", "")
//line cmd/xgoup/main.xgo:371:1
			modifyPath := fs.Bool("modify-path", true, "")
//line cmd/xgoup/main.xgo:372:1
			zipPath := fs.String("zip", "", "")
//line cmd/xgoup/main.xgo:373:1
			_ = fs.Parse(rest[1:])
//line cmd/xgoup/main.xgo:374:1
			err := bootstrap.Install(bootstrap.Options{Repo: *repo, Version: *version, ZipPath: *zipPath, ModifyPath: *modifyPath, Logf: func(format string, args ...interface{}) {
//line cmd/xgoup/main.xgo:380:1
				fmt.Printf(format+"\n", args...)
			}})
//line cmd/xgoup/main.xgo:383:1
			if err != nil {
//line cmd/xgoup/main.xgo:384:1
				die(err)
			}
//line cmd/xgoup/main.xgo:386:1
			os.Exit(0)
//line cmd/xgoup/main.xgo:387:1
		case "update":
//line cmd/xgoup/main.xgo:388:1
			fs := flag.NewFlagSet("self update", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:389:1
			repo := fs.String("repo", os.Getenv("XGOUP_GITHUB_REPO"), "")
//line cmd/xgoup/main.xgo:390:1
			_ = fs.Parse(rest[1:])
//line cmd/xgoup/main.xgo:391:1
			path, err := selfupdate.Update(selfupdate.Options{Repo: *repo})
//line cmd/xgoup/main.xgo:392:1
			if err != nil {
//line cmd/xgoup/main.xgo:393:1
				die(err)
			}
//line cmd/xgoup/main.xgo:395:1
			fmt.Println("[xgoup] updated:", path)
//line cmd/xgoup/main.xgo:396:1
			os.Exit(0)
//line cmd/xgoup/main.xgo:397:1
		case "uninstall":
//line cmd/xgoup/main.xgo:398:1
			fs := flag.NewFlagSet("self uninstall", flag.ContinueOnError)
//line cmd/xgoup/main.xgo:399:1
			force := fs.Bool("force", false, "")
//line cmd/xgoup/main.xgo:400:1
			_ = fs.Parse(rest[1:])
//line cmd/xgoup/main.xgo:401:1
			p, err := home.Resolve()
//line cmd/xgoup/main.xgo:402:1
			if err != nil {
//line cmd/xgoup/main.xgo:403:1
				die(err)
			}
//line cmd/xgoup/main.xgo:405:1
			if
//line cmd/xgoup/main.xgo:405:1
			err := selfupdate.Uninstall(p.Home, *force); err != nil {
//line cmd/xgoup/main.xgo:406:1
				die(err)
			}
//line cmd/xgoup/main.xgo:408:1
			fmt.Println("[xgoup] uninstalled home:", p.Home)
//line cmd/xgoup/main.xgo:409:1
			os.Exit(0)
//line cmd/xgoup/main.xgo:410:1
		default:
//line cmd/xgoup/main.xgo:411:1
			dieUsage("unknown self subcommand: " + rest[0])
		}
//line cmd/xgoup/main.xgo:413:1
	default:
//line cmd/xgoup/main.xgo:414:1
		dieUsage("unknown command: " + cmd)
	}
}
