// Code generated by xgo (XGo); DO NOT EDIT.

package meta

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const _ = true

type ToolchainMeta struct {
	Name         string
	Kind         string
	RootPath     string
	XgoBin       string
	XgoRootValue string
	Managed      string
	Repo         string
	Ref          string
	Commit       string
	Version      string
}
//line internal/meta/meta.xgo:25:1
func FilePath(metaDir string, name string) string {
//line internal/meta/meta.xgo:26:1
	return filepath.Join(metaDir, name+".env")
}
//line internal/meta/meta.xgo:29:1
func Names(metaDir string) ([]string, error) {
//line internal/meta/meta.xgo:30:1
	ents, err := os.ReadDir(metaDir)
//line internal/meta/meta.xgo:31:1
	if err != nil {
//line internal/meta/meta.xgo:32:1
		if os.IsNotExist(err) {
//line internal/meta/meta.xgo:33:1
			return []string{}, nil
		}
//line internal/meta/meta.xgo:35:1
		return nil, err
	}
//line internal/meta/meta.xgo:37:1
	var out []string
	for
//line internal/meta/meta.xgo:38:1
	_, e := range ents {
//line internal/meta/meta.xgo:39:1
		if e.IsDir() {
//line internal/meta/meta.xgo:40:1
			continue
		}
//line internal/meta/meta.xgo:42:1
		n := e.Name()
//line internal/meta/meta.xgo:43:1
		if strings.HasSuffix(n, ".env") {
//line internal/meta/meta.xgo:44:1
			out = append(out, strings.TrimSuffix(n, ".env"))
		}
	}
//line internal/meta/meta.xgo:47:1
	sort.Strings(out)
//line internal/meta/meta.xgo:48:1
	return out, nil
}
//line internal/meta/meta.xgo:51:1
func Load(metaDir string, name string) (ToolchainMeta, error) {
//line internal/meta/meta.xgo:52:1
	p := FilePath(metaDir, name)
//line internal/meta/meta.xgo:53:1
	f, err := os.Open(p)
//line internal/meta/meta.xgo:54:1
	if err != nil {
//line internal/meta/meta.xgo:55:1
		return ToolchainMeta{}, err
	}
//line internal/meta/meta.xgo:57:1
	defer f.Close()
//line internal/meta/meta.xgo:59:1
	m := ToolchainMeta{Name: name}
//line internal/meta/meta.xgo:60:1
	sc := bufio.NewScanner(f)
//line internal/meta/meta.xgo:61:1
	for sc.Scan() {
//line internal/meta/meta.xgo:62:1
		line := strings.TrimSpace(sc.Text())
//line internal/meta/meta.xgo:63:1
		if line == "" || strings.HasPrefix(line, "#") {
//line internal/meta/meta.xgo:64:1
			continue
		}
//line internal/meta/meta.xgo:66:1
		k, v, ok := strings.Cut(line, "=")
//line internal/meta/meta.xgo:67:1
		if !ok {
//line internal/meta/meta.xgo:68:1
			continue
		}
//line internal/meta/meta.xgo:70:1
		k = strings.TrimSpace(k)
//line internal/meta/meta.xgo:71:1
		v = strings.TrimSpace(v)
//line internal/meta/meta.xgo:154:1
		v = parseSingleQuoted(v)
//line internal/meta/meta.xgo:73:1
		switch k {
//line internal/meta/meta.xgo:74:1
		case "NAME":
//line internal/meta/meta.xgo:75:1
			m.Name = v
//line internal/meta/meta.xgo:76:1
		case "KIND":
//line internal/meta/meta.xgo:77:1
			m.Kind = v
//line internal/meta/meta.xgo:78:1
		case "ROOT_PATH":
//line internal/meta/meta.xgo:79:1
			m.RootPath = v
//line internal/meta/meta.xgo:80:1
		case "XGO_BIN":
//line internal/meta/meta.xgo:81:1
			m.XgoBin = v
//line internal/meta/meta.xgo:82:1
		case "XGOROOT_VALUE":
//line internal/meta/meta.xgo:83:1
			m.XgoRootValue = v
//line internal/meta/meta.xgo:84:1
		case "MANAGED":
//line internal/meta/meta.xgo:85:1
			m.Managed = v
//line internal/meta/meta.xgo:86:1
		case "REPO":
//line internal/meta/meta.xgo:87:1
			m.Repo = v
//line internal/meta/meta.xgo:88:1
		case "REF":
//line internal/meta/meta.xgo:89:1
			m.Ref = v
//line internal/meta/meta.xgo:90:1
		case "COMMIT":
//line internal/meta/meta.xgo:91:1
			m.Commit = v
//line internal/meta/meta.xgo:92:1
		case "VERSION":
//line internal/meta/meta.xgo:93:1
			m.Version = v
		}
	}
//line internal/meta/meta.xgo:96:1
	if
//line internal/meta/meta.xgo:96:1
	err := sc.Err(); err != nil {
//line internal/meta/meta.xgo:97:1
		return ToolchainMeta{}, err
	}
//line internal/meta/meta.xgo:99:1
	if m.Name == "" {
//line internal/meta/meta.xgo:100:1
		m.Name = name
	}
//line internal/meta/meta.xgo:102:1
	return m, nil
}
//line internal/meta/meta.xgo:147:1
func parseSingleQuoted(v string) string {
//line internal/meta/meta.xgo:149:1
	if len(v) >= 2 && strings.HasPrefix(v, "'") && strings.HasSuffix(v, "'") {
//line internal/meta/meta.xgo:150:1
		v = v[1 : len(v)-1]
	}
//line internal/meta/meta.xgo:153:1
	v = strings.ReplaceAll(v, `'\''`, `'`)
//line internal/meta/meta.xgo:154:1
	return v
}
//line internal/meta/meta.xgo:105:1
func Save(metaDir string, name string, m ToolchainMeta) error {
//line internal/meta/meta.xgo:106:1
	p := FilePath(metaDir, name)
//line internal/meta/meta.xgo:107:1
	if
//line internal/meta/meta.xgo:107:1
	err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
//line internal/meta/meta.xgo:108:1
		return err
	}
//line internal/meta/meta.xgo:110:1
	f, err := os.Create(p)
//line internal/meta/meta.xgo:111:1
	if err != nil {
//line internal/meta/meta.xgo:112:1
		return err
	}
//line internal/meta/meta.xgo:114:1
	defer f.Close()
//line internal/meta/meta.xgo:117:1
	lines := []struct {
		k string
		v string
	}{struct {
		k string
		v string
	}{"NAME", or(m.Name, name)}, struct {
		k string
		v string
	}{"KIND", m.Kind}, struct {
		k string
		v string
	}{"ROOT_PATH", m.RootPath}, struct {
		k string
		v string
	}{"XGO_BIN", m.XgoBin}, struct {
		k string
		v string
	}{"XGOROOT_VALUE", m.XgoRootValue}, struct {
		k string
		v string
	}{"MANAGED", m.Managed}, struct {
		k string
		v string
	}{"REPO", m.Repo}, struct {
		k string
		v string
	}{"REF", m.Ref}, struct {
		k string
		v string
	}{"COMMIT", m.Commit}, struct {
		k string
		v string
	}{"VERSION", m.Version}}
	for
//line internal/meta/meta.xgo:132:1
	_, kv := range lines {
//line internal/meta/meta.xgo:133:1
		if
//line internal/meta/meta.xgo:133:1
		_, err := fmt.Fprintf(f, "%s='%s'\n", kv.k, escapeSingleQuotes(kv.v)); err != nil {
//line internal/meta/meta.xgo:134:1
			return err
		}
	}
//line internal/meta/meta.xgo:137:1
	return nil
}
//line internal/meta/meta.xgo:140:1
func or(v string, def string) string {
//line internal/meta/meta.xgo:141:1
	if v != "" {
//line internal/meta/meta.xgo:142:1
		return v
	}
//line internal/meta/meta.xgo:144:1
	return def
}
//line internal/meta/meta.xgo:157:1
func escapeSingleQuotes(s string) string {
//line internal/meta/meta.xgo:159:1
	return strings.ReplaceAll(s, `'`, `'\''`)
}
