// Code generated by xgo (XGo); DO NOT EDIT.

package xgodoc

import (
	"fmt"
	"os/exec"
	"runtime"
)

const _ = true
const DefaultRepo = "goplus/xgo"
//line internal/xgodoc/xgodoc.xgo:13:1
// URLs returns stable links: language spec, classfile overview & spec, full docs index,
// demo sources on GitHub, and the public tutorial site (annotated examples).
func URLs(repo string) []string {
//line internal/xgodoc/xgodoc.xgo:16:1
	if repo == "" {
//line internal/xgodoc/xgodoc.xgo:17:1
		repo = DefaultRepo
	}
//line internal/xgodoc/xgodoc.xgo:19:1
	base := "https://github.com/" + repo
//line internal/xgodoc/xgodoc.xgo:20:1
	return []string{base + "/blob/main/doc/spec.md", base + "/blob/main/doc/classfile.md", base + "/blob/main/doc/classfile-spec.md", base + "/blob/main/doc/docs.md", base + "/tree/main/demo", "https://tutorial.xgo.dev/"}
}
//line internal/xgodoc/xgodoc.xgo:30:1
// OpenBrowser opens each URL with the OS default handler (usually a browser).
func OpenBrowser(urls []string) error {
	for
//line internal/xgodoc/xgodoc.xgo:32:1
	_, u := range urls {
//line internal/xgodoc/xgodoc.xgo:33:1
		if
//line internal/xgodoc/xgodoc.xgo:33:1
		err := openOne(u); err != nil {
//line internal/xgodoc/xgodoc.xgo:34:1
			return fmt.Errorf("open %q: %w", u, err)
		}
	}
//line internal/xgodoc/xgodoc.xgo:37:1
	return nil
}
//line internal/xgodoc/xgodoc.xgo:40:1
func openOne(url string) error {
//line internal/xgodoc/xgodoc.xgo:41:1
	switch runtime.GOOS {
//line internal/xgodoc/xgodoc.xgo:42:1
	case "darwin":
//line internal/xgodoc/xgodoc.xgo:43:1
		return exec.Command("open", url).Run()
//line internal/xgodoc/xgodoc.xgo:44:1
	case "windows":
//line internal/xgodoc/xgodoc.xgo:46:1
		return exec.Command("rundll32", "url.dll,FileProtocolHandler", url).Run()
//line internal/xgodoc/xgodoc.xgo:47:1
	default:
//line internal/xgodoc/xgodoc.xgo:48:1
		return exec.Command("xdg-open", url).Run()
	}
}
