// Code generated by xgo (XGo); DO NOT EDIT.

package toolchain

import (
	"archive/zip"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/fanfeilong/xgoup/internal/config"
	"github.com/fanfeilong/xgoup/internal/home"
	"github.com/fanfeilong/xgoup/internal/meta"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"time"
)

const _ = true
const DefaultSourceRepo = "https://github.com/goplus/xgo.git"

type InstallOptions struct {
	Method string
	Repo   string
	Ref    string
	Path   string
	Force  bool
}
//line internal/toolchain/toolchain.xgo:33:1
func Init() (home.Paths, config.Config, error) {
//line internal/toolchain/toolchain.xgo:34:1
	p, err := home.Resolve()
//line internal/toolchain/toolchain.xgo:35:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:36:1
		return home.Paths{}, config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:38:1
	if
//line internal/toolchain/toolchain.xgo:38:1
	err := home.EnsureDirs(p); err != nil {
//line internal/toolchain/toolchain.xgo:39:1
		return home.Paths{}, config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:42:1
	cfg, err := readOrCreateConfig(p)
//line internal/toolchain/toolchain.xgo:43:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:44:1
		return home.Paths{}, config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:46:1
	return p, cfg, nil
}
//line internal/toolchain/toolchain.xgo:49:1
func readOrCreateConfig(p home.Paths) (config.Config, error) {
//line internal/toolchain/toolchain.xgo:50:1
	_, err := os.Stat(p.Config)
//line internal/toolchain/toolchain.xgo:51:1
	if err == nil {
//line internal/toolchain/toolchain.xgo:52:1
		c, err := config.Load(p.Config)
//line internal/toolchain/toolchain.xgo:53:1
		if err != nil {
//line internal/toolchain/toolchain.xgo:54:1
			return config.Config{}, err
		}
//line internal/toolchain/toolchain.xgo:56:1
		if
//line internal/toolchain/toolchain.xgo:56:1
		err := config.Validate(c); err != nil {
//line internal/toolchain/toolchain.xgo:57:1
			return config.Config{}, err
		}
//line internal/toolchain/toolchain.xgo:59:1
		return c, nil
	}
//line internal/toolchain/toolchain.xgo:61:1
	if !os.IsNotExist(err) {
//line internal/toolchain/toolchain.xgo:62:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:65:1
	c := config.Default(DefaultSourceRepo)
//line internal/toolchain/toolchain.xgo:68:1
	names, _ := meta.Names(p.Metadata)
	for
//line internal/toolchain/toolchain.xgo:69:1
	_, n := range names {
//line internal/toolchain/toolchain.xgo:70:1
		m, err := meta.Load(p.Metadata, n)
//line internal/toolchain/toolchain.xgo:71:1
		if err != nil {
//line internal/toolchain/toolchain.xgo:72:1
			continue
		}
//line internal/toolchain/toolchain.xgo:74:1
		managed := strings.EqualFold(m.Managed, "true")
//line internal/toolchain/toolchain.xgo:75:1
		c.Toolchains[n] = config.Toolchain{Kind: m.Kind, Path: m.RootPath, Managed: managed, Version: m.Version, Repo: m.Repo, Ref: m.Ref, Commit: m.Commit}
	}
//line internal/toolchain/toolchain.xgo:85:1
	if c.DefaultToolchain == "" && len(c.Toolchains) > 0 {
//line internal/toolchain/toolchain.xgo:86:1
		// Pick first stable ordering.
		var keys []string
		for
//line internal/toolchain/toolchain.xgo:88:1
		k := range c.Toolchains {
//line internal/toolchain/toolchain.xgo:89:1
			keys = append(keys, k)
		}
//line internal/toolchain/toolchain.xgo:91:1
		sort.Strings(keys)
//line internal/toolchain/toolchain.xgo:92:1
		c.DefaultToolchain = keys[0]
	}
//line internal/toolchain/toolchain.xgo:94:1
	if
//line internal/toolchain/toolchain.xgo:94:1
	err := config.Save(p.Config, c); err != nil {
//line internal/toolchain/toolchain.xgo:95:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:97:1
	return c, nil
}
//line internal/toolchain/toolchain.xgo:100:1
func SaveConfig(p home.Paths, c config.Config) error {
//line internal/toolchain/toolchain.xgo:101:1
	if
//line internal/toolchain/toolchain.xgo:101:1
	err := config.Validate(c); err != nil {
//line internal/toolchain/toolchain.xgo:102:1
		return err
	}
//line internal/toolchain/toolchain.xgo:104:1
	return config.Save(p.Config, c)
}
//line internal/toolchain/toolchain.xgo:107:1
func SetDefault(p home.Paths, c config.Config, name string) (config.Config, error) {
//line internal/toolchain/toolchain.xgo:108:1
	if
//line internal/toolchain/toolchain.xgo:108:1
	_, ok := c.Toolchains[name]; !ok {
//line internal/toolchain/toolchain.xgo:109:1
		return config.Config{}, fmt.Errorf("toolchain not found: %s", name)
	}
//line internal/toolchain/toolchain.xgo:111:1
	c.DefaultToolchain = name
//line internal/toolchain/toolchain.xgo:112:1
	if
//line internal/toolchain/toolchain.xgo:112:1
	err := SaveConfig(p, c); err != nil {
//line internal/toolchain/toolchain.xgo:113:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:115:1
	return c, nil
}
//line internal/toolchain/toolchain.xgo:118:1
func List(p home.Paths, c config.Config) ([]meta.ToolchainMeta, error) {
//line internal/toolchain/toolchain.xgo:119:1
	names, err := meta.Names(p.Metadata)
//line internal/toolchain/toolchain.xgo:120:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:121:1
		return nil, err
	}
//line internal/toolchain/toolchain.xgo:123:1
	out := make([]meta.ToolchainMeta, 0, len(names))
	for
//line internal/toolchain/toolchain.xgo:124:1
	_, n := range names {
//line internal/toolchain/toolchain.xgo:125:1
		m, err := meta.Load(p.Metadata, n)
//line internal/toolchain/toolchain.xgo:126:1
		if err != nil {
//line internal/toolchain/toolchain.xgo:127:1
			return nil, err
		}
//line internal/toolchain/toolchain.xgo:129:1
		out = append(out, m)
	}
//line internal/toolchain/toolchain.xgo:131:1
	return out, nil
}
//line internal/toolchain/toolchain.xgo:134:1
func Remove(p home.Paths, c config.Config, name string, purge bool) (config.Config, error) {
//line internal/toolchain/toolchain.xgo:135:1
	m, err := meta.Load(p.Metadata, name)
//line internal/toolchain/toolchain.xgo:136:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:137:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:139:1
	if purge && strings.EqualFold(m.Managed, "true") && m.RootPath != "" {
//line internal/toolchain/toolchain.xgo:140:1
		_ = os.RemoveAll(m.RootPath)
	}
//line internal/toolchain/toolchain.xgo:142:1
	_ = os.Remove(meta.FilePath(p.Metadata, name))
//line internal/toolchain/toolchain.xgo:144:1
	delete(c.Toolchains, name)
//line internal/toolchain/toolchain.xgo:145:1
	if c.DefaultToolchain == name {
//line internal/toolchain/toolchain.xgo:146:1
		c.DefaultToolchain = ""
	}
//line internal/toolchain/toolchain.xgo:148:1
	if c.DefaultToolchain == "" && len(c.Toolchains) > 0 {
//line internal/toolchain/toolchain.xgo:149:1
		var keys []string
		for
//line internal/toolchain/toolchain.xgo:150:1
		k := range c.Toolchains {
//line internal/toolchain/toolchain.xgo:151:1
			keys = append(keys, k)
		}
//line internal/toolchain/toolchain.xgo:153:1
		sort.Strings(keys)
//line internal/toolchain/toolchain.xgo:154:1
		c.DefaultToolchain = keys[0]
	}
//line internal/toolchain/toolchain.xgo:156:1
	if
//line internal/toolchain/toolchain.xgo:156:1
	err := SaveConfig(p, c); err != nil {
//line internal/toolchain/toolchain.xgo:157:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:159:1
	return c, nil
}
//line internal/toolchain/toolchain.xgo:162:1
func Install(p home.Paths, c config.Config, name string, opt InstallOptions) (config.Config, error) {
//line internal/toolchain/toolchain.xgo:163:1
	if name == "" {
//line internal/toolchain/toolchain.xgo:164:1
		return config.Config{}, errors.New("missing toolchain name")
	}
//line internal/toolchain/toolchain.xgo:166:1
	if opt.Method == "" {
//line internal/toolchain/toolchain.xgo:167:1
		opt.Method = "standard"
	}
//line internal/toolchain/toolchain.xgo:169:1
	switch opt.Method {
//line internal/toolchain/toolchain.xgo:170:1
	case "standard":
//line internal/toolchain/toolchain.xgo:322:1
		return installStandard(p, c, name, opt)
//line internal/toolchain/toolchain.xgo:172:1
	case "linked":
//line internal/toolchain/toolchain.xgo:261:1
		return installLinked(p, c, name, opt)
//line internal/toolchain/toolchain.xgo:174:1
	case "source":
//line internal/toolchain/toolchain.xgo:392:1
		return installSource(p, c, name, opt)
//line internal/toolchain/toolchain.xgo:176:1
	default:
//line internal/toolchain/toolchain.xgo:177:1
		return config.Config{}, fmt.Errorf("unknown method: %s", opt.Method)
	}
}
//line internal/toolchain/toolchain.xgo:264:1
func installStandard(p home.Paths, c config.Config, name string, opt InstallOptions) (config.Config, error) {
//line internal/toolchain/toolchain.xgo:265:1
	if
//line internal/toolchain/toolchain.xgo:265:1
	_, err := os.Stat(meta.FilePath(p.Metadata, name)); err == nil && !opt.Force {
//line internal/toolchain/toolchain.xgo:266:1
		return config.Config{}, fmt.Errorf("toolchain already exists: %s (use --force)", name)
	}
//line internal/toolchain/toolchain.xgo:269:1
	arch, err := windowsArch()
//line internal/toolchain/toolchain.xgo:270:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:271:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:274:1
	tag, asset, err := latestXgoWindowsAsset(arch)
//line internal/toolchain/toolchain.xgo:275:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:276:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:278:1
	url := fmt.Sprintf("https://github.com/goplus/xgo/releases/download/%s/%s", tag, asset)
//line internal/toolchain/toolchain.xgo:280:1
	tmpZip := filepath.Join(os.TempDir(), fmt.Sprintf("xgo-%d.zip", time.Now().UnixNano()))
//line internal/toolchain/toolchain.xgo:281:1
	defer os.Remove(tmpZip)
//line internal/toolchain/toolchain.xgo:282:1
	if
//line internal/toolchain/toolchain.xgo:282:1
	err := httpGetToFile(url, tmpZip); err != nil {
//line internal/toolchain/toolchain.xgo:283:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:286:1
	target := filepath.Join(p.Toolchains, name)
//line internal/toolchain/toolchain.xgo:287:1
	if opt.Force {
//line internal/toolchain/toolchain.xgo:288:1
		_ = os.RemoveAll(target)
	}
//line internal/toolchain/toolchain.xgo:290:1
	if
//line internal/toolchain/toolchain.xgo:290:1
	err := unzipAll(tmpZip, target); err != nil {
//line internal/toolchain/toolchain.xgo:291:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:294:1
	xgoExe, xgoroot, err := findXgoAndRoot(target)
//line internal/toolchain/toolchain.xgo:295:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:296:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:299:1
	m := meta.ToolchainMeta{Name: name, Kind: "standard", RootPath: xgoroot, XgoBin: xgoExe, XgoRootValue: xgoroot, Managed: "true", Version: detectVersionFromXgo(xgoExe, xgoroot)}
//line internal/toolchain/toolchain.xgo:308:1
	if m.Version == "" {
//line internal/toolchain/toolchain.xgo:309:1
		m.Version = tag
	}
//line internal/toolchain/toolchain.xgo:312:1
	if
//line internal/toolchain/toolchain.xgo:312:1
	err := meta.Save(p.Metadata, name, m); err != nil {
//line internal/toolchain/toolchain.xgo:313:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:315:1
	c.Toolchains[name] = config.Toolchain{Kind: "standard", Path: xgoroot, Managed: true, Version: m.Version}
//line internal/toolchain/toolchain.xgo:316:1
	if c.DefaultToolchain == "" {
//line internal/toolchain/toolchain.xgo:317:1
		c.DefaultToolchain = name
	}
//line internal/toolchain/toolchain.xgo:319:1
	if
//line internal/toolchain/toolchain.xgo:319:1
	err := SaveConfig(p, c); err != nil {
//line internal/toolchain/toolchain.xgo:320:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:322:1
	return c, nil
}
//line internal/toolchain/toolchain.xgo:440:1
func windowsArch() (string, error) {
//line internal/toolchain/toolchain.xgo:441:1
	switch runtime.GOARCH {
//line internal/toolchain/toolchain.xgo:442:1
	case "amd64":
//line internal/toolchain/toolchain.xgo:443:1
		return "amd64", nil
//line internal/toolchain/toolchain.xgo:444:1
	case "arm64":
//line internal/toolchain/toolchain.xgo:445:1
		return "arm64", nil
//line internal/toolchain/toolchain.xgo:446:1
	default:
//line internal/toolchain/toolchain.xgo:447:1
		return "", fmt.Errorf("unsupported arch: %s", runtime.GOARCH)
	}
}
//line internal/toolchain/toolchain.xgo:451:1
func latestXgoWindowsAsset(arch string) (tag string, asset string, err error) {
//line internal/toolchain/toolchain.xgo:452:1
	req, err := http.NewRequest("GET", "https://api.github.com/repos/goplus/xgo/releases/latest", nil)
//line internal/toolchain/toolchain.xgo:453:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:454:1
		return "", "", err
	}
//line internal/toolchain/toolchain.xgo:456:1
	req.Header.Set("Accept", "application/vnd.github+json")
//line internal/toolchain/toolchain.xgo:457:1
	req.Header.Set("User-Agent", "xgoup")
//line internal/toolchain/toolchain.xgo:458:1
	if
//line internal/toolchain/toolchain.xgo:458:1
	tok := os.Getenv("GITHUB_TOKEN"); tok != "" {
//line internal/toolchain/toolchain.xgo:459:1
		req.Header.Set("Authorization", "Bearer "+tok)
	}
//line internal/toolchain/toolchain.xgo:461:1
	client := &http.Client{Timeout: 30 * time.Second}
//line internal/toolchain/toolchain.xgo:462:1
	resp, err := client.Do(req)
//line internal/toolchain/toolchain.xgo:463:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:464:1
		return "", "", err
	}
//line internal/toolchain/toolchain.xgo:466:1
	defer resp.Body.Close()
//line internal/toolchain/toolchain.xgo:467:1
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
//line internal/toolchain/toolchain.xgo:468:1
		b, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
//line internal/toolchain/toolchain.xgo:469:1
		return "", "", fmt.Errorf("GET %s: status=%s body=%q", req.URL.String(), resp.Status, string(b))
	}
//line internal/toolchain/toolchain.xgo:471:1
	b, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
//line internal/toolchain/toolchain.xgo:472:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:473:1
		return "", "", err
	}
//line internal/toolchain/toolchain.xgo:475:1
	var v struct {
		Tag string `json:"tag_name"`
	}
//line internal/toolchain/toolchain.xgo:478:1
	if
//line internal/toolchain/toolchain.xgo:478:1
	err := json.Unmarshal(b, &v); err != nil {
//line internal/toolchain/toolchain.xgo:479:1
		return "", "", err
	}
//line internal/toolchain/toolchain.xgo:481:1
	if v.Tag == "" {
//line internal/toolchain/toolchain.xgo:482:1
		return "", "", errors.New("failed to resolve xgo latest release tag")
	}
//line internal/toolchain/toolchain.xgo:484:1
	ver := strings.TrimPrefix(v.Tag, "v")
//line internal/toolchain/toolchain.xgo:485:1
	return v.Tag, fmt.Sprintf("xgo%s.windows-%s.zip", ver, arch), nil
}
//line internal/toolchain/toolchain.xgo:488:1
func httpGetToFile(url string, path string) error {
//line internal/toolchain/toolchain.xgo:489:1
	req, err := http.NewRequest("GET", url, nil)
//line internal/toolchain/toolchain.xgo:490:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:491:1
		return err
	}
//line internal/toolchain/toolchain.xgo:493:1
	req.Header.Set("User-Agent", "xgoup")
//line internal/toolchain/toolchain.xgo:494:1
	req.Header.Set("Accept", "application/octet-stream")
//line internal/toolchain/toolchain.xgo:495:1
	client := &http.Client{Timeout: 120 * time.Second}
//line internal/toolchain/toolchain.xgo:496:1
	resp, err := client.Do(req)
//line internal/toolchain/toolchain.xgo:497:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:498:1
		return err
	}
//line internal/toolchain/toolchain.xgo:500:1
	defer resp.Body.Close()
//line internal/toolchain/toolchain.xgo:501:1
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
//line internal/toolchain/toolchain.xgo:502:1
		b, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
//line internal/toolchain/toolchain.xgo:503:1
		return fmt.Errorf("GET %s: status=%s body=%q", url, resp.Status, string(b))
	}
//line internal/toolchain/toolchain.xgo:505:1
	f, err := os.Create(path)
//line internal/toolchain/toolchain.xgo:506:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:507:1
		return err
	}
//line internal/toolchain/toolchain.xgo:509:1
	defer f.Close()
//line internal/toolchain/toolchain.xgo:510:1
	_, err = io.Copy(f, resp.Body)
//line internal/toolchain/toolchain.xgo:511:1
	return err
}
//line internal/toolchain/toolchain.xgo:514:1
func unzipAll(zipPath string, destDir string) error {
//line internal/toolchain/toolchain.xgo:515:1
	r, err := zip.OpenReader(zipPath)
//line internal/toolchain/toolchain.xgo:516:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:517:1
		return err
	}
//line internal/toolchain/toolchain.xgo:519:1
	defer r.Close()
//line internal/toolchain/toolchain.xgo:520:1
	if
//line internal/toolchain/toolchain.xgo:520:1
	err := os.MkdirAll(destDir, 0o755); err != nil {
//line internal/toolchain/toolchain.xgo:521:1
		return err
	}
	for
//line internal/toolchain/toolchain.xgo:523:1
	_, f := range r.File {
//line internal/toolchain/toolchain.xgo:524:1
		p := filepath.Join(destDir, filepath.FromSlash(f.Name))
//line internal/toolchain/toolchain.xgo:525:1
		if f.FileInfo().IsDir() {
//line internal/toolchain/toolchain.xgo:526:1
			if
//line internal/toolchain/toolchain.xgo:526:1
			err := os.MkdirAll(p, 0o755); err != nil {
//line internal/toolchain/toolchain.xgo:527:1
				return err
			}
//line internal/toolchain/toolchain.xgo:529:1
			continue
		}
//line internal/toolchain/toolchain.xgo:531:1
		if
//line internal/toolchain/toolchain.xgo:531:1
		err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
//line internal/toolchain/toolchain.xgo:532:1
			return err
		}
//line internal/toolchain/toolchain.xgo:534:1
		rc, err := f.Open()
//line internal/toolchain/toolchain.xgo:535:1
		if err != nil {
//line internal/toolchain/toolchain.xgo:536:1
			return err
		}
//line internal/toolchain/toolchain.xgo:538:1
		out, err := os.Create(p)
//line internal/toolchain/toolchain.xgo:539:1
		if err != nil {
//line internal/toolchain/toolchain.xgo:540:1
			rc.Close()
//line internal/toolchain/toolchain.xgo:541:1
			return err
		}
//line internal/toolchain/toolchain.xgo:543:1
		if
//line internal/toolchain/toolchain.xgo:543:1
		_, err := io.Copy(out, rc); err != nil {
//line internal/toolchain/toolchain.xgo:544:1
			out.Close()
//line internal/toolchain/toolchain.xgo:545:1
			rc.Close()
//line internal/toolchain/toolchain.xgo:546:1
			return err
		}
//line internal/toolchain/toolchain.xgo:548:1
		out.Close()
//line internal/toolchain/toolchain.xgo:549:1
		rc.Close()
	}
//line internal/toolchain/toolchain.xgo:551:1
	return nil
}
//line internal/toolchain/toolchain.xgo:554:1
func findXgoAndRoot(root string) (xgoExe string, xgoRoot string, err error) {
//line internal/toolchain/toolchain.xgo:555:1
	// locate xgo.exe
	var found string
//line internal/toolchain/toolchain.xgo:557:1
	err = filepath.WalkDir(root, func(p string, d os.DirEntry, err error) error {
//line internal/toolchain/toolchain.xgo:558:1
		if err != nil {
//line internal/toolchain/toolchain.xgo:559:1
			return err
		}
//line internal/toolchain/toolchain.xgo:561:1
		if d.IsDir() {
//line internal/toolchain/toolchain.xgo:562:1
			return nil
		}
//line internal/toolchain/toolchain.xgo:564:1
		if strings.EqualFold(d.Name(), "xgo.exe") {
//line internal/toolchain/toolchain.xgo:565:1
			found = p
//line internal/toolchain/toolchain.xgo:566:1
			return errFound
		}
//line internal/toolchain/toolchain.xgo:568:1
		return nil
	})
//line internal/toolchain/toolchain.xgo:570:1
	if err != nil && !errors.Is(err, errFound) {
//line internal/toolchain/toolchain.xgo:571:1
		return "", "", err
	}
//line internal/toolchain/toolchain.xgo:573:1
	if found == "" {
//line internal/toolchain/toolchain.xgo:574:1
		return "", "", errors.New("xgo.exe not found after extraction/build")
	}
//line internal/toolchain/toolchain.xgo:576:1
	binDir := filepath.Dir(found)
//line internal/toolchain/toolchain.xgo:577:1
	cand := binDir
//line internal/toolchain/toolchain.xgo:578:1
	if strings.EqualFold(filepath.Base(binDir), "bin") {
//line internal/toolchain/toolchain.xgo:579:1
		cand = filepath.Dir(binDir)
	}
//line internal/toolchain/toolchain.xgo:582:1
	isValid := func(d string) bool {
//line internal/toolchain/toolchain.xgo:583:1
		if d == "" {
//line internal/toolchain/toolchain.xgo:584:1
			return false
		}
//line internal/toolchain/toolchain.xgo:586:1
		if
//line internal/toolchain/toolchain.xgo:586:1
		_, err := os.Stat(filepath.Join(d, "bin", "xgo.exe")); err != nil {
//line internal/toolchain/toolchain.xgo:587:1
			return false
		}
//line internal/toolchain/toolchain.xgo:589:1
		if
//line internal/toolchain/toolchain.xgo:589:1
		_, err := os.Stat(filepath.Join(d, "pkg")); err == nil {
//line internal/toolchain/toolchain.xgo:590:1
			return true
		}
//line internal/toolchain/toolchain.xgo:592:1
		if
//line internal/toolchain/toolchain.xgo:592:1
		_, err := os.Stat(filepath.Join(d, "src")); err == nil {
//line internal/toolchain/toolchain.xgo:593:1
			return true
		}
//line internal/toolchain/toolchain.xgo:595:1
		if
//line internal/toolchain/toolchain.xgo:595:1
		_, err := os.Stat(filepath.Join(d, "all.bash")); err == nil {
//line internal/toolchain/toolchain.xgo:596:1
			return true
		}
//line internal/toolchain/toolchain.xgo:598:1
		return false
	}
//line internal/toolchain/toolchain.xgo:600:1
	for !isValid(cand) {
//line internal/toolchain/toolchain.xgo:601:1
		parent := filepath.Dir(cand)
//line internal/toolchain/toolchain.xgo:602:1
		if parent == cand {
//line internal/toolchain/toolchain.xgo:603:1
			break
		}
//line internal/toolchain/toolchain.xgo:605:1
		cand = parent
	}
//line internal/toolchain/toolchain.xgo:607:1
	if !isValid(cand) {
//line internal/toolchain/toolchain.xgo:608:1
		return found, cand, fmt.Errorf("XGOROOT (%s) is not valid", cand)
	}
//line internal/toolchain/toolchain.xgo:610:1
	return found, cand, nil
}

var errFound = errors.New("found")
//line internal/toolchain/toolchain.xgo:615:1
func detectVersionFromXgo(xgoExe string, xgoRoot string) string {
//line internal/toolchain/toolchain.xgo:618:1
	cmd := exec.Command(xgoExe, "version")
//line internal/toolchain/toolchain.xgo:638:1
	cmd.Env = envForXgoCLI(xgoRoot)
//line internal/toolchain/toolchain.xgo:620:1
	out, _ := cmd.CombinedOutput()
//line internal/toolchain/toolchain.xgo:621:1
	s := strings.TrimSpace(string(out))
//line internal/toolchain/toolchain.xgo:622:1
	if s == "" {
//line internal/toolchain/toolchain.xgo:623:1
		return ""
	}
//line internal/toolchain/toolchain.xgo:625:1
	parts := strings.Fields(s)
//line internal/toolchain/toolchain.xgo:626:1
	if len(parts) == 0 {
//line internal/toolchain/toolchain.xgo:627:1
		return ""
	}
//line internal/toolchain/toolchain.xgo:629:1
	return strings.Join(parts, " ")
}
//line internal/toolchain/toolchain.xgo:632:1
// envForXgoCLI returns process env without a bogus XGOROOT, then sets XGOROOT when known.
func envForXgoCLI(xgoRoot string) []string {
//line internal/toolchain/toolchain.xgo:634:1
	out := stripXGOROOTFromEnviron()
//line internal/toolchain/toolchain.xgo:635:1
	if xgoRoot != "" {
//line internal/toolchain/toolchain.xgo:636:1
		out = append(out, "XGOROOT="+xgoRoot)
	}
//line internal/toolchain/toolchain.xgo:638:1
	return out
}
//line internal/toolchain/toolchain.xgo:641:1
func stripXGOROOTFromEnviron() []string {
//line internal/toolchain/toolchain.xgo:642:1
	var out []string
	for
//line internal/toolchain/toolchain.xgo:643:1
	_, e := range os.Environ() {
//line internal/toolchain/toolchain.xgo:644:1
		if strings.HasPrefix(strings.ToUpper(e), "XGOROOT=") {
//line internal/toolchain/toolchain.xgo:645:1
			continue
		}
//line internal/toolchain/toolchain.xgo:647:1
		out = append(out, e)
	}
//line internal/toolchain/toolchain.xgo:649:1
	return out
}
//line internal/toolchain/toolchain.xgo:227:1
func installLinked(p home.Paths, c config.Config, name string, opt InstallOptions) (config.Config, error) {
//line internal/toolchain/toolchain.xgo:228:1
	if opt.Path == "" {
//line internal/toolchain/toolchain.xgo:229:1
		return config.Config{}, errors.New("linked method requires --path")
	}
//line internal/toolchain/toolchain.xgo:231:1
	abs, err := filepath.Abs(opt.Path)
//line internal/toolchain/toolchain.xgo:232:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:233:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:235:1
	xgo := filepath.Join(abs, "bin", "xgo.exe")
//line internal/toolchain/toolchain.xgo:236:1
	if
//line internal/toolchain/toolchain.xgo:236:1
	_, err := os.Stat(xgo); err != nil {
//line internal/toolchain/toolchain.xgo:237:1
		return config.Config{}, fmt.Errorf("linked path missing xgo: %s", xgo)
	}
//line internal/toolchain/toolchain.xgo:239:1
	if
//line internal/toolchain/toolchain.xgo:239:1
	_, err := os.Stat(meta.FilePath(p.Metadata, name)); err == nil && !opt.Force {
//line internal/toolchain/toolchain.xgo:240:1
		return config.Config{}, fmt.Errorf("toolchain already exists: %s (use --force)", name)
	}
//line internal/toolchain/toolchain.xgo:242:1
	m := meta.ToolchainMeta{Name: name, Kind: "linked", RootPath: abs, XgoBin: xgo, XgoRootValue: abs, Managed: "false", Version: detectVersionFromXgo(xgo, abs)}
//line internal/toolchain/toolchain.xgo:251:1
	if
//line internal/toolchain/toolchain.xgo:251:1
	err := meta.Save(p.Metadata, name, m); err != nil {
//line internal/toolchain/toolchain.xgo:252:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:254:1
	c.Toolchains[name] = config.Toolchain{Kind: "linked", Path: abs, Managed: false, Version: m.Version}
//line internal/toolchain/toolchain.xgo:255:1
	if c.DefaultToolchain == "" {
//line internal/toolchain/toolchain.xgo:256:1
		c.DefaultToolchain = name
	}
//line internal/toolchain/toolchain.xgo:258:1
	if
//line internal/toolchain/toolchain.xgo:258:1
	err := SaveConfig(p, c); err != nil {
//line internal/toolchain/toolchain.xgo:259:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:261:1
	return c, nil
}
//line internal/toolchain/toolchain.xgo:325:1
func installSource(p home.Paths, c config.Config, name string, opt InstallOptions) (config.Config, error) {
//line internal/toolchain/toolchain.xgo:326:1
	repo := opt.Repo
//line internal/toolchain/toolchain.xgo:327:1
	if repo == "" {
//line internal/toolchain/toolchain.xgo:328:1
		repo = DefaultSourceRepo
	}
//line internal/toolchain/toolchain.xgo:330:1
	if
//line internal/toolchain/toolchain.xgo:330:1
	_, err := os.Stat(meta.FilePath(p.Metadata, name)); err == nil && !opt.Force {
//line internal/toolchain/toolchain.xgo:331:1
		return config.Config{}, fmt.Errorf("toolchain already exists: %s (use --force)", name)
	}
//line internal/toolchain/toolchain.xgo:333:1
	if
//line internal/toolchain/toolchain.xgo:333:1
	_, err := exec.LookPath("git"); err != nil {
//line internal/toolchain/toolchain.xgo:334:1
		return config.Config{}, errors.New("missing required command: git")
	}
//line internal/toolchain/toolchain.xgo:336:1
	bash, err := findBash()
//line internal/toolchain/toolchain.xgo:337:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:338:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:341:1
	target := filepath.Join(p.Toolchains, name)
//line internal/toolchain/toolchain.xgo:342:1
	if opt.Force {
//line internal/toolchain/toolchain.xgo:343:1
		_ = os.RemoveAll(target)
	}
//line internal/toolchain/toolchain.xgo:346:1
	if
//line internal/toolchain/toolchain.xgo:346:1
	err := execCmd("", "git", "clone", repo, target); err != nil {
//line internal/toolchain/toolchain.xgo:347:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:349:1
	if opt.Ref != "" {
//line internal/toolchain/toolchain.xgo:350:1
		if
//line internal/toolchain/toolchain.xgo:350:1
		err := execCmd("", "git", "-C", target, "checkout", opt.Ref); err != nil {
//line internal/toolchain/toolchain.xgo:351:1
			return config.Config{}, err
		}
	}
//line internal/toolchain/toolchain.xgo:356:1
	if
//line internal/toolchain/toolchain.xgo:356:1
	err := execCmd(target, bash, "-lc", "./all.bash"); err != nil {
//line internal/toolchain/toolchain.xgo:357:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:360:1
	xgoExe, xgoroot, err := findXgoAndRoot(target)
//line internal/toolchain/toolchain.xgo:361:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:362:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:365:1
	commit := ""
//line internal/toolchain/toolchain.xgo:366:1
	if
//line internal/toolchain/toolchain.xgo:366:1
	out, err := exec.Command("git", "-C", target, "rev-parse", "HEAD").CombinedOutput(); err == nil {
//line internal/toolchain/toolchain.xgo:367:1
		commit = strings.TrimSpace(string(out))
	}
//line internal/toolchain/toolchain.xgo:370:1
	m := meta.ToolchainMeta{Name: name, Kind: "source", RootPath: xgoroot, XgoBin: xgoExe, XgoRootValue: xgoroot, Managed: "true", Repo: repo, Ref: opt.Ref, Commit: commit, Version: detectVersionFromXgo(xgoExe, xgoroot)}
//line internal/toolchain/toolchain.xgo:382:1
	if
//line internal/toolchain/toolchain.xgo:382:1
	err := meta.Save(p.Metadata, name, m); err != nil {
//line internal/toolchain/toolchain.xgo:383:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:385:1
	c.Toolchains[name] = config.Toolchain{Kind: "source", Path: xgoroot, Managed: true, Version: m.Version, Repo: repo, Ref: opt.Ref, Commit: commit}
//line internal/toolchain/toolchain.xgo:386:1
	if c.DefaultToolchain == "" {
//line internal/toolchain/toolchain.xgo:387:1
		c.DefaultToolchain = name
	}
//line internal/toolchain/toolchain.xgo:389:1
	if
//line internal/toolchain/toolchain.xgo:389:1
	err := SaveConfig(p, c); err != nil {
//line internal/toolchain/toolchain.xgo:390:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:392:1
	return c, nil
}
//line internal/toolchain/toolchain.xgo:652:1
func findBash() (string, error) {
//line internal/toolchain/toolchain.xgo:653:1
	if
//line internal/toolchain/toolchain.xgo:653:1
	p, err := exec.LookPath("bash.exe"); err == nil {
//line internal/toolchain/toolchain.xgo:654:1
		return p, nil
	}
//line internal/toolchain/toolchain.xgo:656:1
	if
//line internal/toolchain/toolchain.xgo:656:1
	p, err := exec.LookPath("bash"); err == nil {
//line internal/toolchain/toolchain.xgo:657:1
		return p, nil
	}
//line internal/toolchain/toolchain.xgo:660:1
	common := []string{filepath.Join(os.Getenv("ProgramFiles"), "Git", "bin", "bash.exe"), filepath.Join(os.Getenv("ProgramFiles(x86)"), "Git", "bin", "bash.exe")}
	for
//line internal/toolchain/toolchain.xgo:664:1
	_, p := range common {
//line internal/toolchain/toolchain.xgo:665:1
		if p == "" {
//line internal/toolchain/toolchain.xgo:666:1
			continue
		}
//line internal/toolchain/toolchain.xgo:668:1
		if
//line internal/toolchain/toolchain.xgo:668:1
		_, err := os.Stat(p); err == nil {
//line internal/toolchain/toolchain.xgo:669:1
			return p, nil
		}
	}
//line internal/toolchain/toolchain.xgo:672:1
	return "", errors.New("bash.exe not found; install Git for Windows (Git-Bash) or MSYS2 and ensure bash is on PATH")
}
//line internal/toolchain/toolchain.xgo:675:1
func execCmd(dir string, exe string, args ...string) error {
//line internal/toolchain/toolchain.xgo:676:1
	cmd := exec.Command(exe, args...) 
//line internal/toolchain/toolchain.xgo:677:1
	if dir != "" {
//line internal/toolchain/toolchain.xgo:678:1
		cmd.Dir = dir
	}
//line internal/toolchain/toolchain.xgo:680:1
	cmd.Env = stripXGOROOTFromEnviron()
//line internal/toolchain/toolchain.xgo:681:1
	cmd.Stdout = os.Stdout
//line internal/toolchain/toolchain.xgo:682:1
	cmd.Stderr = os.Stderr
//line internal/toolchain/toolchain.xgo:683:1
	return cmd.Run()
}
//line internal/toolchain/toolchain.xgo:181:1
func Update(p home.Paths, c config.Config, name string) (config.Config, error) {
//line internal/toolchain/toolchain.xgo:182:1
	if name == "" {
//line internal/toolchain/toolchain.xgo:183:1
		name = c.DefaultToolchain
	}
//line internal/toolchain/toolchain.xgo:185:1
	if name == "" {
//line internal/toolchain/toolchain.xgo:186:1
		return config.Config{}, errors.New("no toolchain specified and no default configured")
	}
//line internal/toolchain/toolchain.xgo:188:1
	tc, ok := c.Toolchains[name]
//line internal/toolchain/toolchain.xgo:189:1
	if !ok {
//line internal/toolchain/toolchain.xgo:190:1
		return config.Config{}, fmt.Errorf("toolchain not found: %s", name)
	}
//line internal/toolchain/toolchain.xgo:192:1
	switch tc.Kind {
//line internal/toolchain/toolchain.xgo:193:1
	case "standard":
//line internal/toolchain/toolchain.xgo:194:1
		return installStandard(p, c, name, InstallOptions{Method: "standard", Force: true})
//line internal/toolchain/toolchain.xgo:195:1
	case "source":
//line internal/toolchain/toolchain.xgo:435:1
		return installSourceUpdate(p, c, name)
//line internal/toolchain/toolchain.xgo:197:1
	case "linked":
//line internal/toolchain/toolchain.xgo:198:1
		return c, fmt.Errorf("linked toolchain update is a no-op: %s", name)
//line internal/toolchain/toolchain.xgo:199:1
	default:
//line internal/toolchain/toolchain.xgo:200:1
		return config.Config{}, fmt.Errorf("unknown toolchain kind: %s", tc.Kind)
	}
}
//line internal/toolchain/toolchain.xgo:395:1
func installSourceUpdate(p home.Paths, c config.Config, name string) (config.Config, error) {
//line internal/toolchain/toolchain.xgo:396:1
	tc := c.Toolchains[name]
//line internal/toolchain/toolchain.xgo:397:1
	if tc.Path == "" {
//line internal/toolchain/toolchain.xgo:398:1
		return config.Config{}, errors.New("source toolchain missing path")
	}
//line internal/toolchain/toolchain.xgo:400:1
	if
//line internal/toolchain/toolchain.xgo:400:1
	_, err := exec.LookPath("git"); err != nil {
//line internal/toolchain/toolchain.xgo:401:1
		return config.Config{}, errors.New("missing required command: git")
	}
//line internal/toolchain/toolchain.xgo:403:1
	bash, err := findBash()
//line internal/toolchain/toolchain.xgo:404:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:405:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:408:1
	_ = execCmd("", "git", "-C", tc.Path, "fetch", "--tags", "--prune")
//line internal/toolchain/toolchain.xgo:409:1
	_ = execCmd("", "git", "-C", tc.Path, "pull", "--ff-only")
//line internal/toolchain/toolchain.xgo:410:1
	if
//line internal/toolchain/toolchain.xgo:410:1
	err := execCmd(tc.Path, bash, "-lc", "./all.bash"); err != nil {
//line internal/toolchain/toolchain.xgo:411:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:413:1
	xgoExe, xgoroot, err := findXgoAndRoot(tc.Path)
//line internal/toolchain/toolchain.xgo:414:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:415:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:417:1
	m, _ := meta.Load(p.Metadata, name)
//line internal/toolchain/toolchain.xgo:418:1
	m.RootPath = xgoroot
//line internal/toolchain/toolchain.xgo:419:1
	m.XgoBin = xgoExe
//line internal/toolchain/toolchain.xgo:420:1
	m.XgoRootValue = xgoroot
//line internal/toolchain/toolchain.xgo:421:1
	m.Version = detectVersionFromXgo(xgoExe, xgoroot)
//line internal/toolchain/toolchain.xgo:422:1
	if
//line internal/toolchain/toolchain.xgo:422:1
	out, err := exec.Command("git", "-C", tc.Path, "rev-parse", "HEAD").CombinedOutput(); err == nil {
//line internal/toolchain/toolchain.xgo:423:1
		m.Commit = strings.TrimSpace(string(out))
	}
//line internal/toolchain/toolchain.xgo:425:1
	if
//line internal/toolchain/toolchain.xgo:425:1
	err := meta.Save(p.Metadata, name, m); err != nil {
//line internal/toolchain/toolchain.xgo:426:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:428:1
	tc.Path = xgoroot
//line internal/toolchain/toolchain.xgo:429:1
	tc.Version = m.Version
//line internal/toolchain/toolchain.xgo:430:1
	tc.Commit = m.Commit
//line internal/toolchain/toolchain.xgo:431:1
	c.Toolchains[name] = tc
//line internal/toolchain/toolchain.xgo:432:1
	if
//line internal/toolchain/toolchain.xgo:432:1
	err := SaveConfig(p, c); err != nil {
//line internal/toolchain/toolchain.xgo:433:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:435:1
	return c, nil
}
//line internal/toolchain/toolchain.xgo:204:1
func Doctor(p home.Paths, c config.Config) error {
//line internal/toolchain/toolchain.xgo:206:1
	if
//line internal/toolchain/toolchain.xgo:206:1
	err := config.Validate(c); err != nil {
//line internal/toolchain/toolchain.xgo:207:1
		return err
	}
//line internal/toolchain/toolchain.xgo:210:1
	names, _ := meta.Names(p.Metadata)
	for
//line internal/toolchain/toolchain.xgo:211:1
	_, n := range names {
//line internal/toolchain/toolchain.xgo:212:1
		m, err := meta.Load(p.Metadata, n)
//line internal/toolchain/toolchain.xgo:213:1
		if err != nil {
//line internal/toolchain/toolchain.xgo:214:1
			return fmt.Errorf("metadata load failed for %s: %w", n, err)
		}
//line internal/toolchain/toolchain.xgo:216:1
		if m.XgoBin != "" {
//line internal/toolchain/toolchain.xgo:217:1
			if
//line internal/toolchain/toolchain.xgo:217:1
			_, err := os.Stat(m.XgoBin); err != nil {
//line internal/toolchain/toolchain.xgo:218:1
				return fmt.Errorf("xgo missing for %s: %s", n, m.XgoBin)
			}
		}
	}
//line internal/toolchain/toolchain.xgo:222:1
	return nil
}
