// Code generated by xgo (XGo); DO NOT EDIT.

package toolchain

import (
	"archive/zip"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/fanfeilong/xgoup/internal/config"
	"github.com/fanfeilong/xgoup/internal/home"
	"github.com/fanfeilong/xgoup/internal/meta"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"time"
)

const _ = true
const DefaultSourceRepo = "https://github.com/goplus/xgo.git"
const MinGoMajor = 1
const MinGoMinor = 19

type InstallOptions struct {
	Method string
	Repo   string
	Ref    string
	Path   string
	Force  bool
}
//line internal/toolchain/toolchain.xgo:36:1
func Init() (home.Paths, config.Config, error) {
//line internal/toolchain/toolchain.xgo:37:1
	p, err := home.Resolve()
//line internal/toolchain/toolchain.xgo:38:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:39:1
		return home.Paths{}, config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:41:1
	if
//line internal/toolchain/toolchain.xgo:41:1
	err := home.EnsureDirs(p); err != nil {
//line internal/toolchain/toolchain.xgo:42:1
		return home.Paths{}, config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:45:1
	cfg, err := readOrCreateConfig(p)
//line internal/toolchain/toolchain.xgo:46:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:47:1
		return home.Paths{}, config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:49:1
	return p, cfg, nil
}
//line internal/toolchain/toolchain.xgo:52:1
func readOrCreateConfig(p home.Paths) (config.Config, error) {
//line internal/toolchain/toolchain.xgo:53:1
	_, err := os.Stat(p.Config)
//line internal/toolchain/toolchain.xgo:54:1
	if err == nil {
//line internal/toolchain/toolchain.xgo:55:1
		c, err := config.Load(p.Config)
//line internal/toolchain/toolchain.xgo:56:1
		if err != nil {
//line internal/toolchain/toolchain.xgo:57:1
			return config.Config{}, err
		}
//line internal/toolchain/toolchain.xgo:59:1
		if
//line internal/toolchain/toolchain.xgo:59:1
		err := config.Validate(c); err != nil {
//line internal/toolchain/toolchain.xgo:60:1
			return config.Config{}, err
		}
//line internal/toolchain/toolchain.xgo:62:1
		return c, nil
	}
//line internal/toolchain/toolchain.xgo:64:1
	if !os.IsNotExist(err) {
//line internal/toolchain/toolchain.xgo:65:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:68:1
	c := config.Default(DefaultSourceRepo)
//line internal/toolchain/toolchain.xgo:71:1
	names, _ := meta.Names(p.Metadata)
	for
//line internal/toolchain/toolchain.xgo:72:1
	_, n := range names {
//line internal/toolchain/toolchain.xgo:73:1
		m, err := meta.Load(p.Metadata, n)
//line internal/toolchain/toolchain.xgo:74:1
		if err != nil {
//line internal/toolchain/toolchain.xgo:75:1
			continue
		}
//line internal/toolchain/toolchain.xgo:77:1
		managed := strings.EqualFold(m.Managed, "true")
//line internal/toolchain/toolchain.xgo:78:1
		c.Toolchains[n] = config.Toolchain{Kind: m.Kind, Path: m.RootPath, Managed: managed, Version: m.Version, Repo: m.Repo, Ref: m.Ref, Commit: m.Commit}
	}
//line internal/toolchain/toolchain.xgo:88:1
	if c.DefaultToolchain == "" && len(c.Toolchains) > 0 {
//line internal/toolchain/toolchain.xgo:89:1
		// Pick first stable ordering.
		var keys []string
		for
//line internal/toolchain/toolchain.xgo:91:1
		k := range c.Toolchains {
//line internal/toolchain/toolchain.xgo:92:1
			keys = append(keys, k)
		}
//line internal/toolchain/toolchain.xgo:94:1
		sort.Strings(keys)
//line internal/toolchain/toolchain.xgo:95:1
		c.DefaultToolchain = keys[0]
	}
//line internal/toolchain/toolchain.xgo:97:1
	if
//line internal/toolchain/toolchain.xgo:97:1
	err := config.Save(p.Config, c); err != nil {
//line internal/toolchain/toolchain.xgo:98:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:100:1
	return c, nil
}
//line internal/toolchain/toolchain.xgo:103:1
func SaveConfig(p home.Paths, c config.Config) error {
//line internal/toolchain/toolchain.xgo:104:1
	if
//line internal/toolchain/toolchain.xgo:104:1
	err := config.Validate(c); err != nil {
//line internal/toolchain/toolchain.xgo:105:1
		return err
	}
//line internal/toolchain/toolchain.xgo:107:1
	return config.Save(p.Config, c)
}
//line internal/toolchain/toolchain.xgo:110:1
func SetDefault(p home.Paths, c config.Config, name string) (config.Config, error) {
//line internal/toolchain/toolchain.xgo:111:1
	if
//line internal/toolchain/toolchain.xgo:111:1
	_, ok := c.Toolchains[name]; !ok {
//line internal/toolchain/toolchain.xgo:112:1
		return config.Config{}, fmt.Errorf("toolchain not found: %s", name)
	}
//line internal/toolchain/toolchain.xgo:114:1
	c.DefaultToolchain = name
//line internal/toolchain/toolchain.xgo:115:1
	if
//line internal/toolchain/toolchain.xgo:115:1
	err := SaveConfig(p, c); err != nil {
//line internal/toolchain/toolchain.xgo:116:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:118:1
	return c, nil
}
//line internal/toolchain/toolchain.xgo:121:1
func List(p home.Paths, c config.Config) ([]meta.ToolchainMeta, error) {
//line internal/toolchain/toolchain.xgo:122:1
	names, err := meta.Names(p.Metadata)
//line internal/toolchain/toolchain.xgo:123:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:124:1
		return nil, err
	}
//line internal/toolchain/toolchain.xgo:126:1
	out := make([]meta.ToolchainMeta, 0, len(names))
	for
//line internal/toolchain/toolchain.xgo:127:1
	_, n := range names {
//line internal/toolchain/toolchain.xgo:128:1
		m, err := meta.Load(p.Metadata, n)
//line internal/toolchain/toolchain.xgo:129:1
		if err != nil {
//line internal/toolchain/toolchain.xgo:130:1
			return nil, err
		}
//line internal/toolchain/toolchain.xgo:132:1
		out = append(out, m)
	}
//line internal/toolchain/toolchain.xgo:134:1
	return out, nil
}
//line internal/toolchain/toolchain.xgo:137:1
func Remove(p home.Paths, c config.Config, name string, purge bool) (config.Config, error) {
//line internal/toolchain/toolchain.xgo:138:1
	m, err := meta.Load(p.Metadata, name)
//line internal/toolchain/toolchain.xgo:139:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:140:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:142:1
	if purge && strings.EqualFold(m.Managed, "true") && m.RootPath != "" {
//line internal/toolchain/toolchain.xgo:143:1
		_ = os.RemoveAll(m.RootPath)
	}
//line internal/toolchain/toolchain.xgo:145:1
	_ = os.Remove(meta.FilePath(p.Metadata, name))
//line internal/toolchain/toolchain.xgo:147:1
	delete(c.Toolchains, name)
//line internal/toolchain/toolchain.xgo:148:1
	if c.DefaultToolchain == name {
//line internal/toolchain/toolchain.xgo:149:1
		c.DefaultToolchain = ""
	}
//line internal/toolchain/toolchain.xgo:151:1
	if c.DefaultToolchain == "" && len(c.Toolchains) > 0 {
//line internal/toolchain/toolchain.xgo:152:1
		var keys []string
		for
//line internal/toolchain/toolchain.xgo:153:1
		k := range c.Toolchains {
//line internal/toolchain/toolchain.xgo:154:1
			keys = append(keys, k)
		}
//line internal/toolchain/toolchain.xgo:156:1
		sort.Strings(keys)
//line internal/toolchain/toolchain.xgo:157:1
		c.DefaultToolchain = keys[0]
	}
//line internal/toolchain/toolchain.xgo:159:1
	if
//line internal/toolchain/toolchain.xgo:159:1
	err := SaveConfig(p, c); err != nil {
//line internal/toolchain/toolchain.xgo:160:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:162:1
	return c, nil
}
//line internal/toolchain/toolchain.xgo:165:1
func Install(p home.Paths, c config.Config, name string, opt InstallOptions) (config.Config, error) {
//line internal/toolchain/toolchain.xgo:166:1
	if name == "" {
//line internal/toolchain/toolchain.xgo:167:1
		return config.Config{}, errors.New("missing toolchain name")
	}
//line internal/toolchain/toolchain.xgo:169:1
	if opt.Method == "" {
//line internal/toolchain/toolchain.xgo:170:1
		opt.Method = "standard"
	}
//line internal/toolchain/toolchain.xgo:172:1
	switch opt.Method {
//line internal/toolchain/toolchain.xgo:173:1
	case "standard":
//line internal/toolchain/toolchain.xgo:329:1
		return installStandard(p, c, name, opt)
//line internal/toolchain/toolchain.xgo:175:1
	case "linked":
//line internal/toolchain/toolchain.xgo:264:1
		return installLinked(p, c, name, opt)
//line internal/toolchain/toolchain.xgo:177:1
	case "source":
//line internal/toolchain/toolchain.xgo:399:1
		return installSource(p, c, name, opt)
//line internal/toolchain/toolchain.xgo:179:1
	default:
//line internal/toolchain/toolchain.xgo:180:1
		return config.Config{}, fmt.Errorf("unknown method: %s", opt.Method)
	}
}
//line internal/toolchain/toolchain.xgo:267:1
func installStandard(p home.Paths, c config.Config, name string, opt InstallOptions) (config.Config, error) {
//line internal/toolchain/toolchain.xgo:268:1
	if
//line internal/toolchain/toolchain.xgo:268:1
	_, err := os.Stat(meta.FilePath(p.Metadata, name)); err == nil && !opt.Force {
//line internal/toolchain/toolchain.xgo:269:1
		return config.Config{}, fmt.Errorf("toolchain already exists: %s (use --force)", name)
	}
//line internal/toolchain/toolchain.xgo:272:1
	if
//line internal/toolchain/toolchain.xgo:272:1
	err := ensureGo(MinGoMajor, MinGoMinor); err != nil {
//line internal/toolchain/toolchain.xgo:273:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:276:1
	arch, err := windowsArch()
//line internal/toolchain/toolchain.xgo:277:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:278:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:281:1
	tag, asset, err := latestXgoWindowsAsset(arch)
//line internal/toolchain/toolchain.xgo:282:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:283:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:285:1
	url := fmt.Sprintf("https://github.com/goplus/xgo/releases/download/%s/%s", tag, asset)
//line internal/toolchain/toolchain.xgo:287:1
	tmpZip := filepath.Join(os.TempDir(), fmt.Sprintf("xgo-%d.zip", time.Now().UnixNano()))
//line internal/toolchain/toolchain.xgo:288:1
	defer os.Remove(tmpZip)
//line internal/toolchain/toolchain.xgo:289:1
	if
//line internal/toolchain/toolchain.xgo:289:1
	err := httpGetToFile(url, tmpZip); err != nil {
//line internal/toolchain/toolchain.xgo:290:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:293:1
	target := filepath.Join(p.Toolchains, name)
//line internal/toolchain/toolchain.xgo:294:1
	if opt.Force {
//line internal/toolchain/toolchain.xgo:295:1
		_ = os.RemoveAll(target)
	}
//line internal/toolchain/toolchain.xgo:297:1
	if
//line internal/toolchain/toolchain.xgo:297:1
	err := unzipAll(tmpZip, target); err != nil {
//line internal/toolchain/toolchain.xgo:298:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:301:1
	xgoExe, xgoroot, err := findXgoAndRoot(target)
//line internal/toolchain/toolchain.xgo:302:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:303:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:306:1
	m := meta.ToolchainMeta{Name: name, Kind: "standard", RootPath: xgoroot, XgoBin: xgoExe, XgoRootValue: xgoroot, Managed: "true", Version: detectVersionFromXgo(xgoExe, xgoroot)}
//line internal/toolchain/toolchain.xgo:315:1
	if m.Version == "" {
//line internal/toolchain/toolchain.xgo:316:1
		m.Version = tag
	}
//line internal/toolchain/toolchain.xgo:319:1
	if
//line internal/toolchain/toolchain.xgo:319:1
	err := meta.Save(p.Metadata, name, m); err != nil {
//line internal/toolchain/toolchain.xgo:320:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:322:1
	c.Toolchains[name] = config.Toolchain{Kind: "standard", Path: xgoroot, Managed: true, Version: m.Version}
//line internal/toolchain/toolchain.xgo:323:1
	if c.DefaultToolchain == "" {
//line internal/toolchain/toolchain.xgo:324:1
		c.DefaultToolchain = name
	}
//line internal/toolchain/toolchain.xgo:326:1
	if
//line internal/toolchain/toolchain.xgo:326:1
	err := SaveConfig(p, c); err != nil {
//line internal/toolchain/toolchain.xgo:327:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:329:1
	return c, nil
}
//line internal/toolchain/toolchain.xgo:458:1
func ensureGo(minMajor int, minMinor int) error {
//line internal/toolchain/toolchain.xgo:459:1
	ok, got, err := haveGo(minMajor, minMinor)
//line internal/toolchain/toolchain.xgo:460:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:461:1
		return err
	}
//line internal/toolchain/toolchain.xgo:463:1
	if ok {
//line internal/toolchain/toolchain.xgo:464:1
		return nil
	}
//line internal/toolchain/toolchain.xgo:468:1
	switch runtime.GOOS {
//line internal/toolchain/toolchain.xgo:469:1
	case "windows":
//line internal/toolchain/toolchain.xgo:470:1
		if
//line internal/toolchain/toolchain.xgo:470:1
		err := installGoWindows(); err != nil {
//line internal/toolchain/toolchain.xgo:471:1
			return fmt.Errorf("Go is required (>= go%d.%d); not found (got: %s): %w", minMajor, minMinor, got, err)
		}
//line internal/toolchain/toolchain.xgo:473:1
		if
//line internal/toolchain/toolchain.xgo:473:1
		err := maybeAddGoToPathWindows(); err != nil {
//line internal/toolchain/toolchain.xgo:475:1
			_ = err
		}
//line internal/toolchain/toolchain.xgo:477:1
	default:
//line internal/toolchain/toolchain.xgo:478:1
		return fmt.Errorf("Go is required (>= go%d.%d); not found (got: %s). Install Go and ensure `go` is on PATH", minMajor, minMinor, got)
	}
//line internal/toolchain/toolchain.xgo:481:1
	ok, got, err = haveGo(minMajor, minMinor)
//line internal/toolchain/toolchain.xgo:482:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:483:1
		return err
	}
//line internal/toolchain/toolchain.xgo:485:1
	if !ok {
//line internal/toolchain/toolchain.xgo:486:1
		return fmt.Errorf("Go is required (>= go%d.%d); still not available after install attempt (got: %s)", minMajor, minMinor, got)
	}
//line internal/toolchain/toolchain.xgo:488:1
	return nil
}
//line internal/toolchain/toolchain.xgo:491:1
func haveGo(minMajor int, minMinor int) (ok bool, got string, err error) {
//line internal/toolchain/toolchain.xgo:492:1
	goExe, err := exec.LookPath("go")
//line internal/toolchain/toolchain.xgo:493:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:494:1
		return false, "missing", nil
	}
//line internal/toolchain/toolchain.xgo:496:1
	out, err := exec.Command(goExe, "version").CombinedOutput()
//line internal/toolchain/toolchain.xgo:497:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:498:1
		return false, strings.TrimSpace(string(out)), nil
	}
//line internal/toolchain/toolchain.xgo:500:1
	maj, min, ver := parseGoVersion(string(out))
//line internal/toolchain/toolchain.xgo:501:1
	if maj == 0 && min == 0 {
//line internal/toolchain/toolchain.xgo:503:1
		return true, strings.TrimSpace(ver), nil
	}
//line internal/toolchain/toolchain.xgo:505:1
	if maj > minMajor || maj == minMajor && min >= minMinor {
//line internal/toolchain/toolchain.xgo:506:1
		return true, ver, nil
	}
//line internal/toolchain/toolchain.xgo:508:1
	return false, ver, nil
}
//line internal/toolchain/toolchain.xgo:511:1
func parseGoVersion(s string) (major int, minor int, ver string) {
//line internal/toolchain/toolchain.xgo:516:1
	f := strings.Fields(strings.TrimSpace(s))
	for
//line internal/toolchain/toolchain.xgo:517:1
	_, tok := range f {
//line internal/toolchain/toolchain.xgo:518:1
		if strings.HasPrefix(tok, "go1.") {
//line internal/toolchain/toolchain.xgo:519:1
			ver = tok
//line internal/toolchain/toolchain.xgo:520:1
			maj, min := parseGoMajorMinor(strings.TrimPrefix(tok, "go"))
//line internal/toolchain/toolchain.xgo:521:1
			return maj, min, tok
		}
	}
//line internal/toolchain/toolchain.xgo:524:1
	if len(f) > 0 {
//line internal/toolchain/toolchain.xgo:525:1
		ver = f[len(f)-1]
	}
//line internal/toolchain/toolchain.xgo:527:1
	return 0, 0, strings.TrimSpace(s)
}
//line internal/toolchain/toolchain.xgo:530:1
func parseGoMajorMinor(v string) (major int, minor int) {
//line internal/toolchain/toolchain.xgo:532:1
	parts := strings.SplitN(v, ".", 3)
//line internal/toolchain/toolchain.xgo:533:1
	if len(parts) < 2 {
//line internal/toolchain/toolchain.xgo:534:1
		return 0, 0
	}
//line internal/toolchain/toolchain.xgo:549:1
	major = atoiSafe(parts[0])
//line internal/toolchain/toolchain.xgo:537:1
	minor = atoiSafe(parts[1])
//line internal/toolchain/toolchain.xgo:538:1
	return major, minor
}
//line internal/toolchain/toolchain.xgo:541:1
func atoiSafe(s string) int {
//line internal/toolchain/toolchain.xgo:542:1
	n := 0
	for
//line internal/toolchain/toolchain.xgo:543:1
	_, r := range s {
//line internal/toolchain/toolchain.xgo:544:1
		if r < '0' || r > '9' {
//line internal/toolchain/toolchain.xgo:545:1
			break
		}
//line internal/toolchain/toolchain.xgo:547:1
		n = n*10 + int(r-'0')
	}
//line internal/toolchain/toolchain.xgo:549:1
	return n
}
//line internal/toolchain/toolchain.xgo:552:1
func installGoWindows() error {
//line internal/toolchain/toolchain.xgo:553:1
	winget, err := exec.LookPath("winget")
//line internal/toolchain/toolchain.xgo:554:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:555:1
		return errors.New("winget not found; install Go manually or install winget (App Installer)")
	}
//line internal/toolchain/toolchain.xgo:558:1
	cmd := exec.Command(winget, "install", "--id", "GoLang.Go", "-e", "--accept-package-agreements", "--accept-source-agreements")
//line internal/toolchain/toolchain.xgo:565:1
	cmd.Stdout = os.Stdout
//line internal/toolchain/toolchain.xgo:566:1
	cmd.Stderr = os.Stderr
//line internal/toolchain/toolchain.xgo:567:1
	return cmd.Run()
}
//line internal/toolchain/toolchain.xgo:570:1
func maybeAddGoToPathWindows() error {
//line internal/toolchain/toolchain.xgo:572:1
	root := os.Getenv("ProgramFiles")
//line internal/toolchain/toolchain.xgo:573:1
	if root == "" {
//line internal/toolchain/toolchain.xgo:574:1
		return nil
	}
//line internal/toolchain/toolchain.xgo:576:1
	bin := filepath.Join(root, "Go", "bin")
//line internal/toolchain/toolchain.xgo:577:1
	if
//line internal/toolchain/toolchain.xgo:577:1
	_, err := os.Stat(filepath.Join(bin, "go.exe")); err != nil {
//line internal/toolchain/toolchain.xgo:578:1
		return nil
	}
//line internal/toolchain/toolchain.xgo:582:1
	path := os.Getenv("PATH")
//line internal/toolchain/toolchain.xgo:583:1
	if !strings.Contains(strings.ToLower(path), strings.ToLower(bin)) {
//line internal/toolchain/toolchain.xgo:584:1
		_ = os.Setenv("PATH", bin+string(os.PathListSeparator)+path)
	}
//line internal/toolchain/toolchain.xgo:588:1
	ps := fmt.Sprintf(`
$bin = '%s'
$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
if (-not $userPath) { $userPath = '' }
$parts = $userPath.Split(';') | Where-Object { $_ -ne '' }
if ($parts -notcontains $bin) {
  $newPath = if ($userPath.Trim().Length -gt 0) { "$bin;$userPath" } else { $bin }
  [Environment]::SetEnvironmentVariable('Path', $newPath, 'User')
}
`, strings.ReplaceAll(bin, `'`, `''`))
//line internal/toolchain/toolchain.xgo:598:1
	c := exec.Command("powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", ps)
//line internal/toolchain/toolchain.xgo:599:1
	_, _ = c.CombinedOutput()
//line internal/toolchain/toolchain.xgo:600:1
	return nil
}
//line internal/toolchain/toolchain.xgo:447:1
func windowsArch() (string, error) {
//line internal/toolchain/toolchain.xgo:448:1
	switch runtime.GOARCH {
//line internal/toolchain/toolchain.xgo:449:1
	case "amd64":
//line internal/toolchain/toolchain.xgo:450:1
		return "amd64", nil
//line internal/toolchain/toolchain.xgo:451:1
	case "arm64":
//line internal/toolchain/toolchain.xgo:452:1
		return "arm64", nil
//line internal/toolchain/toolchain.xgo:453:1
	default:
//line internal/toolchain/toolchain.xgo:454:1
		return "", fmt.Errorf("unsupported arch: %s", runtime.GOARCH)
	}
}
//line internal/toolchain/toolchain.xgo:603:1
func latestXgoWindowsAsset(arch string) (tag string, asset string, err error) {
//line internal/toolchain/toolchain.xgo:604:1
	req, err := http.NewRequest("GET", "https://api.github.com/repos/goplus/xgo/releases/latest", nil)
//line internal/toolchain/toolchain.xgo:605:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:606:1
		return "", "", err
	}
//line internal/toolchain/toolchain.xgo:608:1
	req.Header.Set("Accept", "application/vnd.github+json")
//line internal/toolchain/toolchain.xgo:609:1
	req.Header.Set("User-Agent", "xgoup")
//line internal/toolchain/toolchain.xgo:610:1
	if
//line internal/toolchain/toolchain.xgo:610:1
	tok := os.Getenv("GITHUB_TOKEN"); tok != "" {
//line internal/toolchain/toolchain.xgo:611:1
		req.Header.Set("Authorization", "Bearer "+tok)
	}
//line internal/toolchain/toolchain.xgo:613:1
	client := &http.Client{Timeout: 30 * time.Second}
//line internal/toolchain/toolchain.xgo:614:1
	resp, err := client.Do(req)
//line internal/toolchain/toolchain.xgo:615:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:616:1
		return "", "", err
	}
//line internal/toolchain/toolchain.xgo:618:1
	defer resp.Body.Close()
//line internal/toolchain/toolchain.xgo:619:1
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
//line internal/toolchain/toolchain.xgo:620:1
		b, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
//line internal/toolchain/toolchain.xgo:621:1
		return "", "", fmt.Errorf("GET %s: status=%s body=%q", req.URL.String(), resp.Status, string(b))
	}
//line internal/toolchain/toolchain.xgo:623:1
	b, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
//line internal/toolchain/toolchain.xgo:624:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:625:1
		return "", "", err
	}
//line internal/toolchain/toolchain.xgo:627:1
	var v struct {
		Tag string `json:"tag_name"`
	}
//line internal/toolchain/toolchain.xgo:630:1
	if
//line internal/toolchain/toolchain.xgo:630:1
	err := json.Unmarshal(b, &v); err != nil {
//line internal/toolchain/toolchain.xgo:631:1
		return "", "", err
	}
//line internal/toolchain/toolchain.xgo:633:1
	if v.Tag == "" {
//line internal/toolchain/toolchain.xgo:634:1
		return "", "", errors.New("failed to resolve xgo latest release tag")
	}
//line internal/toolchain/toolchain.xgo:636:1
	ver := strings.TrimPrefix(v.Tag, "v")
//line internal/toolchain/toolchain.xgo:637:1
	return v.Tag, fmt.Sprintf("xgo%s.windows-%s.zip", ver, arch), nil
}
//line internal/toolchain/toolchain.xgo:640:1
func httpGetToFile(url string, path string) error {
//line internal/toolchain/toolchain.xgo:641:1
	req, err := http.NewRequest("GET", url, nil)
//line internal/toolchain/toolchain.xgo:642:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:643:1
		return err
	}
//line internal/toolchain/toolchain.xgo:645:1
	req.Header.Set("User-Agent", "xgoup")
//line internal/toolchain/toolchain.xgo:646:1
	req.Header.Set("Accept", "application/octet-stream")
//line internal/toolchain/toolchain.xgo:647:1
	client := &http.Client{Timeout: 120 * time.Second}
//line internal/toolchain/toolchain.xgo:648:1
	resp, err := client.Do(req)
//line internal/toolchain/toolchain.xgo:649:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:650:1
		return err
	}
//line internal/toolchain/toolchain.xgo:652:1
	defer resp.Body.Close()
//line internal/toolchain/toolchain.xgo:653:1
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
//line internal/toolchain/toolchain.xgo:654:1
		b, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
//line internal/toolchain/toolchain.xgo:655:1
		return fmt.Errorf("GET %s: status=%s body=%q", url, resp.Status, string(b))
	}
//line internal/toolchain/toolchain.xgo:657:1
	f, err := os.Create(path)
//line internal/toolchain/toolchain.xgo:658:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:659:1
		return err
	}
//line internal/toolchain/toolchain.xgo:661:1
	defer f.Close()
//line internal/toolchain/toolchain.xgo:662:1
	_, err = io.Copy(f, resp.Body)
//line internal/toolchain/toolchain.xgo:663:1
	return err
}
//line internal/toolchain/toolchain.xgo:666:1
func unzipAll(zipPath string, destDir string) error {
//line internal/toolchain/toolchain.xgo:667:1
	r, err := zip.OpenReader(zipPath)
//line internal/toolchain/toolchain.xgo:668:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:669:1
		return err
	}
//line internal/toolchain/toolchain.xgo:671:1
	defer r.Close()
//line internal/toolchain/toolchain.xgo:672:1
	if
//line internal/toolchain/toolchain.xgo:672:1
	err := os.MkdirAll(destDir, 0o755); err != nil {
//line internal/toolchain/toolchain.xgo:673:1
		return err
	}
	for
//line internal/toolchain/toolchain.xgo:675:1
	_, f := range r.File {
//line internal/toolchain/toolchain.xgo:676:1
		p := filepath.Join(destDir, filepath.FromSlash(f.Name))
//line internal/toolchain/toolchain.xgo:677:1
		if f.FileInfo().IsDir() {
//line internal/toolchain/toolchain.xgo:678:1
			if
//line internal/toolchain/toolchain.xgo:678:1
			err := os.MkdirAll(p, 0o755); err != nil {
//line internal/toolchain/toolchain.xgo:679:1
				return err
			}
//line internal/toolchain/toolchain.xgo:681:1
			continue
		}
//line internal/toolchain/toolchain.xgo:683:1
		if
//line internal/toolchain/toolchain.xgo:683:1
		err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
//line internal/toolchain/toolchain.xgo:684:1
			return err
		}
//line internal/toolchain/toolchain.xgo:686:1
		rc, err := f.Open()
//line internal/toolchain/toolchain.xgo:687:1
		if err != nil {
//line internal/toolchain/toolchain.xgo:688:1
			return err
		}
//line internal/toolchain/toolchain.xgo:690:1
		out, err := os.Create(p)
//line internal/toolchain/toolchain.xgo:691:1
		if err != nil {
//line internal/toolchain/toolchain.xgo:692:1
			rc.Close()
//line internal/toolchain/toolchain.xgo:693:1
			return err
		}
//line internal/toolchain/toolchain.xgo:695:1
		if
//line internal/toolchain/toolchain.xgo:695:1
		_, err := io.Copy(out, rc); err != nil {
//line internal/toolchain/toolchain.xgo:696:1
			out.Close()
//line internal/toolchain/toolchain.xgo:697:1
			rc.Close()
//line internal/toolchain/toolchain.xgo:698:1
			return err
		}
//line internal/toolchain/toolchain.xgo:700:1
		out.Close()
//line internal/toolchain/toolchain.xgo:701:1
		rc.Close()
	}
//line internal/toolchain/toolchain.xgo:703:1
	return nil
}
//line internal/toolchain/toolchain.xgo:706:1
func findXgoAndRoot(root string) (xgoExe string, xgoRoot string, err error) {
//line internal/toolchain/toolchain.xgo:707:1
	// locate xgo.exe
	var found string
//line internal/toolchain/toolchain.xgo:709:1
	err = filepath.WalkDir(root, func(p string, d os.DirEntry, err error) error {
//line internal/toolchain/toolchain.xgo:710:1
		if err != nil {
//line internal/toolchain/toolchain.xgo:711:1
			return err
		}
//line internal/toolchain/toolchain.xgo:713:1
		if d.IsDir() {
//line internal/toolchain/toolchain.xgo:714:1
			return nil
		}
//line internal/toolchain/toolchain.xgo:716:1
		if strings.EqualFold(d.Name(), "xgo.exe") {
//line internal/toolchain/toolchain.xgo:717:1
			found = p
//line internal/toolchain/toolchain.xgo:718:1
			return errFound
		}
//line internal/toolchain/toolchain.xgo:720:1
		return nil
	})
//line internal/toolchain/toolchain.xgo:722:1
	if err != nil && !errors.Is(err, errFound) {
//line internal/toolchain/toolchain.xgo:723:1
		return "", "", err
	}
//line internal/toolchain/toolchain.xgo:725:1
	if found == "" {
//line internal/toolchain/toolchain.xgo:726:1
		return "", "", errors.New("xgo.exe not found after extraction/build")
	}
//line internal/toolchain/toolchain.xgo:728:1
	binDir := filepath.Dir(found)
//line internal/toolchain/toolchain.xgo:729:1
	cand := binDir
//line internal/toolchain/toolchain.xgo:730:1
	if strings.EqualFold(filepath.Base(binDir), "bin") {
//line internal/toolchain/toolchain.xgo:731:1
		cand = filepath.Dir(binDir)
	}
//line internal/toolchain/toolchain.xgo:734:1
	isValid := func(d string) bool {
//line internal/toolchain/toolchain.xgo:735:1
		if d == "" {
//line internal/toolchain/toolchain.xgo:736:1
			return false
		}
//line internal/toolchain/toolchain.xgo:738:1
		if
//line internal/toolchain/toolchain.xgo:738:1
		_, err := os.Stat(filepath.Join(d, "bin", "xgo.exe")); err != nil {
//line internal/toolchain/toolchain.xgo:739:1
			return false
		}
//line internal/toolchain/toolchain.xgo:741:1
		if
//line internal/toolchain/toolchain.xgo:741:1
		_, err := os.Stat(filepath.Join(d, "pkg")); err == nil {
//line internal/toolchain/toolchain.xgo:742:1
			return true
		}
//line internal/toolchain/toolchain.xgo:744:1
		if
//line internal/toolchain/toolchain.xgo:744:1
		_, err := os.Stat(filepath.Join(d, "src")); err == nil {
//line internal/toolchain/toolchain.xgo:745:1
			return true
		}
//line internal/toolchain/toolchain.xgo:747:1
		if
//line internal/toolchain/toolchain.xgo:747:1
		_, err := os.Stat(filepath.Join(d, "all.bash")); err == nil {
//line internal/toolchain/toolchain.xgo:748:1
			return true
		}
//line internal/toolchain/toolchain.xgo:750:1
		return false
	}
//line internal/toolchain/toolchain.xgo:752:1
	for !isValid(cand) {
//line internal/toolchain/toolchain.xgo:753:1
		parent := filepath.Dir(cand)
//line internal/toolchain/toolchain.xgo:754:1
		if parent == cand {
//line internal/toolchain/toolchain.xgo:755:1
			break
		}
//line internal/toolchain/toolchain.xgo:757:1
		cand = parent
	}
//line internal/toolchain/toolchain.xgo:759:1
	if !isValid(cand) {
//line internal/toolchain/toolchain.xgo:760:1
		return found, cand, fmt.Errorf("XGOROOT (%s) is not valid", cand)
	}
//line internal/toolchain/toolchain.xgo:762:1
	return found, cand, nil
}

var errFound = errors.New("found")
//line internal/toolchain/toolchain.xgo:767:1
func detectVersionFromXgo(xgoExe string, xgoRoot string) string {
//line internal/toolchain/toolchain.xgo:770:1
	cmd := exec.Command(xgoExe, "version")
//line internal/toolchain/toolchain.xgo:790:1
	cmd.Env = envForXgoCLI(xgoRoot)
//line internal/toolchain/toolchain.xgo:772:1
	out, _ := cmd.CombinedOutput()
//line internal/toolchain/toolchain.xgo:773:1
	s := strings.TrimSpace(string(out))
//line internal/toolchain/toolchain.xgo:774:1
	if s == "" {
//line internal/toolchain/toolchain.xgo:775:1
		return ""
	}
//line internal/toolchain/toolchain.xgo:777:1
	parts := strings.Fields(s)
//line internal/toolchain/toolchain.xgo:778:1
	if len(parts) == 0 {
//line internal/toolchain/toolchain.xgo:779:1
		return ""
	}
//line internal/toolchain/toolchain.xgo:781:1
	return strings.Join(parts, " ")
}
//line internal/toolchain/toolchain.xgo:784:1
// envForXgoCLI returns process env without a bogus XGOROOT, then sets XGOROOT when known.
func envForXgoCLI(xgoRoot string) []string {
//line internal/toolchain/toolchain.xgo:786:1
	out := stripXGOROOTFromEnviron()
//line internal/toolchain/toolchain.xgo:787:1
	if xgoRoot != "" {
//line internal/toolchain/toolchain.xgo:788:1
		out = append(out, "XGOROOT="+xgoRoot)
	}
//line internal/toolchain/toolchain.xgo:790:1
	return out
}
//line internal/toolchain/toolchain.xgo:793:1
func stripXGOROOTFromEnviron() []string {
//line internal/toolchain/toolchain.xgo:794:1
	var out []string
	for
//line internal/toolchain/toolchain.xgo:795:1
	_, e := range os.Environ() {
//line internal/toolchain/toolchain.xgo:796:1
		if strings.HasPrefix(strings.ToUpper(e), "XGOROOT=") {
//line internal/toolchain/toolchain.xgo:797:1
			continue
		}
//line internal/toolchain/toolchain.xgo:799:1
		out = append(out, e)
	}
//line internal/toolchain/toolchain.xgo:801:1
	return out
}
//line internal/toolchain/toolchain.xgo:230:1
func installLinked(p home.Paths, c config.Config, name string, opt InstallOptions) (config.Config, error) {
//line internal/toolchain/toolchain.xgo:231:1
	if opt.Path == "" {
//line internal/toolchain/toolchain.xgo:232:1
		return config.Config{}, errors.New("linked method requires --path")
	}
//line internal/toolchain/toolchain.xgo:234:1
	abs, err := filepath.Abs(opt.Path)
//line internal/toolchain/toolchain.xgo:235:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:236:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:238:1
	xgo := filepath.Join(abs, "bin", "xgo.exe")
//line internal/toolchain/toolchain.xgo:239:1
	if
//line internal/toolchain/toolchain.xgo:239:1
	_, err := os.Stat(xgo); err != nil {
//line internal/toolchain/toolchain.xgo:240:1
		return config.Config{}, fmt.Errorf("linked path missing xgo: %s", xgo)
	}
//line internal/toolchain/toolchain.xgo:242:1
	if
//line internal/toolchain/toolchain.xgo:242:1
	_, err := os.Stat(meta.FilePath(p.Metadata, name)); err == nil && !opt.Force {
//line internal/toolchain/toolchain.xgo:243:1
		return config.Config{}, fmt.Errorf("toolchain already exists: %s (use --force)", name)
	}
//line internal/toolchain/toolchain.xgo:245:1
	m := meta.ToolchainMeta{Name: name, Kind: "linked", RootPath: abs, XgoBin: xgo, XgoRootValue: abs, Managed: "false", Version: detectVersionFromXgo(xgo, abs)}
//line internal/toolchain/toolchain.xgo:254:1
	if
//line internal/toolchain/toolchain.xgo:254:1
	err := meta.Save(p.Metadata, name, m); err != nil {
//line internal/toolchain/toolchain.xgo:255:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:257:1
	c.Toolchains[name] = config.Toolchain{Kind: "linked", Path: abs, Managed: false, Version: m.Version}
//line internal/toolchain/toolchain.xgo:258:1
	if c.DefaultToolchain == "" {
//line internal/toolchain/toolchain.xgo:259:1
		c.DefaultToolchain = name
	}
//line internal/toolchain/toolchain.xgo:261:1
	if
//line internal/toolchain/toolchain.xgo:261:1
	err := SaveConfig(p, c); err != nil {
//line internal/toolchain/toolchain.xgo:262:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:264:1
	return c, nil
}
//line internal/toolchain/toolchain.xgo:332:1
func installSource(p home.Paths, c config.Config, name string, opt InstallOptions) (config.Config, error) {
//line internal/toolchain/toolchain.xgo:333:1
	repo := opt.Repo
//line internal/toolchain/toolchain.xgo:334:1
	if repo == "" {
//line internal/toolchain/toolchain.xgo:335:1
		repo = DefaultSourceRepo
	}
//line internal/toolchain/toolchain.xgo:337:1
	if
//line internal/toolchain/toolchain.xgo:337:1
	_, err := os.Stat(meta.FilePath(p.Metadata, name)); err == nil && !opt.Force {
//line internal/toolchain/toolchain.xgo:338:1
		return config.Config{}, fmt.Errorf("toolchain already exists: %s (use --force)", name)
	}
//line internal/toolchain/toolchain.xgo:340:1
	if
//line internal/toolchain/toolchain.xgo:340:1
	_, err := exec.LookPath("git"); err != nil {
//line internal/toolchain/toolchain.xgo:341:1
		return config.Config{}, errors.New("missing required command: git")
	}
//line internal/toolchain/toolchain.xgo:343:1
	bash, err := findBash()
//line internal/toolchain/toolchain.xgo:344:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:345:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:348:1
	target := filepath.Join(p.Toolchains, name)
//line internal/toolchain/toolchain.xgo:349:1
	if opt.Force {
//line internal/toolchain/toolchain.xgo:350:1
		_ = os.RemoveAll(target)
	}
//line internal/toolchain/toolchain.xgo:353:1
	if
//line internal/toolchain/toolchain.xgo:353:1
	err := execCmd("", "git", "clone", repo, target); err != nil {
//line internal/toolchain/toolchain.xgo:354:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:356:1
	if opt.Ref != "" {
//line internal/toolchain/toolchain.xgo:357:1
		if
//line internal/toolchain/toolchain.xgo:357:1
		err := execCmd("", "git", "-C", target, "checkout", opt.Ref); err != nil {
//line internal/toolchain/toolchain.xgo:358:1
			return config.Config{}, err
		}
	}
//line internal/toolchain/toolchain.xgo:363:1
	if
//line internal/toolchain/toolchain.xgo:363:1
	err := execCmd(target, bash, "-lc", "./all.bash"); err != nil {
//line internal/toolchain/toolchain.xgo:364:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:367:1
	xgoExe, xgoroot, err := findXgoAndRoot(target)
//line internal/toolchain/toolchain.xgo:368:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:369:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:372:1
	commit := ""
//line internal/toolchain/toolchain.xgo:373:1
	if
//line internal/toolchain/toolchain.xgo:373:1
	out, err := exec.Command("git", "-C", target, "rev-parse", "HEAD").CombinedOutput(); err == nil {
//line internal/toolchain/toolchain.xgo:374:1
		commit = strings.TrimSpace(string(out))
	}
//line internal/toolchain/toolchain.xgo:377:1
	m := meta.ToolchainMeta{Name: name, Kind: "source", RootPath: xgoroot, XgoBin: xgoExe, XgoRootValue: xgoroot, Managed: "true", Repo: repo, Ref: opt.Ref, Commit: commit, Version: detectVersionFromXgo(xgoExe, xgoroot)}
//line internal/toolchain/toolchain.xgo:389:1
	if
//line internal/toolchain/toolchain.xgo:389:1
	err := meta.Save(p.Metadata, name, m); err != nil {
//line internal/toolchain/toolchain.xgo:390:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:392:1
	c.Toolchains[name] = config.Toolchain{Kind: "source", Path: xgoroot, Managed: true, Version: m.Version, Repo: repo, Ref: opt.Ref, Commit: commit}
//line internal/toolchain/toolchain.xgo:393:1
	if c.DefaultToolchain == "" {
//line internal/toolchain/toolchain.xgo:394:1
		c.DefaultToolchain = name
	}
//line internal/toolchain/toolchain.xgo:396:1
	if
//line internal/toolchain/toolchain.xgo:396:1
	err := SaveConfig(p, c); err != nil {
//line internal/toolchain/toolchain.xgo:397:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:399:1
	return c, nil
}
//line internal/toolchain/toolchain.xgo:804:1
func findBash() (string, error) {
//line internal/toolchain/toolchain.xgo:805:1
	if
//line internal/toolchain/toolchain.xgo:805:1
	p, err := exec.LookPath("bash.exe"); err == nil {
//line internal/toolchain/toolchain.xgo:806:1
		return p, nil
	}
//line internal/toolchain/toolchain.xgo:808:1
	if
//line internal/toolchain/toolchain.xgo:808:1
	p, err := exec.LookPath("bash"); err == nil {
//line internal/toolchain/toolchain.xgo:809:1
		return p, nil
	}
//line internal/toolchain/toolchain.xgo:812:1
	common := []string{filepath.Join(os.Getenv("ProgramFiles"), "Git", "bin", "bash.exe"), filepath.Join(os.Getenv("ProgramFiles(x86)"), "Git", "bin", "bash.exe")}
	for
//line internal/toolchain/toolchain.xgo:816:1
	_, p := range common {
//line internal/toolchain/toolchain.xgo:817:1
		if p == "" {
//line internal/toolchain/toolchain.xgo:818:1
			continue
		}
//line internal/toolchain/toolchain.xgo:820:1
		if
//line internal/toolchain/toolchain.xgo:820:1
		_, err := os.Stat(p); err == nil {
//line internal/toolchain/toolchain.xgo:821:1
			return p, nil
		}
	}
//line internal/toolchain/toolchain.xgo:824:1
	return "", errors.New("bash.exe not found; install Git for Windows (Git-Bash) or MSYS2 and ensure bash is on PATH")
}
//line internal/toolchain/toolchain.xgo:827:1
func execCmd(dir string, exe string, args ...string) error {
//line internal/toolchain/toolchain.xgo:828:1
	cmd := exec.Command(exe, args...) 
//line internal/toolchain/toolchain.xgo:829:1
	if dir != "" {
//line internal/toolchain/toolchain.xgo:830:1
		cmd.Dir = dir
	}
//line internal/toolchain/toolchain.xgo:832:1
	cmd.Env = stripXGOROOTFromEnviron()
//line internal/toolchain/toolchain.xgo:833:1
	cmd.Stdout = os.Stdout
//line internal/toolchain/toolchain.xgo:834:1
	cmd.Stderr = os.Stderr
//line internal/toolchain/toolchain.xgo:835:1
	return cmd.Run()
}
//line internal/toolchain/toolchain.xgo:184:1
func Update(p home.Paths, c config.Config, name string) (config.Config, error) {
//line internal/toolchain/toolchain.xgo:185:1
	if name == "" {
//line internal/toolchain/toolchain.xgo:186:1
		name = c.DefaultToolchain
	}
//line internal/toolchain/toolchain.xgo:188:1
	if name == "" {
//line internal/toolchain/toolchain.xgo:189:1
		return config.Config{}, errors.New("no toolchain specified and no default configured")
	}
//line internal/toolchain/toolchain.xgo:191:1
	tc, ok := c.Toolchains[name]
//line internal/toolchain/toolchain.xgo:192:1
	if !ok {
//line internal/toolchain/toolchain.xgo:193:1
		return config.Config{}, fmt.Errorf("toolchain not found: %s", name)
	}
//line internal/toolchain/toolchain.xgo:195:1
	switch tc.Kind {
//line internal/toolchain/toolchain.xgo:196:1
	case "standard":
//line internal/toolchain/toolchain.xgo:197:1
		return installStandard(p, c, name, InstallOptions{Method: "standard", Force: true})
//line internal/toolchain/toolchain.xgo:198:1
	case "source":
//line internal/toolchain/toolchain.xgo:442:1
		return installSourceUpdate(p, c, name)
//line internal/toolchain/toolchain.xgo:200:1
	case "linked":
//line internal/toolchain/toolchain.xgo:201:1
		return c, fmt.Errorf("linked toolchain update is a no-op: %s", name)
//line internal/toolchain/toolchain.xgo:202:1
	default:
//line internal/toolchain/toolchain.xgo:203:1
		return config.Config{}, fmt.Errorf("unknown toolchain kind: %s", tc.Kind)
	}
}
//line internal/toolchain/toolchain.xgo:402:1
func installSourceUpdate(p home.Paths, c config.Config, name string) (config.Config, error) {
//line internal/toolchain/toolchain.xgo:403:1
	tc := c.Toolchains[name]
//line internal/toolchain/toolchain.xgo:404:1
	if tc.Path == "" {
//line internal/toolchain/toolchain.xgo:405:1
		return config.Config{}, errors.New("source toolchain missing path")
	}
//line internal/toolchain/toolchain.xgo:407:1
	if
//line internal/toolchain/toolchain.xgo:407:1
	_, err := exec.LookPath("git"); err != nil {
//line internal/toolchain/toolchain.xgo:408:1
		return config.Config{}, errors.New("missing required command: git")
	}
//line internal/toolchain/toolchain.xgo:410:1
	bash, err := findBash()
//line internal/toolchain/toolchain.xgo:411:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:412:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:415:1
	_ = execCmd("", "git", "-C", tc.Path, "fetch", "--tags", "--prune")
//line internal/toolchain/toolchain.xgo:416:1
	_ = execCmd("", "git", "-C", tc.Path, "pull", "--ff-only")
//line internal/toolchain/toolchain.xgo:417:1
	if
//line internal/toolchain/toolchain.xgo:417:1
	err := execCmd(tc.Path, bash, "-lc", "./all.bash"); err != nil {
//line internal/toolchain/toolchain.xgo:418:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:420:1
	xgoExe, xgoroot, err := findXgoAndRoot(tc.Path)
//line internal/toolchain/toolchain.xgo:421:1
	if err != nil {
//line internal/toolchain/toolchain.xgo:422:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:424:1
	m, _ := meta.Load(p.Metadata, name)
//line internal/toolchain/toolchain.xgo:425:1
	m.RootPath = xgoroot
//line internal/toolchain/toolchain.xgo:426:1
	m.XgoBin = xgoExe
//line internal/toolchain/toolchain.xgo:427:1
	m.XgoRootValue = xgoroot
//line internal/toolchain/toolchain.xgo:428:1
	m.Version = detectVersionFromXgo(xgoExe, xgoroot)
//line internal/toolchain/toolchain.xgo:429:1
	if
//line internal/toolchain/toolchain.xgo:429:1
	out, err := exec.Command("git", "-C", tc.Path, "rev-parse", "HEAD").CombinedOutput(); err == nil {
//line internal/toolchain/toolchain.xgo:430:1
		m.Commit = strings.TrimSpace(string(out))
	}
//line internal/toolchain/toolchain.xgo:432:1
	if
//line internal/toolchain/toolchain.xgo:432:1
	err := meta.Save(p.Metadata, name, m); err != nil {
//line internal/toolchain/toolchain.xgo:433:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:435:1
	tc.Path = xgoroot
//line internal/toolchain/toolchain.xgo:436:1
	tc.Version = m.Version
//line internal/toolchain/toolchain.xgo:437:1
	tc.Commit = m.Commit
//line internal/toolchain/toolchain.xgo:438:1
	c.Toolchains[name] = tc
//line internal/toolchain/toolchain.xgo:439:1
	if
//line internal/toolchain/toolchain.xgo:439:1
	err := SaveConfig(p, c); err != nil {
//line internal/toolchain/toolchain.xgo:440:1
		return config.Config{}, err
	}
//line internal/toolchain/toolchain.xgo:442:1
	return c, nil
}
//line internal/toolchain/toolchain.xgo:207:1
func Doctor(p home.Paths, c config.Config) error {
//line internal/toolchain/toolchain.xgo:209:1
	if
//line internal/toolchain/toolchain.xgo:209:1
	err := config.Validate(c); err != nil {
//line internal/toolchain/toolchain.xgo:210:1
		return err
	}
//line internal/toolchain/toolchain.xgo:213:1
	names, _ := meta.Names(p.Metadata)
	for
//line internal/toolchain/toolchain.xgo:214:1
	_, n := range names {
//line internal/toolchain/toolchain.xgo:215:1
		m, err := meta.Load(p.Metadata, n)
//line internal/toolchain/toolchain.xgo:216:1
		if err != nil {
//line internal/toolchain/toolchain.xgo:217:1
			return fmt.Errorf("metadata load failed for %s: %w", n, err)
		}
//line internal/toolchain/toolchain.xgo:219:1
		if m.XgoBin != "" {
//line internal/toolchain/toolchain.xgo:220:1
			if
//line internal/toolchain/toolchain.xgo:220:1
			_, err := os.Stat(m.XgoBin); err != nil {
//line internal/toolchain/toolchain.xgo:221:1
				return fmt.Errorf("xgo missing for %s: %s", n, m.XgoBin)
			}
		}
	}
//line internal/toolchain/toolchain.xgo:225:1
	return nil
}
