// Code generated by xgo (XGo); DO NOT EDIT.

package bootstrap

import (
	"archive/tar"
	"archive/zip"
	"compress/gzip"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

const _ = true
// Options configures a self-install from release assets or a local archive.
type Options struct {
	Repo       string
	Version    string
	ZipPath    string
	ModifyPath bool
	Logf       func(format string, args ...interface{})
}
//line internal/bootstrap/bootstrap.xgo:30:1
func logf(o Options, format string, args ...interface{}) {
//line internal/bootstrap/bootstrap.xgo:31:1
	if o.Logf != nil {
//line internal/bootstrap/bootstrap.xgo:32:1
		o.Logf(format, args...)
	}
}
//line internal/bootstrap/bootstrap.xgo:36:1
// Install downloads (or uses --zip) the release payload for this OS/arch and
// installs xgoup into ~/.xgoup/bin, then optionally updates user PATH.
func Install(o Options) error {
//line internal/bootstrap/bootstrap.xgo:39:1
	if o.Repo == "" {
//line internal/bootstrap/bootstrap.xgo:40:1
		o.Repo = "fanfeilong/xgoup"
	}
//line internal/bootstrap/bootstrap.xgo:42:1
	if o.Version == "" {
//line internal/bootstrap/bootstrap.xgo:43:1
		o.Version = "latest"
	}
//line internal/bootstrap/bootstrap.xgo:45:1
	home := defaultHome()
//line internal/bootstrap/bootstrap.xgo:46:1
	binDir := filepath.Join(home, "bin")
//line internal/bootstrap/bootstrap.xgo:47:1
	if
//line internal/bootstrap/bootstrap.xgo:47:1
	err := os.MkdirAll(binDir, 0o755); err != nil {
//line internal/bootstrap/bootstrap.xgo:48:1
		return err
	}
//line internal/bootstrap/bootstrap.xgo:51:1
	switch runtime.GOOS {
//line internal/bootstrap/bootstrap.xgo:52:1
	case "windows":
//line internal/bootstrap/bootstrap.xgo:141:1
		return installWindows(binDir, o)
//line internal/bootstrap/bootstrap.xgo:54:1
	case "darwin", "linux":
//line internal/bootstrap/bootstrap.xgo:200:1
		return installUnix(binDir, o)
//line internal/bootstrap/bootstrap.xgo:56:1
	default:
//line internal/bootstrap/bootstrap.xgo:57:1
		return fmt.Errorf("self install: unsupported GOOS %s", runtime.GOOS)
	}
}
//line internal/bootstrap/bootstrap.xgo:61:1
func defaultHome() string {
//line internal/bootstrap/bootstrap.xgo:62:1
	if
//line internal/bootstrap/bootstrap.xgo:62:1
	h := os.Getenv("XGOUP_HOME"); h != "" {
//line internal/bootstrap/bootstrap.xgo:63:1
		return h
	}
//line internal/bootstrap/bootstrap.xgo:65:1
	if runtime.GOOS == "windows" {
//line internal/bootstrap/bootstrap.xgo:66:1
		up := os.Getenv("USERPROFILE")
//line internal/bootstrap/bootstrap.xgo:67:1
		if up == "" {
//line internal/bootstrap/bootstrap.xgo:68:1
			return filepath.Join(os.TempDir(), ".xgoup")
		}
//line internal/bootstrap/bootstrap.xgo:70:1
		return filepath.Join(up, ".xgoup")
	}
//line internal/bootstrap/bootstrap.xgo:72:1
	h, err := os.UserHomeDir()
//line internal/bootstrap/bootstrap.xgo:73:1
	if err != nil {
//line internal/bootstrap/bootstrap.xgo:74:1
		return filepath.Join(os.TempDir(), ".xgoup")
	}
//line internal/bootstrap/bootstrap.xgo:76:1
	return filepath.Join(h, ".xgoup")
}
//line internal/bootstrap/bootstrap.xgo:79:1
func installWindows(binDir string, o Options) error {
//line internal/bootstrap/bootstrap.xgo:80:1
	arch, err := detectArch()
//line internal/bootstrap/bootstrap.xgo:81:1
	if err != nil {
//line internal/bootstrap/bootstrap.xgo:82:1
		return err
	}
//line internal/bootstrap/bootstrap.xgo:84:1
	tryURLs := buildTryURLs(o.Repo, o.Version, arch, "windows")
//line internal/bootstrap/bootstrap.xgo:86:1
	tmp := filepath.Join(os.TempDir(), fmt.Sprintf("xgoup-%d.zip", time.Now().UnixNano()))
//line internal/bootstrap/bootstrap.xgo:87:1
	var lastErr error
//line internal/bootstrap/bootstrap.xgo:88:1
	zipPath := o.ZipPath
//line internal/bootstrap/bootstrap.xgo:89:1
	if zipPath != "" {
//line internal/bootstrap/bootstrap.xgo:90:1
		if
//line internal/bootstrap/bootstrap.xgo:90:1
		_, err := os.Stat(zipPath); err != nil {
//line internal/bootstrap/bootstrap.xgo:91:1
			return err
		}
//line internal/bootstrap/bootstrap.xgo:93:1
		tmp = zipPath
	} else {
//line internal/bootstrap/bootstrap.xgo:95:1
		defer func() {
//line internal/bootstrap/bootstrap.xgo:95:1
			_ = os.Remove(tmp)
		}()
		for
//line internal/bootstrap/bootstrap.xgo:96:1
		_, u := range tryURLs {
//line internal/bootstrap/bootstrap.xgo:97:1
			logf(o, "[xgoup] download: %s", u)
//line internal/bootstrap/bootstrap.xgo:98:1
			if
//line internal/bootstrap/bootstrap.xgo:98:1
			err := httpGetToFile(u, tmp); err != nil {
//line internal/bootstrap/bootstrap.xgo:99:1
				lastErr = err
//line internal/bootstrap/bootstrap.xgo:100:1
				logf(o, "[xgoup] download failed: %v", err)
//line internal/bootstrap/bootstrap.xgo:101:1
				continue
			}
//line internal/bootstrap/bootstrap.xgo:103:1
			lastErr = nil
//line internal/bootstrap/bootstrap.xgo:104:1
			break
		}
//line internal/bootstrap/bootstrap.xgo:106:1
		if lastErr != nil {
//line internal/bootstrap/bootstrap.xgo:107:1
			return lastErr
		}
	}
//line internal/bootstrap/bootstrap.xgo:111:1
	want := map[string]bool{"xgoup.exe": true}
//line internal/bootstrap/bootstrap.xgo:112:1
	if
//line internal/bootstrap/bootstrap.xgo:112:1
	err := unzipSelected(tmp, binDir, want); err != nil {
//line internal/bootstrap/bootstrap.xgo:113:1
		return fmt.Errorf("unzip: %w", err)
	}
//line internal/bootstrap/bootstrap.xgo:115:1
	logf(o, "[xgoup] installed: %s", binDir)
	for
//line internal/bootstrap/bootstrap.xgo:117:1
	_, legacy := range []string{"xgoup.ps1", "xgoup.cmd"} {
//line internal/bootstrap/bootstrap.xgo:118:1
		p := filepath.Join(binDir, legacy)
//line internal/bootstrap/bootstrap.xgo:119:1
		if
//line internal/bootstrap/bootstrap.xgo:119:1
		err := os.Remove(p); err == nil {
//line internal/bootstrap/bootstrap.xgo:120:1
			logf(o, "[xgoup] removed legacy: %s", p)
		}
	}
//line internal/bootstrap/bootstrap.xgo:124:1
	if o.ModifyPath {
//line internal/bootstrap/bootstrap.xgo:125:1
		if
//line internal/bootstrap/bootstrap.xgo:125:1
		err := addToUserPathWindows(binDir); err != nil {
//line internal/bootstrap/bootstrap.xgo:126:1
			logf(o, "[xgoup] PATH update skipped/failed: %v", err)
		} else {
//line internal/bootstrap/bootstrap.xgo:128:1
			logf(o, "[xgoup] updated user PATH")
		}
	}
//line internal/bootstrap/bootstrap.xgo:132:1
	cmdPath := filepath.Join(binDir, "xgoup.exe")
//line internal/bootstrap/bootstrap.xgo:133:1
	logf(o, "[xgoup] try: %s --version", cmdPath)
//line internal/bootstrap/bootstrap.xgo:134:1
	out, err := exec.Command(cmdPath, "--version").CombinedOutput()
//line internal/bootstrap/bootstrap.xgo:135:1
	if
//line internal/bootstrap/bootstrap.xgo:135:1
	text := strings.TrimSpace(string(out)); text != "" {
//line internal/bootstrap/bootstrap.xgo:136:1
		fmt.Println(text)
	}
//line internal/bootstrap/bootstrap.xgo:138:1
	if err != nil {
//line internal/bootstrap/bootstrap.xgo:139:1
		logf(o, "[xgoup] xgoup exit: %v", err)
	}
//line internal/bootstrap/bootstrap.xgo:141:1
	return nil
}
//line internal/bootstrap/bootstrap.xgo:230:1
func detectArch() (string, error) {
//line internal/bootstrap/bootstrap.xgo:231:1
	switch runtime.GOARCH {
//line internal/bootstrap/bootstrap.xgo:232:1
	case "amd64":
//line internal/bootstrap/bootstrap.xgo:233:1
		return "amd64", nil
//line internal/bootstrap/bootstrap.xgo:234:1
	case "arm64":
//line internal/bootstrap/bootstrap.xgo:235:1
		return "arm64", nil
//line internal/bootstrap/bootstrap.xgo:236:1
	default:
//line internal/bootstrap/bootstrap.xgo:237:1
		return "", fmt.Errorf("unsupported arch: %s", runtime.GOARCH)
	}
}
//line internal/bootstrap/bootstrap.xgo:203:1
func buildTryURLs(repo string, version string, arch string, goos string) []string {
//line internal/bootstrap/bootstrap.xgo:204:1
	var try []string
//line internal/bootstrap/bootstrap.xgo:205:1
	if version != "" && version != "latest" {
//line internal/bootstrap/bootstrap.xgo:206:1
		try = append(try, fmt.Sprintf("https://github.com/%s/releases/download/%s/xgoup-%s-windows-%s.zip", repo, version, version, arch))
	}
//line internal/bootstrap/bootstrap.xgo:208:1
	try = append(try, fmt.Sprintf("https://github.com/%s/releases/latest/download/xgoup-windows-%s.zip", repo, arch))
//line internal/bootstrap/bootstrap.xgo:209:1
	if version == "latest" {
//line internal/bootstrap/bootstrap.xgo:210:1
		if
//line internal/bootstrap/bootstrap.xgo:210:1
		tag, err := getLatestReleaseTag(repo); err == nil {
//line internal/bootstrap/bootstrap.xgo:211:1
			try = append(try, fmt.Sprintf("https://github.com/%s/releases/download/%s/xgoup-%s-windows-%s.zip", repo, tag, tag, arch))
		}
	}
//line internal/bootstrap/bootstrap.xgo:214:1
	return try
}
//line internal/bootstrap/bootstrap.xgo:241:1
func getLatestReleaseTag(repo string) (string, error) {
//line internal/bootstrap/bootstrap.xgo:242:1
	req, err := http.NewRequest("GET", fmt.Sprintf("https://api.github.com/repos/%s/releases/latest", repo), nil)
//line internal/bootstrap/bootstrap.xgo:243:1
	if err != nil {
//line internal/bootstrap/bootstrap.xgo:244:1
		return "", err
	}
//line internal/bootstrap/bootstrap.xgo:246:1
	req.Header.Set("Accept", "application/vnd.github+json")
//line internal/bootstrap/bootstrap.xgo:247:1
	req.Header.Set("User-Agent", "xgoup")
//line internal/bootstrap/bootstrap.xgo:248:1
	if
//line internal/bootstrap/bootstrap.xgo:248:1
	tok := os.Getenv("GITHUB_TOKEN"); tok != "" {
//line internal/bootstrap/bootstrap.xgo:249:1
		req.Header.Set("Authorization", "Bearer "+tok)
	}
//line internal/bootstrap/bootstrap.xgo:251:1
	client := &http.Client{Timeout: 30 * time.Second}
//line internal/bootstrap/bootstrap.xgo:252:1
	resp, err := client.Do(req)
//line internal/bootstrap/bootstrap.xgo:253:1
	if err != nil {
//line internal/bootstrap/bootstrap.xgo:254:1
		return "", err
	}
//line internal/bootstrap/bootstrap.xgo:256:1
	defer resp.Body.Close()
//line internal/bootstrap/bootstrap.xgo:257:1
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
//line internal/bootstrap/bootstrap.xgo:258:1
		b, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
//line internal/bootstrap/bootstrap.xgo:259:1
		return "", fmt.Errorf("GET %s: status=%s body=%q", req.URL.String(), resp.Status, string(b))
	}
//line internal/bootstrap/bootstrap.xgo:261:1
	b, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
//line internal/bootstrap/bootstrap.xgo:262:1
	if err != nil {
//line internal/bootstrap/bootstrap.xgo:263:1
		return "", err
	}
//line internal/bootstrap/bootstrap.xgo:265:1
	var v struct {
		Tag string `json:"tag_name"`
	}
//line internal/bootstrap/bootstrap.xgo:268:1
	if
//line internal/bootstrap/bootstrap.xgo:268:1
	err := json.Unmarshal(b, &v); err != nil {
//line internal/bootstrap/bootstrap.xgo:269:1
		return "", err
	}
//line internal/bootstrap/bootstrap.xgo:271:1
	if v.Tag == "" {
//line internal/bootstrap/bootstrap.xgo:272:1
		return "", errors.New("empty tag_name")
	}
//line internal/bootstrap/bootstrap.xgo:274:1
	return v.Tag, nil
}
//line internal/bootstrap/bootstrap.xgo:277:1
func httpGetToFile(url string, path string) error {
//line internal/bootstrap/bootstrap.xgo:278:1
	req, err := http.NewRequest("GET", url, nil)
//line internal/bootstrap/bootstrap.xgo:279:1
	if err != nil {
//line internal/bootstrap/bootstrap.xgo:280:1
		return err
	}
//line internal/bootstrap/bootstrap.xgo:282:1
	req.Header.Set("User-Agent", "xgoup")
//line internal/bootstrap/bootstrap.xgo:283:1
	req.Header.Set("Accept", "application/octet-stream")
//line internal/bootstrap/bootstrap.xgo:284:1
	client := &http.Client{Timeout: 120 * time.Second}
//line internal/bootstrap/bootstrap.xgo:285:1
	resp, err := client.Do(req)
//line internal/bootstrap/bootstrap.xgo:286:1
	if err != nil {
//line internal/bootstrap/bootstrap.xgo:287:1
		return err
	}
//line internal/bootstrap/bootstrap.xgo:289:1
	defer resp.Body.Close()
//line internal/bootstrap/bootstrap.xgo:290:1
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
//line internal/bootstrap/bootstrap.xgo:291:1
		b, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
//line internal/bootstrap/bootstrap.xgo:292:1
		return fmt.Errorf("GET %s: status=%s body=%q", url, resp.Status, string(b))
	}
//line internal/bootstrap/bootstrap.xgo:294:1
	f, err := os.Create(path)
//line internal/bootstrap/bootstrap.xgo:295:1
	if err != nil {
//line internal/bootstrap/bootstrap.xgo:296:1
		return err
	}
//line internal/bootstrap/bootstrap.xgo:298:1
	defer f.Close()
//line internal/bootstrap/bootstrap.xgo:299:1
	_, err = io.Copy(f, resp.Body)
//line internal/bootstrap/bootstrap.xgo:300:1
	return err
}
//line internal/bootstrap/bootstrap.xgo:303:1
func unzipSelected(zipPath string, destDir string, want map[string]bool) error {
//line internal/bootstrap/bootstrap.xgo:304:1
	r, err := zip.OpenReader(zipPath)
//line internal/bootstrap/bootstrap.xgo:305:1
	if err != nil {
//line internal/bootstrap/bootstrap.xgo:306:1
		return err
	}
//line internal/bootstrap/bootstrap.xgo:308:1
	defer r.Close()
//line internal/bootstrap/bootstrap.xgo:309:1
	if
//line internal/bootstrap/bootstrap.xgo:309:1
	err := os.MkdirAll(destDir, 0o755); err != nil {
//line internal/bootstrap/bootstrap.xgo:310:1
		return err
	}
//line internal/bootstrap/bootstrap.xgo:312:1
	found := map[string]bool{}
	for
//line internal/bootstrap/bootstrap.xgo:313:1
	_, f := range r.File {
//line internal/bootstrap/bootstrap.xgo:314:1
		name := filepath.Base(strings.ReplaceAll(f.Name, "\\", "/"))
//line internal/bootstrap/bootstrap.xgo:315:1
		if !want[name] {
//line internal/bootstrap/bootstrap.xgo:316:1
			continue
		}
//line internal/bootstrap/bootstrap.xgo:318:1
		rc, err := f.Open()
//line internal/bootstrap/bootstrap.xgo:319:1
		if err != nil {
//line internal/bootstrap/bootstrap.xgo:320:1
			return err
		}
//line internal/bootstrap/bootstrap.xgo:322:1
		outPath := filepath.Join(destDir, name)
//line internal/bootstrap/bootstrap.xgo:323:1
		out, err := os.Create(outPath)
//line internal/bootstrap/bootstrap.xgo:324:1
		if err != nil {
//line internal/bootstrap/bootstrap.xgo:325:1
			rc.Close()
//line internal/bootstrap/bootstrap.xgo:326:1
			return err
		}
//line internal/bootstrap/bootstrap.xgo:328:1
		if
//line internal/bootstrap/bootstrap.xgo:328:1
		_, err := io.Copy(out, rc); err != nil {
//line internal/bootstrap/bootstrap.xgo:329:1
			out.Close()
//line internal/bootstrap/bootstrap.xgo:330:1
			rc.Close()
//line internal/bootstrap/bootstrap.xgo:331:1
			return err
		}
//line internal/bootstrap/bootstrap.xgo:333:1
		out.Close()
//line internal/bootstrap/bootstrap.xgo:334:1
		rc.Close()
//line internal/bootstrap/bootstrap.xgo:335:1
		found[name] = true
	}
	for
//line internal/bootstrap/bootstrap.xgo:337:1
	k := range want {
//line internal/bootstrap/bootstrap.xgo:338:1
		if !found[k] {
//line internal/bootstrap/bootstrap.xgo:339:1
			return fmt.Errorf("missing %q in zip", k)
		}
	}
//line internal/bootstrap/bootstrap.xgo:342:1
	return nil
}
//line internal/bootstrap/bootstrap.xgo:385:1
func addToUserPathWindows(binDir string) error {
//line internal/bootstrap/bootstrap.xgo:386:1
	ps := fmt.Sprintf(`[Environment]::SetEnvironmentVariable("Path", (([Environment]::GetEnvironmentVariable("Path","User") + ";%s").Trim(";")), "User")`, strings.ReplaceAll(binDir, `"`, `""`))
//line internal/bootstrap/bootstrap.xgo:387:1
	cmd := exec.Command("powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", ps)
//line internal/bootstrap/bootstrap.xgo:388:1
	out, err := cmd.CombinedOutput()
//line internal/bootstrap/bootstrap.xgo:389:1
	if err != nil {
//line internal/bootstrap/bootstrap.xgo:390:1
		return fmt.Errorf("powershell PATH update: %w (%s)", err, strings.TrimSpace(string(out)))
	}
//line internal/bootstrap/bootstrap.xgo:392:1
	return nil
}
//line internal/bootstrap/bootstrap.xgo:144:1
func installUnix(binDir string, o Options) error {
//line internal/bootstrap/bootstrap.xgo:145:1
	arch, err := detectArch()
//line internal/bootstrap/bootstrap.xgo:146:1
	if err != nil {
//line internal/bootstrap/bootstrap.xgo:147:1
		return err
	}
//line internal/bootstrap/bootstrap.xgo:149:1
	goos := runtime.GOOS
//line internal/bootstrap/bootstrap.xgo:150:1
	tryURLs := buildTryURLsUnix(o.Repo, o.Version, goos, arch)
//line internal/bootstrap/bootstrap.xgo:152:1
	tmp := filepath.Join(os.TempDir(), fmt.Sprintf("xgoup-%d.tgz", time.Now().UnixNano()))
//line internal/bootstrap/bootstrap.xgo:154:1
	var lastErr error
//line internal/bootstrap/bootstrap.xgo:155:1
	if o.ZipPath != "" {
//line internal/bootstrap/bootstrap.xgo:156:1
		if
//line internal/bootstrap/bootstrap.xgo:156:1
		_, err := os.Stat(o.ZipPath); err != nil {
//line internal/bootstrap/bootstrap.xgo:157:1
			return err
		}
//line internal/bootstrap/bootstrap.xgo:159:1
		tmp = o.ZipPath
	} else {
//line internal/bootstrap/bootstrap.xgo:161:1
		defer func() {
//line internal/bootstrap/bootstrap.xgo:161:1
			_ = os.Remove(tmp)
		}()
		for
//line internal/bootstrap/bootstrap.xgo:162:1
		_, u := range tryURLs {
//line internal/bootstrap/bootstrap.xgo:163:1
			logf(o, "[xgoup] download: %s", u)
//line internal/bootstrap/bootstrap.xgo:164:1
			if
//line internal/bootstrap/bootstrap.xgo:164:1
			err := httpGetToFile(u, tmp); err != nil {
//line internal/bootstrap/bootstrap.xgo:165:1
				lastErr = err
//line internal/bootstrap/bootstrap.xgo:166:1
				logf(o, "[xgoup] download failed: %v", err)
//line internal/bootstrap/bootstrap.xgo:167:1
				continue
			}
//line internal/bootstrap/bootstrap.xgo:169:1
			lastErr = nil
//line internal/bootstrap/bootstrap.xgo:170:1
			break
		}
//line internal/bootstrap/bootstrap.xgo:172:1
		if lastErr != nil {
//line internal/bootstrap/bootstrap.xgo:173:1
			return lastErr
		}
	}
//line internal/bootstrap/bootstrap.xgo:177:1
	if
//line internal/bootstrap/bootstrap.xgo:177:1
	err := extractTarGzXgoup(tmp, filepath.Join(binDir, "xgoup")); err != nil {
//line internal/bootstrap/bootstrap.xgo:178:1
		return fmt.Errorf("extract: %w", err)
	}
//line internal/bootstrap/bootstrap.xgo:180:1
	if
//line internal/bootstrap/bootstrap.xgo:180:1
	err := os.Chmod(filepath.Join(binDir, "xgoup"), 0o755); err != nil {
//line internal/bootstrap/bootstrap.xgo:181:1
		return err
	}
//line internal/bootstrap/bootstrap.xgo:183:1
	logf(o, "[xgoup] installed: %s", binDir)
//line internal/bootstrap/bootstrap.xgo:185:1
	if o.ModifyPath {
//line internal/bootstrap/bootstrap.xgo:186:1
		if
//line internal/bootstrap/bootstrap.xgo:186:1
		err := appendUnixUserPath(binDir); err != nil {
//line internal/bootstrap/bootstrap.xgo:187:1
			logf(o, "[xgoup] PATH hint failed: %v", err)
		}
	}
//line internal/bootstrap/bootstrap.xgo:191:1
	cmdPath := filepath.Join(binDir, "xgoup")
//line internal/bootstrap/bootstrap.xgo:192:1
	logf(o, "[xgoup] try: %s --version", cmdPath)
//line internal/bootstrap/bootstrap.xgo:193:1
	out, err := exec.Command(cmdPath, "--version").CombinedOutput()
//line internal/bootstrap/bootstrap.xgo:194:1
	if
//line internal/bootstrap/bootstrap.xgo:194:1
	text := strings.TrimSpace(string(out)); text != "" {
//line internal/bootstrap/bootstrap.xgo:195:1
		fmt.Println(text)
	}
//line internal/bootstrap/bootstrap.xgo:197:1
	if err != nil {
//line internal/bootstrap/bootstrap.xgo:198:1
		logf(o, "[xgoup] xgoup exit: %v", err)
	}
//line internal/bootstrap/bootstrap.xgo:200:1
	return nil
}
//line internal/bootstrap/bootstrap.xgo:217:1
func buildTryURLsUnix(repo string, version string, goos string, arch string) []string {
//line internal/bootstrap/bootstrap.xgo:218:1
	var try []string
//line internal/bootstrap/bootstrap.xgo:219:1
	if version != "" && version != "latest" {
//line internal/bootstrap/bootstrap.xgo:220:1
		try = append(try, fmt.Sprintf("https://github.com/%s/releases/download/%s/xgoup-%s-%s-%s.tar.gz", repo, version, version, goos, arch))
	}
//line internal/bootstrap/bootstrap.xgo:222:1
	if version == "latest" {
//line internal/bootstrap/bootstrap.xgo:223:1
		if
//line internal/bootstrap/bootstrap.xgo:223:1
		tag, err := getLatestReleaseTag(repo); err == nil {
//line internal/bootstrap/bootstrap.xgo:224:1
			try = append(try, fmt.Sprintf("https://github.com/%s/releases/download/%s/xgoup-%s-%s-%s.tar.gz", repo, tag, tag, goos, arch))
		}
	}
//line internal/bootstrap/bootstrap.xgo:227:1
	return try
}
//line internal/bootstrap/bootstrap.xgo:345:1
func extractTarGzXgoup(tgzPath string, destBin string) error {
//line internal/bootstrap/bootstrap.xgo:346:1
	f, err := os.Open(tgzPath)
//line internal/bootstrap/bootstrap.xgo:347:1
	if err != nil {
//line internal/bootstrap/bootstrap.xgo:348:1
		return err
	}
//line internal/bootstrap/bootstrap.xgo:350:1
	defer f.Close()
//line internal/bootstrap/bootstrap.xgo:351:1
	gz, err := gzip.NewReader(f)
//line internal/bootstrap/bootstrap.xgo:352:1
	if err != nil {
//line internal/bootstrap/bootstrap.xgo:353:1
		return err
	}
//line internal/bootstrap/bootstrap.xgo:355:1
	defer gz.Close()
//line internal/bootstrap/bootstrap.xgo:356:1
	tr := tar.NewReader(gz)
//line internal/bootstrap/bootstrap.xgo:357:1
	for {
//line internal/bootstrap/bootstrap.xgo:358:1
		hdr, err := tr.Next()
//line internal/bootstrap/bootstrap.xgo:359:1
		if err == io.EOF {
//line internal/bootstrap/bootstrap.xgo:360:1
			break
		}
//line internal/bootstrap/bootstrap.xgo:362:1
		if err != nil {
//line internal/bootstrap/bootstrap.xgo:363:1
			return err
		}
//line internal/bootstrap/bootstrap.xgo:365:1
		if hdr.Typeflag != tar.TypeReg {
//line internal/bootstrap/bootstrap.xgo:366:1
			continue
		}
//line internal/bootstrap/bootstrap.xgo:368:1
		base := filepath.Base(hdr.Name)
//line internal/bootstrap/bootstrap.xgo:369:1
		if base != "xgoup" {
//line internal/bootstrap/bootstrap.xgo:370:1
			continue
		}
//line internal/bootstrap/bootstrap.xgo:372:1
		out, err := os.Create(destBin)
//line internal/bootstrap/bootstrap.xgo:373:1
		if err != nil {
//line internal/bootstrap/bootstrap.xgo:374:1
			return err
		}
//line internal/bootstrap/bootstrap.xgo:376:1
		if
//line internal/bootstrap/bootstrap.xgo:376:1
		_, err := io.Copy(out, tr); err != nil {
//line internal/bootstrap/bootstrap.xgo:377:1
			out.Close()
//line internal/bootstrap/bootstrap.xgo:378:1
			return err
		}
//line internal/bootstrap/bootstrap.xgo:380:1
		return out.Close()
	}
//line internal/bootstrap/bootstrap.xgo:382:1
	return errors.New("no file named xgoup in archive")
}
//line internal/bootstrap/bootstrap.xgo:395:1
func appendUnixUserPath(binDir string) error {
//line internal/bootstrap/bootstrap.xgo:396:1
	home, err := os.UserHomeDir()
//line internal/bootstrap/bootstrap.xgo:397:1
	if err != nil {
//line internal/bootstrap/bootstrap.xgo:398:1
		return err
	}
//line internal/bootstrap/bootstrap.xgo:400:1
	rc := filepath.Join(home, ".profile")
//line internal/bootstrap/bootstrap.xgo:401:1
	line := fmt.Sprintf(`export PATH="%s:$PATH"`, binDir)
//line internal/bootstrap/bootstrap.xgo:402:1
	b, err := os.ReadFile(rc)
//line internal/bootstrap/bootstrap.xgo:403:1
	if err != nil && !os.IsNotExist(err) {
//line internal/bootstrap/bootstrap.xgo:404:1
		return err
	}
//line internal/bootstrap/bootstrap.xgo:406:1
	s := string(b)
//line internal/bootstrap/bootstrap.xgo:407:1
	if strings.Contains(s, binDir) {
//line internal/bootstrap/bootstrap.xgo:408:1
		return nil
	}
//line internal/bootstrap/bootstrap.xgo:410:1
	f, err := os.OpenFile(rc, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
//line internal/bootstrap/bootstrap.xgo:411:1
	if err != nil {
//line internal/bootstrap/bootstrap.xgo:412:1
		return err
	}
//line internal/bootstrap/bootstrap.xgo:414:1
	defer f.Close()
//line internal/bootstrap/bootstrap.xgo:415:1
	if len(s) > 0 && !strings.HasSuffix(s, "\n") {
//line internal/bootstrap/bootstrap.xgo:416:1
		if
//line internal/bootstrap/bootstrap.xgo:416:1
		_, err := f.WriteString("\n"); err != nil {
//line internal/bootstrap/bootstrap.xgo:417:1
			return err
		}
	}
//line internal/bootstrap/bootstrap.xgo:420:1
	_, err = fmt.Fprintf(f, "\n# xgoup self install\n%s\n", line)
//line internal/bootstrap/bootstrap.xgo:421:1
	return err
}
