// Code generated by xgo (XGo); DO NOT EDIT.

package home

import (
	"errors"
	"os"
	"path/filepath"
)

const _ = true

type Paths struct {
	Home       string
	Toolchains string
	Metadata   string
	Config     string
}
//line internal/home/home.xgo:16:1
func Resolve() (Paths, error) {
//line internal/home/home.xgo:17:1
	home := os.Getenv("XGOUP_HOME")
//line internal/home/home.xgo:18:1
	if home == "" {
//line internal/home/home.xgo:19:1
		up := os.Getenv("USERPROFILE")
//line internal/home/home.xgo:20:1
		if up != "" {
//line internal/home/home.xgo:21:1
			home = filepath.Join(up, ".xgoup")
		} else {
//line internal/home/home.xgo:23:1
			home = filepath.Join(os.TempDir(), ".xgoup")
		}
	}
//line internal/home/home.xgo:26:1
	if !filepath.IsAbs(home) {
//line internal/home/home.xgo:27:1
		abs, err := filepath.Abs(home)
//line internal/home/home.xgo:28:1
		if err != nil {
//line internal/home/home.xgo:29:1
			return Paths{}, err
		}
//line internal/home/home.xgo:31:1
		home = abs
	}
//line internal/home/home.xgo:34:1
	return Paths{Home: home, Toolchains: filepath.Join(home, "toolchains"), Metadata: filepath.Join(home, "metadata"), Config: filepath.Join(home, "config.toml")}, nil
}
//line internal/home/home.xgo:42:1
func EnsureDirs(p Paths) error {
//line internal/home/home.xgo:43:1
	if p.Home == "" {
//line internal/home/home.xgo:44:1
		return errors.New("home is empty")
	}
//line internal/home/home.xgo:46:1
	if
//line internal/home/home.xgo:46:1
	err := os.MkdirAll(p.Toolchains, 0o755); err != nil {
//line internal/home/home.xgo:47:1
		return err
	}
//line internal/home/home.xgo:49:1
	if
//line internal/home/home.xgo:49:1
	err := os.MkdirAll(p.Metadata, 0o755); err != nil {
//line internal/home/home.xgo:50:1
		return err
	}
//line internal/home/home.xgo:52:1
	return nil
}
