// Code generated by xgo (XGo); DO NOT EDIT.

package resolve

import (
	"errors"
	"fmt"
	"github.com/fanfeilong/xgoup/internal/config"
	"github.com/fanfeilong/xgoup/internal/home"
	"github.com/fanfeilong/xgoup/internal/meta"
	"github.com/pelletier/go-toml/v2"
	"os"
	"path/filepath"
	"strings"
)

const _ = true

type Result struct {
	Name    string
	Meta    meta.ToolchainMeta
	XgoExe  string
	XgoRoot string
	BinDir  string
}
//line internal/resolve/resolve.xgo:24:1
func ResolveToolchain(p home.Paths, c config.Config, cliName string, cwd string) (Result, error) {
//line internal/resolve/resolve.xgo:25:1
	if cliName != "" {
//line internal/resolve/resolve.xgo:81:1
		return byName(p, c, cliName)
	}
//line internal/resolve/resolve.xgo:28:1
	if
//line internal/resolve/resolve.xgo:28:1
	env := os.Getenv("XGO_TOOLCHAIN"); env != "" {
//line internal/resolve/resolve.xgo:29:1
		return byName(p, c, env)
	}
//line internal/resolve/resolve.xgo:31:1
	if cwd != "" {
//line internal/resolve/resolve.xgo:32:1
		if
//line internal/resolve/resolve.xgo:32:1
		name, ok := projectOverride(cwd); ok {
//line internal/resolve/resolve.xgo:33:1
			return byName(p, c, name)
		}
	}
//line internal/resolve/resolve.xgo:36:1
	if c.DefaultToolchain != "" {
//line internal/resolve/resolve.xgo:37:1
		return byName(p, c, c.DefaultToolchain)
	}
//line internal/resolve/resolve.xgo:39:1
	return Result{}, errors.New("no toolchain selected (set default or use --toolchain)")
}
//line internal/resolve/resolve.xgo:64:1
func byName(p home.Paths, c config.Config, name string) (Result, error) {
//line internal/resolve/resolve.xgo:65:1
	if
//line internal/resolve/resolve.xgo:65:1
	_, ok := c.Toolchains[name]; !ok {
//line internal/resolve/resolve.xgo:66:1
		return Result{}, fmt.Errorf("toolchain not found: %s", name)
	}
//line internal/resolve/resolve.xgo:68:1
	m, err := meta.Load(p.Metadata, name)
//line internal/resolve/resolve.xgo:69:1
	if err != nil {
//line internal/resolve/resolve.xgo:70:1
		return Result{}, err
	}
//line internal/resolve/resolve.xgo:72:1
	if m.XgoBin == "" {
//line internal/resolve/resolve.xgo:74:1
		if m.RootPath != "" {
//line internal/resolve/resolve.xgo:75:1
			m.XgoBin = filepath.Join(m.RootPath, "bin", "xgo.exe")
		}
	}
//line internal/resolve/resolve.xgo:78:1
	if m.XgoRootValue == "" {
//line internal/resolve/resolve.xgo:79:1
		m.XgoRootValue = m.RootPath
	}
//line internal/resolve/resolve.xgo:81:1
	return Result{Name: name, Meta: m, XgoExe: m.XgoBin, XgoRoot: m.XgoRootValue, BinDir: filepath.Dir(m.XgoBin)}, nil
}
//line internal/resolve/resolve.xgo:42:1
func projectOverride(start string) (string, bool) {
//line internal/resolve/resolve.xgo:43:1
	dir := start
//line internal/resolve/resolve.xgo:44:1
	for {
//line internal/resolve/resolve.xgo:45:1
		p := filepath.Join(dir, "xgo-toolchain.toml")
//line internal/resolve/resolve.xgo:46:1
		b, err := os.ReadFile(p)
//line internal/resolve/resolve.xgo:47:1
		if err == nil {
//line internal/resolve/resolve.xgo:48:1
			var v struct {
				Toolchain string `toml:"toolchain"`
			}
//line internal/resolve/resolve.xgo:51:1
			if
//line internal/resolve/resolve.xgo:51:1
			err := toml.Unmarshal(b, &v); err == nil && strings.TrimSpace(v.Toolchain) != "" {
//line internal/resolve/resolve.xgo:52:1
				return strings.TrimSpace(v.Toolchain), true
			}
//line internal/resolve/resolve.xgo:54:1
			return "", false
		}
//line internal/resolve/resolve.xgo:56:1
		parent := filepath.Dir(dir)
//line internal/resolve/resolve.xgo:57:1
		if parent == dir {
//line internal/resolve/resolve.xgo:58:1
			return "", false
		}
//line internal/resolve/resolve.xgo:60:1
		dir = parent
	}
}
