// Code generated by xgo (XGo); DO NOT EDIT.

package userenv

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

const _ = true
const (
	unixEnvRel  = ".xgoup/env.sh"
	markerBegin = "# >>> xgoup env (managed)"
	markerEnd   = "# <<< xgoup env (managed)"
)
//line internal/userenv/userenv.xgo:18:1
// PersistDefaultToolchainEnv writes XGOROOT (and toolchain bin on PATH) so new shells
// pick up the default toolchain after `xgoup default <name>`.
// - Windows: user environment variables XGOROOT and PATH (prepend toolchain\bin if missing).
// - Unix: ~/.xgoup/env.sh and a sourced block in ~/.profile / ~/.zshrc / ~/.bashrc when present.
func PersistDefaultToolchainEnv(root string) error {
//line internal/userenv/userenv.xgo:23:1
	root = strings.TrimSpace(root)
//line internal/userenv/userenv.xgo:24:1
	if root == "" {
//line internal/userenv/userenv.xgo:25:1
		return fmt.Errorf("empty toolchain root")
	}
//line internal/userenv/userenv.xgo:27:1
	switch runtime.GOOS {
//line internal/userenv/userenv.xgo:28:1
	case "windows":
//line internal/userenv/userenv.xgo:54:1
		return persistWindows(root)
//line internal/userenv/userenv.xgo:30:1
	default:
//line internal/userenv/userenv.xgo:123:1
		return persistUnix(root)
	}
}
//line internal/userenv/userenv.xgo:35:1
func persistWindows(root string) error {
//line internal/userenv/userenv.xgo:36:1
	esc := strings.ReplaceAll(root, `'`, `''`)
//line internal/userenv/userenv.xgo:37:1
	ps := fmt.Sprintf(`
$root = '%s'
[Environment]::SetEnvironmentVariable('XGOROOT', $root, 'User')
$bin = Join-Path $root 'bin'
$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
if (-not $userPath) { $userPath = '' }
$parts = $userPath.Split(';') | Where-Object { $_ -ne '' }
if ($parts -notcontains $bin) {
  $newPath = if ($userPath.Trim().Length -gt 0) { "$bin;$userPath" } else { $bin }
  [Environment]::SetEnvironmentVariable('Path', $newPath, 'User')
}
`, esc)
//line internal/userenv/userenv.xgo:49:1
	cmd := exec.Command("powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", ps)
//line internal/userenv/userenv.xgo:50:1
	out, err := cmd.CombinedOutput()
//line internal/userenv/userenv.xgo:51:1
	if err != nil {
//line internal/userenv/userenv.xgo:52:1
		return fmt.Errorf("%w: %s", err, strings.TrimSpace(string(out)))
	}
//line internal/userenv/userenv.xgo:54:1
	return nil
}
//line internal/userenv/userenv.xgo:57:1
func persistUnix(root string) error {
//line internal/userenv/userenv.xgo:58:1
	home, err := os.UserHomeDir()
//line internal/userenv/userenv.xgo:59:1
	if err != nil {
//line internal/userenv/userenv.xgo:60:1
		return err
	}
//line internal/userenv/userenv.xgo:62:1
	xgoupDir := filepath.Join(home, ".xgoup")
//line internal/userenv/userenv.xgo:63:1
	if
//line internal/userenv/userenv.xgo:63:1
	err := os.MkdirAll(xgoupDir, 0o755); err != nil {
//line internal/userenv/userenv.xgo:64:1
		return err
	}
//line internal/userenv/userenv.xgo:66:1
	envPath := filepath.Join(home, unixEnvRel)
//line internal/userenv/userenv.xgo:67:1
	q := posixSingleQuote(root)
//line internal/userenv/userenv.xgo:68:1
	body := fmt.Sprintf(`# Generated by xgoup default — do not edit.
export XGOROOT=%s
export PATH="$XGOROOT/bin:$PATH"
`, q)
//line internal/userenv/userenv.xgo:72:1
	if
//line internal/userenv/userenv.xgo:72:1
	err := os.WriteFile(envPath, []byte(body+"\n"), 0o644); err != nil {
//line internal/userenv/userenv.xgo:73:1
		return err
	}
//line internal/userenv/userenv.xgo:76:1
	line := `[ -f "$HOME/.xgoup/env.sh" ] && . "$HOME/.xgoup/env.sh"`
//line internal/userenv/userenv.xgo:78:1
	candidates := []string{".zshrc", ".bashrc", ".bash_profile", ".profile"}
//line internal/userenv/userenv.xgo:79:1
	var target string
	for
//line internal/userenv/userenv.xgo:80:1
	_, name := range candidates {
//line internal/userenv/userenv.xgo:81:1
		p := filepath.Join(home, name)
//line internal/userenv/userenv.xgo:82:1
		if
//line internal/userenv/userenv.xgo:82:1
		_, err := os.Stat(p); err == nil {
//line internal/userenv/userenv.xgo:83:1
			target = p
//line internal/userenv/userenv.xgo:84:1
			break
		}
	}
//line internal/userenv/userenv.xgo:87:1
	if target == "" {
//line internal/userenv/userenv.xgo:88:1
		if runtime.GOOS == "darwin" {
//line internal/userenv/userenv.xgo:89:1
			target = filepath.Join(home, ".zshrc")
		} else {
//line internal/userenv/userenv.xgo:91:1
			target = filepath.Join(home, ".profile")
		}
	}
//line internal/userenv/userenv.xgo:123:1
	return mergeSourceLine(target, line)
}
//line internal/userenv/userenv.xgo:126:1
func posixSingleQuote(s string) string {
//line internal/userenv/userenv.xgo:127:1
	return `'` + strings.ReplaceAll(s, `'`, `'"'"'`) + `'`
}
//line internal/userenv/userenv.xgo:97:1
func mergeSourceLine(path string, line string) error {
//line internal/userenv/userenv.xgo:98:1
	b, err := os.ReadFile(path)
//line internal/userenv/userenv.xgo:99:1
	if err != nil {
//line internal/userenv/userenv.xgo:100:1
		if !os.IsNotExist(err) {
//line internal/userenv/userenv.xgo:101:1
			return err
		}
//line internal/userenv/userenv.xgo:103:1
		b = nil
	}
//line internal/userenv/userenv.xgo:105:1
	s := string(b)
//line internal/userenv/userenv.xgo:106:1
	if strings.Contains(s, markerBegin) && strings.Contains(s, "env.sh") {
//line internal/userenv/userenv.xgo:107:1
		return nil
	}
//line internal/userenv/userenv.xgo:109:1
	if strings.Contains(s, ".xgoup/env.sh") {
//line internal/userenv/userenv.xgo:110:1
		return nil
	}
//line internal/userenv/userenv.xgo:112:1
	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
//line internal/userenv/userenv.xgo:113:1
	if err != nil {
//line internal/userenv/userenv.xgo:114:1
		return err
	}
//line internal/userenv/userenv.xgo:116:1
	defer f.Close()
//line internal/userenv/userenv.xgo:117:1
	if len(s) > 0 && !strings.HasSuffix(s, "\n") {
//line internal/userenv/userenv.xgo:118:1
		if
//line internal/userenv/userenv.xgo:118:1
		_, err := f.WriteString("\n"); err != nil {
//line internal/userenv/userenv.xgo:119:1
			return err
		}
	}
//line internal/userenv/userenv.xgo:122:1
	_, err = fmt.Fprintf(f, "\n%s\n%s\n%s\n", markerBegin, strings.TrimSpace(line), markerEnd)
//line internal/userenv/userenv.xgo:123:1
	return err
}
