// Code generated by xgo (XGo); DO NOT EDIT.

package buildinfo

const _ = true
// These can be overridden via -ldflags at build time.
var Version = "0.1.8"
// These can be overridden via -ldflags at build time.
var Commit = ""
// These can be overridden via -ldflags at build time.
var Date = ""
