// Code generated by xgo (XGo); DO NOT EDIT.

package selfupdate

import (
	"archive/zip"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

const _ = true

type Options struct {
	Repo string
}
//line internal/selfupdate/selfupdate.xgo:20:1
func Update(opt Options) (string, error) {
//line internal/selfupdate/selfupdate.xgo:21:1
	repo := opt.Repo
//line internal/selfupdate/selfupdate.xgo:22:1
	if repo == "" {
//line internal/selfupdate/selfupdate.xgo:23:1
		repo = "fanfeilong/xgoup"
	}
//line internal/selfupdate/selfupdate.xgo:25:1
	arch, err := windowsArch()
//line internal/selfupdate/selfupdate.xgo:26:1
	if err != nil {
//line internal/selfupdate/selfupdate.xgo:27:1
		return "", err
	}
//line internal/selfupdate/selfupdate.xgo:29:1
	url := fmt.Sprintf("https://github.com/%s/releases/latest/download/xgoup-windows-%s.zip", repo, arch)
//line internal/selfupdate/selfupdate.xgo:31:1
	tmpZip := filepath.Join(os.TempDir(), fmt.Sprintf("xgoup-self-%d.zip", time.Now().UnixNano()))
//line internal/selfupdate/selfupdate.xgo:32:1
	defer os.Remove(tmpZip)
//line internal/selfupdate/selfupdate.xgo:33:1
	if
//line internal/selfupdate/selfupdate.xgo:33:1
	err := httpGetToFile(url, tmpZip); err != nil {
//line internal/selfupdate/selfupdate.xgo:34:1
		return "", err
	}
//line internal/selfupdate/selfupdate.xgo:37:1
	exe, err := os.Executable()
//line internal/selfupdate/selfupdate.xgo:38:1
	if err != nil {
//line internal/selfupdate/selfupdate.xgo:39:1
		return "", err
	}
//line internal/selfupdate/selfupdate.xgo:42:1
	tmpExe := exe + ".new"
//line internal/selfupdate/selfupdate.xgo:43:1
	if
//line internal/selfupdate/selfupdate.xgo:43:1
	err := extractFileFromZip(tmpZip, "xgoup.exe", tmpExe); err != nil {
//line internal/selfupdate/selfupdate.xgo:45:1
		if
//line internal/selfupdate/selfupdate.xgo:45:1
		err2 := extractAnyBasenameFromZip(tmpZip, "xgoup.exe", tmpExe); err2 != nil {
//line internal/selfupdate/selfupdate.xgo:46:1
			return "", err
		}
	}
//line internal/selfupdate/selfupdate.xgo:51:1
	backup := exe + ".old"
//line internal/selfupdate/selfupdate.xgo:52:1
	_ = os.Remove(backup)
//line internal/selfupdate/selfupdate.xgo:53:1
	if
//line internal/selfupdate/selfupdate.xgo:53:1
	err := os.Rename(exe, backup); err != nil {
//line internal/selfupdate/selfupdate.xgo:55:1
		return tmpExe, fmt.Errorf("downloaded update to %s (failed to replace running exe: %v)", tmpExe, err)
	}
//line internal/selfupdate/selfupdate.xgo:57:1
	if
//line internal/selfupdate/selfupdate.xgo:57:1
	err := os.Rename(tmpExe, exe); err != nil {
//line internal/selfupdate/selfupdate.xgo:58:1
		_ = os.Rename(backup, exe)
//line internal/selfupdate/selfupdate.xgo:59:1
		return "", err
	}
//line internal/selfupdate/selfupdate.xgo:61:1
	_ = os.Remove(backup)
//line internal/selfupdate/selfupdate.xgo:62:1
	return exe, nil
}
//line internal/selfupdate/selfupdate.xgo:75:1
func windowsArch() (string, error) {
//line internal/selfupdate/selfupdate.xgo:76:1
	switch runtime.GOARCH {
//line internal/selfupdate/selfupdate.xgo:77:1
	case "amd64":
//line internal/selfupdate/selfupdate.xgo:78:1
		return "amd64", nil
//line internal/selfupdate/selfupdate.xgo:79:1
	case "arm64":
//line internal/selfupdate/selfupdate.xgo:80:1
		return "arm64", nil
//line internal/selfupdate/selfupdate.xgo:81:1
	default:
//line internal/selfupdate/selfupdate.xgo:82:1
		return "", fmt.Errorf("unsupported arch: %s", runtime.GOARCH)
	}
}
//line internal/selfupdate/selfupdate.xgo:86:1
func httpGetToFile(url string, path string) error {
//line internal/selfupdate/selfupdate.xgo:87:1
	req, err := http.NewRequest("GET", url, nil)
//line internal/selfupdate/selfupdate.xgo:88:1
	if err != nil {
//line internal/selfupdate/selfupdate.xgo:89:1
		return err
	}
//line internal/selfupdate/selfupdate.xgo:91:1
	req.Header.Set("User-Agent", "xgoup")
//line internal/selfupdate/selfupdate.xgo:92:1
	req.Header.Set("Accept", "application/octet-stream")
//line internal/selfupdate/selfupdate.xgo:93:1
	client := &http.Client{Timeout: 120 * time.Second}
//line internal/selfupdate/selfupdate.xgo:94:1
	resp, err := client.Do(req)
//line internal/selfupdate/selfupdate.xgo:95:1
	if err != nil {
//line internal/selfupdate/selfupdate.xgo:96:1
		return err
	}
//line internal/selfupdate/selfupdate.xgo:98:1
	defer resp.Body.Close()
//line internal/selfupdate/selfupdate.xgo:99:1
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
//line internal/selfupdate/selfupdate.xgo:100:1
		b, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
//line internal/selfupdate/selfupdate.xgo:101:1
		return fmt.Errorf("GET %s: status=%s body=%q", url, resp.Status, string(b))
	}
//line internal/selfupdate/selfupdate.xgo:103:1
	f, err := os.Create(path)
//line internal/selfupdate/selfupdate.xgo:104:1
	if err != nil {
//line internal/selfupdate/selfupdate.xgo:105:1
		return err
	}
//line internal/selfupdate/selfupdate.xgo:107:1
	defer f.Close()
//line internal/selfupdate/selfupdate.xgo:108:1
	_, err = io.Copy(f, resp.Body)
//line internal/selfupdate/selfupdate.xgo:109:1
	return err
}
//line internal/selfupdate/selfupdate.xgo:112:1
func extractFileFromZip(zipPath string, wantName string, outPath string) error {
//line internal/selfupdate/selfupdate.xgo:113:1
	r, err := zip.OpenReader(zipPath)
//line internal/selfupdate/selfupdate.xgo:114:1
	if err != nil {
//line internal/selfupdate/selfupdate.xgo:115:1
		return err
	}
//line internal/selfupdate/selfupdate.xgo:117:1
	defer r.Close()
	for
//line internal/selfupdate/selfupdate.xgo:118:1
	_, f := range r.File {
//line internal/selfupdate/selfupdate.xgo:119:1
		if filepath.Base(strings.ReplaceAll(f.Name, "\\", "/")) != wantName {
//line internal/selfupdate/selfupdate.xgo:120:1
			continue
		}
//line internal/selfupdate/selfupdate.xgo:158:1
		return writeZipFile(f, outPath)
	}
//line internal/selfupdate/selfupdate.xgo:124:1
	return fmt.Errorf("missing %q in zip", wantName)
}
//line internal/selfupdate/selfupdate.xgo:141:1
func writeZipFile(f *zip.File, outPath string) error {
//line internal/selfupdate/selfupdate.xgo:142:1
	rc, err := f.Open()
//line internal/selfupdate/selfupdate.xgo:143:1
	if err != nil {
//line internal/selfupdate/selfupdate.xgo:144:1
		return err
	}
//line internal/selfupdate/selfupdate.xgo:146:1
	defer rc.Close()
//line internal/selfupdate/selfupdate.xgo:147:1
	if
//line internal/selfupdate/selfupdate.xgo:147:1
	err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
//line internal/selfupdate/selfupdate.xgo:148:1
		return err
	}
//line internal/selfupdate/selfupdate.xgo:150:1
	out, err := os.Create(outPath)
//line internal/selfupdate/selfupdate.xgo:151:1
	if err != nil {
//line internal/selfupdate/selfupdate.xgo:152:1
		return err
	}
//line internal/selfupdate/selfupdate.xgo:154:1
	defer out.Close()
//line internal/selfupdate/selfupdate.xgo:155:1
	if
//line internal/selfupdate/selfupdate.xgo:155:1
	_, err := io.Copy(out, rc); err != nil {
//line internal/selfupdate/selfupdate.xgo:156:1
		return err
	}
//line internal/selfupdate/selfupdate.xgo:158:1
	return nil
}
//line internal/selfupdate/selfupdate.xgo:127:1
func extractAnyBasenameFromZip(zipPath string, wantBase string, outPath string) error {
//line internal/selfupdate/selfupdate.xgo:128:1
	r, err := zip.OpenReader(zipPath)
//line internal/selfupdate/selfupdate.xgo:129:1
	if err != nil {
//line internal/selfupdate/selfupdate.xgo:130:1
		return err
	}
//line internal/selfupdate/selfupdate.xgo:132:1
	defer r.Close()
	for
//line internal/selfupdate/selfupdate.xgo:133:1
	_, f := range r.File {
//line internal/selfupdate/selfupdate.xgo:134:1
		if filepath.Base(strings.ReplaceAll(f.Name, "\\", "/")) == wantBase {
//line internal/selfupdate/selfupdate.xgo:135:1
			return writeZipFile(f, outPath)
		}
	}
//line internal/selfupdate/selfupdate.xgo:138:1
	return fmt.Errorf("missing %q in zip", wantBase)
}
//line internal/selfupdate/selfupdate.xgo:65:1
func Uninstall(homeDir string, force bool) error {
//line internal/selfupdate/selfupdate.xgo:66:1
	if homeDir == "" {
//line internal/selfupdate/selfupdate.xgo:67:1
		return errors.New("homeDir is empty")
	}
//line internal/selfupdate/selfupdate.xgo:69:1
	if !force {
//line internal/selfupdate/selfupdate.xgo:70:1
		return errors.New("refusing to uninstall without --force")
	}
//line internal/selfupdate/selfupdate.xgo:72:1
	return os.RemoveAll(homeDir)
}
