// Code generated by xgo (XGo); DO NOT EDIT.

package config

import (
	"errors"
	"github.com/pelletier/go-toml/v2"
	"os"
	"path/filepath"
	"time"
)

const _ = true

type Settings struct {
	AutoSelfUpdate bool `toml:"auto_self_update"`
	AutoPathHint   bool `toml:"auto_path_hint"`
	Telemetry      bool `toml:"telemetry"`
}
type Registries struct {
	SourceRepo     string `toml:"source_repo"`
	ReleaseBaseURL string `toml:"release_base_url"`
}
type Toolchain struct {
	Kind    string `toml:"kind"`
	Path    string `toml:"path"`
	Managed bool   `toml:"managed"`
	Version string `toml:"version,omitempty"`
	Repo    string `toml:"repo,omitempty"`
	Ref     string `toml:"ref,omitempty"`
	Commit  string `toml:"commit,omitempty"`
}
type Config struct {
	Version          int                  `toml:"version"`
	DefaultToolchain string               `toml:"default_toolchain"`
	LastUpdateCheck  string               `toml:"last_update_check,omitempty"`
	Settings         Settings             `toml:"settings"`
	Registries       Registries           `toml:"registries"`
	Toolchains       map[string]Toolchain `toml:"toolchains"`
}
//line internal/config/config.xgo:42:1
func Default(sourceRepo string) Config {
//line internal/config/config.xgo:43:1
	return Config{Version: 1, DefaultToolchain: "", LastUpdateCheck: time.Now().UTC().Format(time.RFC3339), Settings: Settings{AutoSelfUpdate: true, AutoPathHint: true, Telemetry: false}, Registries: Registries{SourceRepo: sourceRepo, ReleaseBaseURL: "https://github.com/<org>/xgoup/releases/download"}, Toolchains: map[string]Toolchain{}}
}
//line internal/config/config.xgo:60:1
func Load(path string) (Config, error) {
//line internal/config/config.xgo:61:1
	b, err := os.ReadFile(path)
//line internal/config/config.xgo:62:1
	if err != nil {
//line internal/config/config.xgo:63:1
		return Config{}, err
	}
//line internal/config/config.xgo:65:1
	var c Config
//line internal/config/config.xgo:66:1
	if
//line internal/config/config.xgo:66:1
	err := toml.Unmarshal(b, &c); err != nil {
//line internal/config/config.xgo:67:1
		return Config{}, err
	}
//line internal/config/config.xgo:69:1
	if c.Version == 0 {
//line internal/config/config.xgo:70:1
		c.Version = 1
	}
//line internal/config/config.xgo:72:1
	if c.Toolchains == nil {
//line internal/config/config.xgo:73:1
		c.Toolchains = map[string]Toolchain{}
	}
//line internal/config/config.xgo:75:1
	return c, nil
}
//line internal/config/config.xgo:78:1
func Save(path string, c Config) error {
//line internal/config/config.xgo:79:1
	if c.Version == 0 {
//line internal/config/config.xgo:80:1
		c.Version = 1
	}
//line internal/config/config.xgo:82:1
	if c.LastUpdateCheck == "" {
//line internal/config/config.xgo:83:1
		c.LastUpdateCheck = time.Now().UTC().Format(time.RFC3339)
	}
//line internal/config/config.xgo:85:1
	if c.Toolchains == nil {
//line internal/config/config.xgo:86:1
		c.Toolchains = map[string]Toolchain{}
	}
//line internal/config/config.xgo:88:1
	if
//line internal/config/config.xgo:88:1
	err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
//line internal/config/config.xgo:89:1
		return err
	}
//line internal/config/config.xgo:91:1
	b, err := toml.Marshal(c)
//line internal/config/config.xgo:92:1
	if err != nil {
//line internal/config/config.xgo:93:1
		return err
	}
//line internal/config/config.xgo:95:1
	return os.WriteFile(path, b, 0o644)
}
//line internal/config/config.xgo:98:1
func Validate(c Config) error {
//line internal/config/config.xgo:99:1
	if c.Version != 1 {
//line internal/config/config.xgo:100:1
		return errors.New("unsupported config version")
	}
//line internal/config/config.xgo:102:1
	if c.DefaultToolchain != "" {
//line internal/config/config.xgo:103:1
		if
//line internal/config/config.xgo:103:1
		_, ok := c.Toolchains[c.DefaultToolchain]; !ok {
//line internal/config/config.xgo:104:1
			return errors.New("default_toolchain does not exist in [toolchains]")
		}
	}
//line internal/config/config.xgo:107:1
	seen := map[string]bool{}
	for
//line internal/config/config.xgo:108:1
	name, tc := range c.Toolchains {
//line internal/config/config.xgo:109:1
		if name == "" {
//line internal/config/config.xgo:110:1
			return errors.New("toolchain name is empty")
		}
//line internal/config/config.xgo:112:1
		if !filepath.IsAbs(tc.Path) {
//line internal/config/config.xgo:113:1
			return errors.New("toolchain path must be absolute: " + name)
		}
//line internal/config/config.xgo:115:1
		if seen[tc.Path] {
//line internal/config/config.xgo:116:1
			return errors.New("duplicate toolchain path: " + tc.Path)
		}
//line internal/config/config.xgo:118:1
		seen[tc.Path] = true
//line internal/config/config.xgo:119:1
		if tc.Kind == "linked" && tc.Managed {
//line internal/config/config.xgo:120:1
			return errors.New("linked toolchain must have managed=false: " + name)
		}
//line internal/config/config.xgo:122:1
		if tc.Kind == "source" && tc.Repo == "" {
//line internal/config/config.xgo:123:1
			return errors.New("source toolchain requires repo: " + name)
		}
	}
//line internal/config/config.xgo:126:1
	return nil
}
